### ISSUE TITLE
rosbag compilation error with Boost 1.50 on OSX

### ISSUE THREAD

**Issue by hawesie** [ros/ros_comm#10]
This is from a fuerte install started today from fresh:

```
/Users/nah/ros-underlay/ros_comm/tools/rosbag/src/recorder.cpp:439:42: error: 
      no member named 'TIME_UTC' in namespace 'boost'; did you mean 'TIME_UTC_'?
            boost::xtime_get(&xt, boost::TIME_UTC);
                                  ~~~~~~~^~~~~~~~
                                         TIME_UTC_
/usr/local/include/boost/thread/xtime.hpp:23:5: note: 'TIME_UTC_' declared here
    TIME_UTC_=1
    ^
1 error generated.
```

Adding the `_` appears to fix it.

**Comment by vrabaud** [comment]
Fixed in bef00d344c2faea59672c47cd5509ee8269129b8 for Groovy and 2a50c0b3aa43fe338a608ede5abfa576edba0a97 in Fuerte. As we do not support Boost 1.50 officially we will not make a new package release for ros_comm just for that in Fuerte but it will be part of the next patch release. Thx.

**Comment by dirk-thomas** [comment]
The link to the changeset for Fuerte gives a 404 and the commit on the Fuerte branch does not show your patch. Have you pushed the patch to the branch?

**Comment by vrabaud** [comment]
sorry, that was 8857d910272559df63290d7fc16c2406624f8681 for Fuerte
