### ISSUE TITLE
rosbag play issue "Cannot find rosbag/play executable"

### ISSUE THREAD

**Issue by code-juggling** [ros/ros_comm#1037]
My Config: Ubuntu 14.04 LTS, ROS Indigo (latest updates installed)
I'm having a weird problem lately:
rosbag can't find the play executable anymore.
![rosbag_error](https://cloud.githubusercontent.com/assets/24550050/25341701/fdbd1b22-2909-11e7-9729-bcd3f9fe8822.jpg)

I did try these steps to solve the problem:
1. reinstalling ros-indigo-rosbag & ros-indigo-desktop-full
2. purge ros-indigo-desktop-full & autoremove the rest -> install again, rosdep init & update etc. like the beginners guide shows, paths are made, sourcing is done in my .bashrc for my exsisting workspace...
Didn't solve the problem :(

(I did check the .bag file with 'rosbag check one.bag' and it did not show any errors)
Those commands shown in the pictures are from the rosbag guide itself and they did work in the beginning, but 2 or 3 weeks ago (I guess since an update) they stopped working.

Can somebody help me?

Thanks in advance!

**Comment by mikepurvis** [comment]
Looks like your environment or installation are messed up. Please ask about this on http://answers.ros.org/

(To get things going in your question, please report the results of `rospack find rosbag` and `find /opt/ros/indigo/lib/rosbag`)
