### ISSUE TITLE
Completely disable logging outputs on screen

### ISSUE THREAD

**Issue by this-is-martin** [ros/ros_comm#1039]
Hi, 
I want to disable the ROS logging in the console completely, but still have the logging to the /rosout topic. I tried these two options:

1. Set output="log" in the launch file. This disables the output of Debug, Info and Warning messages but still, Error and Fatal messages are shown.
2. Set the logger level to Fatal but this completely disables the /rosout topic.

Are there any other possibilities I could try out? For me, it sounds like a design-issue, because, if I explicitly specify the "log" output, I do not want to have outputs in the console...

Otherwise, I would be grateful to see this fixed in the next ROS version! :)

Thanks!

**Comment by this-is-martin** [comment]
By the way, I have another logging framework running that should still be able to log everything to the console.

**Comment by dirk-thomas** [comment]
In ROS the log threshold determines that all log messages with a lower level are being ignored. The backend actually performing the logging can be swapped (see existing implementations: https://github.com/ros/ros_comm/tree/lunar-devel/tools/rosconsole/src/rosconsole/impl).

You use case of assigning separate thresholds for different sinks isn't supported. You might be able to [configure](https://github.com/ros/ros_comm/blob/lunar-devel/tools/rosconsole/config/rosconsole.config) / extend the log4cxx backend to match your needs.

But this is likely not a feature the maintainers will work on in the future. Please consider to contribute a pull request if this functionality is useful for you.

**Comment by dirk-thomas** [comment]
This issue was moved to ros/rosconsole#8
