### ISSUE TITLE
rospy: validate ROS_HOSTNAME at startup and provide a good error if bad  (ros ticket #3702)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#110]
I saw this user discussion http://groups.google.com/group/hbrobotics/msg/d724afb1db03ce2b

The problem turned out to be an incorrectly set ROS_HOSTNAME with "http://" at the front which is invalid.  But nothing caught it as being invalid.  

I feel like I filed this ticket before, but I couldn't find it so I'm refiling.  This should be done in both roscpp and rospy. 

This was the traceback:
{{{
Traceback (most recent call last): 
  File 
"/opt/ros/diamondback/stacks/ros_comm/tools/roslaunch/src/roslaunch/**init_ _.py", 
line 247, in main 
    p.start() 
  File 
"/opt/ros/diamondback/stacks/ros_comm/tools/roslaunch/src/roslaunch/parent. py", 
line 254, in start 
    self._start_infrastructure() 
  File 
"/opt/ros/diamondback/stacks/ros_comm/tools/roslaunch/src/roslaunch/parent. py", 
line 212, in _start_infrastructure 
    self._start_server() 
  File 
"/opt/ros/diamondback/stacks/ros_comm/tools/roslaunch/src/roslaunch/parent. py", 
line 163, in _start_server 
    self.server.start() 
  File 
"/opt/ros/diamondback/stacks/ros_comm/tools/roslaunch/src/roslaunch/server. py", 
line 371, in start 
    code, msg, val = xmlrpclib.ServerProxy(self.uri).get_pid() 
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call** 
    return self.**send(self.__name, args) 
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request 
    verbose=self.__verbose 
  File "/usr/lib/python2.6/xmlrpclib.py", line 1228, in request 
    h = self.make_connection(host) 
  File "/usr/lib/python2.6/xmlrpclib.py", line 1305, in make_connection 
    return httplib.HTTP(host) 
  File "/usr/lib/python2.6/httplib.py", line 1020, in __init** 
    self._setup(self._connection_class(host, port, strict)) 
  File "/usr/lib/python2.6/httplib.py", line 657, in __init__ 
    self._set_hostport(host, port) 
  File "/usr/lib/python2.6/httplib.py", line 682, in _set_hostport 
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:]) 
InvalidURL: nonnumeric port: '' 
}}}

trac data:
- Owner: **kwc**
- Reporter: **tfoote**
- Reported at: **Wed Oct 12 00:28:32 2011**
- URL: https://code.ros.org/trac/ros/ticket/3702

**Comment by ablasdel** [comment]
Pull request https://github.com/ros/ros_comm/pull/134 addresses this issue.

It validates that ROS_IP is either IPv4 or IPv6 and verifies that there are no ':' in the ROS_HOSTNAME which would imply a protocol, port or password had been incorrectly added.

**Comment by dirk-thomas** [comment]
This has been addressed quite some time ago.
