### ISSUE TITLE
rosbag: record multiple -x options

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#115]
This was also asked here, but never received any reply  http://answers.ros.org/question/35888/multi-exclude-in-rosbag-record

In my case, I was trying this: rosbag record -a -x "/cam_(._)/image_raw" -x "/cam_(._)/image_raw/compressed*" so as to record all my topics, except for the camera topics, for which I want only the theora part. But what happened is that it excluded only the compressed topic and I ended up with a 60GB bag which included the image_raw topic and the theora topic.

The workaround I used is to record 2 bags: one that excludes all camera topics, and another that includes only the theora topic, and then I can combine them when playing.

migration of trac ticket 4031:
  https://code.ros.org/trac/ros/ticket/4031

**Comment by hcostelha** [comment]
This ticket should be closed, as it is already possible. As I ansered in answers.ros.org, you can use the following for your example:

rosbag record -a -O data.bag -x "/usb_cam/(._)|/usb_cam_repub/theora/(._)"

**Comment by dirk-thomas** [comment]
Thanks for the heads up. Since it is achievable with the regex I will close the ticket.
