### ISSUE TITLE
Inconsistent exit codes of tools in error cases

### ISSUE THREAD

**Issue by luator** [ros/ros_comm#1171]
I just noticed that the console tools (`rosnode`, `rostopic`, ...) are inconsistent in their return code in case of errors.

The case I tested was running them without a running roscore (using kinetic):
* `rostopic list` --> exit code 1
* `rosservice list` --> exit code 2
* `rosnode list` --> exit code 0
* `rosparam list` --> exit code 1

Especially the exit code of `rosnode` is problematic if you expect to get an error code like with the other tools.

**Comment by dirk-thomas** [comment]
All tools should indeed return a non-zero exit code in case of errors. Some have specific codes to indicate the exact error though.

Please consider providing a pull request to fix the error code of `rosnode list`.

**Comment by luator** [comment]
Alright, I will try to find some time for it in the next days.
