### ISSUE TITLE
Bug in ros::NodeHandle::searchParam()?

### ISSUE THREAD

**Issue by CodeFinder2** [ros/ros_comm#1187]
Hi all,

I've already posted/asked this on answers.ros.org, see [here](https://answers.ros.org/question/272703/bug-in-rosnodehandlesearchparam/). Because it doesn't get much attention, I am posting it here as well since it may be a serious error in the implementation of `ros::NodeHandle::searchParam()`.

Any comments on this? Thanks!

**Comment by gavanderhoorn** [comment]
@CodeFinder2: I would suggest to mention here that you have a MWE, and possibly include it in your OP or make it available in a self-contained GH repository.

**Comment by dirk-thomas** [comment]
Please see the answer on answers.ros.org.
