### ISSUE TITLE
roswtf is unable to contact nodes reliably

### ISSUE THREAD

**Issue by ahendrix** [ros/ros_comm#120]
I was attempting to reproduce this bug: https://code.ros.org/trac/ros/ticket/3706 , but ran into more pressing problems.

When talking to python clients, roswtf is not able to reliably contact all of the nodes in a ROS graph.

For a simple case running the python talker and listener on my local machine, roswtf produces the following output:

```
$ roswtf
WARNING: Package name "langs-dev" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.
No package or stack in context
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules

Online checks summary:

Found 4 error(s).

ERROR Communication with [/talker_19871_1357696510874] raised an error: 
ERROR Communication with [/rosout] raised an error: 
ERROR Communication with [/listener_19820_1357696509064] raised an error: 
ERROR The following nodes should be connected but aren't:
 * /listener_19820_1357696509064->/rosout (/rosout)
 * /talker_19871_1357696510874->/listener_19820_1357696509064 (/chatter)
 * /talker_19871_1357696510874->/rosout (/rosout)
```

Version 1.9.39 of ros_comm from debs (current public version as of 1/8/2013)

**Comment by mirzashah** [comment]
I should be able to look at this tomorrow.

I can also look at the original issue you were trying to hunt down once the first part is resolved. We did a mass migration the other day of all issues on code.ros.org to GitHub...not sure why it didn't get migrated and got marked as "wontfix". I believe @dirk-thomas was the one closing out the issues for ros_comm so he may have had a reason. If you think it's a critical bug and Dirk agrees, I can correct the behavior to be consistent with that of the other tools.

**Comment by trainman419** [comment]
Yay!

I have a few ideas about what's causing the issues mentioned in the older ticket; I think they're actually bugs in rospy but haven't confirmed. Once roswtf works properly, I'll come up with some better bug reports.

**Comment by mirzashah** [comment]
@trainman419 -- I added in the fixes (two additional mutex locks) from our joint debugging session. We can work on the other issue as well tomorrow if you're up for it...if you could create another ticket for it that would be ideal.

**Comment by ahendrix** [comment]
Follow-up: I haven't been able to reproduce the bug mentioned in https://code.ros.org/trac/ros/ticket/3706 , or any of the other problems that I was seeing; it looks like it they're no longer valid.
