### ISSUE TITLE
things about mavros

### ISSUE THREAD

**Issue by aaumar** [ros/ros_comm#1204]
Hi I want to ask sometihing.
first, I got error when I used this command
`$ roslaunch px4 mavros_posix_sitl.launch`
and here is the error

> ... logging to /home/abdularis/.ros/log/27a0f1d6-ba3a-11e7-bf7a-94e9799ce369/roslaunch-abdularis-9598.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
Invalid <arg> tag: mavros_sitl_gazebo
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/abdularis/catkin_ws/src/mavlink
ROS path [2]=/home/abdularis/catkin_ws/src/mavros/libmavconn
ROS path [3]=/home/abdularis/catkin_ws/src/mavros/mavros_msgs
ROS path [4]=/home/abdularis/catkin_ws/src/mavros/mavros
ROS path [5]=/home/abdularis/catkin_ws/src/mavros/mavros_extras
ROS path [6]=/home/abdularis/catkin_ws/src/Firmware
ROS path [7]=/home/abdularis/catkin_ws/src/mavros/test_mavros
ROS path [8]=/opt/ros/kinetic/share
ROS path [9]=/home/abdularis/catkin_ws/src/Firmware
ROS path [10]=/home/abdularis/catkin_ws/src/Firmware/Tools/sitl_gazebo. 
Arg xml is <arg default="$(find mavros_sitl_gazebo)/worlds/empty.world" name="world"/>
The traceback for the exception was written to the log file

and the second question is I try another method to run gazebo and ros with mavros with this several command that I got from dev px4 site
`$ roslaunch mavros px4.launch fcu_url:="udp://:14540@127.0.0.1:14557"`
`$ no_sim=1 make posix_sitl_default gazebo`
and when I call iris world file with this
`$ roslaunch gazebo_ros empty_world.launch world_name:=$(pwd)/Tools/sitl_gazebo/worlds/iris.world
`
I got this error

> INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2017-10-26/09_53_24.ulg
INFO  [mavlink] partner IP: 127.0.0.1
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
INFO  [lib__ecl] EKF aligned, (pressure height, IMU buf: 15, OBS buf: 14)
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
INFO  [lib__ecl] EKF GPS checks passed (WGS-84 origin set)
INFO  [lib__ecl] EKF commencing GPS fusion
INFO  [commander] home: 47.3977419, 8.5455938, 488.02
INFO  [tone_alarm] home_set
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.
ERROR [mavlink] [timesync] Hard setting offset.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
