### ISSUE TITLE
cleanup_master_blacklist() in rosnode has incorrect documentation

### ISSUE THREAD

**Issue by ajeetdsouza** [ros/ros_comm#1252]
The comment says `Remove registrations from ROS Master that do not match blacklist.`, however the function is supposed to remove everything _on_ the blacklist.
https://github.com/ros/ros_comm/blob/lunar-devel/tools/rosnode/src/rosnode/__init__.py

PS: this is my first issue/PR, any inputs would be appreciated.

**Comment by mikepurvis** [comment]
Fixed via #1253.
