### ISSUE TITLE
Possible documentation error in rosnode

### ISSUE THREAD

**Issue by ajeetdsouza** [ros/ros_comm#1254]
rosnode documentation seems to have outdated docstrings, making references to XMLRPC handles in places where we now use instances of `rosgraph.Master` (a convenience API for interaction with the ROS Master).

https://github.com/ros/ros_comm/blob/lunar-devel/tools/rosnode/src/rosnode/__init__.py

**Comment by dirk-thomas** [comment]
Addressed by #1278.
