### ISSUE TITLE
Add message filters support for non-const messages

### ISSUE THREAD

**Issue by chadrockey** [ros/ros_comm#126]
Reopening from:
https://code.ros.org/trac/ros/ticket/3907

The current message filters API ( http://www.ros.org/doc/api/message_filters/html/classmessage__filters_1_1TimeSynchronizer.html) only supports const MessageConstPtr? callbacks.

One useful case I have would be for a const MessagePtr? callback instead. My specific need is I want to synchronize multiple messages, edit one of those messages with the synchronized information, and then republish that edited message on a new topic. Since these messages are large, I do not want to make a new copy to do so.

Is there a reason why these callbacks do not currently allow you to change the messages? And is there an alternative method to achieve what I need without changing the callback signatures?

Thanks!

**Comment by chadrockey** [comment]
Changed 4 hours ago by dthomas ¶

status changed from new to closed
resolution set to wontfix
Your custom message filter code might not be the only one operating on the message instance at a time. Therefore the interface only provides a const pointer. Changing the message in-place could affect other code and is therefore not allow. So there is no way the interface can be relaxed in the way you want it to.

I don't see an easy way to solve your use case without the data object supporting shallow copying.

**Comment by chadrockey** [comment]
@dirk-thomas 

There is of course risk present editing messages in memory; however, Nodelets allow you to use non-const callbacks.  Since message filters does not allow you to use non-const callbacks, you have to re-implement the functionality in your own library.

The specific application was:
camera driver publishes /camera/image with an approximate USB timestamp.
Precision hardware sometime later sends a message containing an exact timestamp /camera/stamp

Nodelet takes /camera/image and /camera/stamp, merges stamp into image->header.stamp, republishes on a different topic as /camera/image_stamped.
While it is possible for other nodelets to modify that data, the separation on topic was sufficient for this application.

Without message_filters supporting non-const implementation, the developer is left with poor options:
1) Write queue handling code in driver to only publish once the timestamp is received - bad due to functionality duplication and worse because ROS cannot monitor or bag the unstamped topic in case of driver freeze/crash.
2) Rewrite message filters functionality using non-const Nodelets - even worse, but what this application required to resolve this issue.
3) Complicate every piece of code and logging downstream by requiring message filters and duplicating timestamp matching logic in every subscriber (like image_transport, but 3 ways).  This also blocks use of image_transport and other useful tools.
4) Full memcpy on Images by not using nodelets or copying message contents.  This will grind applications to a halt with unnecessary copying.

Nodelets already let you violate the guidelines for shared memory and the alternatives are not great on developers running on limited capacity CPUs.  If you absolutely want to enforce that nodelet passed messages are not modified, Nodelet should be modified to be const callbacks only for consistency.

**Comment by dirk-thomas** [comment]
Most of the NodeHandle API enforces const of the passed message:
http://ros.org/doc/groovy/api/roscpp/html/classros_1_1NodeHandle.html#a317fe4c05919e0bf3fb5162ccb2f7c28

Some (mostly older) signatures technically allow you to declare callbacks receiving non-const messages:
http://ros.org/doc/groovy/api/roscpp/html/classros_1_1NodeHandle.html#a34143456de5df2022f3ebcd6e95b92ec
But as the doc comment of these methods state: "This message should not be changed in place, as it is shared with any other subscriptions to this topic."

So the interface for message filters should also stay const.

The only (really ugly) workaround in this specific case - if you can make sure that altering the timestamp does not break concurrent access to the message (or don't have concurrent access in your case) - is to use a const_case to get rid of the const and alter the message despite the different API agreement. [This last paragraph will self-destruct in one minute...]
