### ISSUE TITLE
topic_tools transform publisher subscriber order

### ISSUE THREAD

**Issue by borgcons** [ros/ros_comm#1273]
I believe that the script should call publisher before subscriber. I have has a situation in my launch file where the subscriber callback is call before the publisher is created and when the callback calls publish I get an error.

        self.pub = rospy.Publisher(args.output_topic, self.output_class, queue_size=1)
        self.sub = rospy.Subscriber(input_topic, input_class, self.callback)

**Comment by dirk-thomas** [comment]
Since the `callback` might use `self.pub` that sounds like a good idea. Please create a pull request with the proposed patch.
