### ISSUE TITLE
topic_tools transform latch output

### ISSUE THREAD

**Issue by borgcons** [ros/ros_comm#1274]
I also think that there should be a  latch on the publisher

        parser.add_argument(
            '--latch_output', action='store_true',
            help='Latch output messages.'
        )
...
        self.pub = rospy.Publisher(args.output_topic, self.output_class, queue_size=1, latch=args.latch_output)

**Comment by dirk-thomas** [comment]
That sounds like a good feature idea. Please consider to provide a pull request for this.

**Comment by cwecht** [comment]
Has been fixed by #1341
