### ISSUE TITLE
Topic_tools  transform wait_for_start

### ISSUE THREAD

**Issue by borgcons** [ros/ros_comm#1275]
I believe there is an error in the script

        parser.add_argument(
            '--wait-for-start', action='store_true',
            help='Wait for input messages.'
        )
...
       input_class, input_topic, self.input_fn = rostopic.get_topic_class(
            args.input, blocking=args.wait_for_start)

the variable names are not the same.

**Comment by dirk-thomas** [comment]
Can you please elaborate which variable names are not the same. I don't see which exact part you are referring to.

**Comment by borgcons** [comment]
My error. 

It took a little while to find this in the documentation.

Any internal - characters will be converted to _ characters to make sure the string is a valid attribute name.
