### ISSUE TITLE
rosbag record: Option for TCP_NODELAY

### ISSUE THREAD

**Issue by alspitz** [ros/ros_comm#1279]
When recording large messages such as Odometry, the messages arrive at the bag in clumps. It would be nice if rosbag record had a --tcpnodelay or --udp option to prevent this from happening.

**Comment by dirk-thomas** [comment]
The `TCP_NODELAY` option is a publisher setting. But in the case of recording `rosbag` is subscribing to the topics. Therefore it can't enforce / request that option.

Therefore I don't think this feature request for `rosbag` is feasible. Instead whichever node is publishing the odometer messages would need to provide that option.

**Comment by alspitz** [comment]
It's definitely an option that can be added to a C++ subscription: https://docs.ros.org/api/roscpp/html/classros_1_1TransportHints.html. AFAIK, there is no way to add transport hints to a C++ publisher.

**Comment by alspitz** [comment]
Also, since Python subscribers can also specify TCP_NODELAY (but not UDP), it would be nice if `rostopic hz` had a `--nodelay` option as well.

**Comment by dirk-thomas** [comment]
Sorry, you are right. The option can also be requested from the subscriber side.

Please consider to provide a pull request to add such an option to the `rosbag record` command.

**Comment by alspitz** [comment]
I've created a pull request here: https://github.com/ros/ros_comm/pull/1295

**Comment by alspitz** [comment]
I also created a pull request for adding TCP_NODELAY to rostopic hz and delay here: https://github.com/ros/ros_comm/pull/1296

**Comment by dirk-thomas** [comment]
I close this issue in favor of the pending PR #1295 (to only have one open item). Thank you for working on this.
