### ISSUE TITLE
Build warning with -pedantic

### ISSUE THREAD

**Issue by oxoocoffee** [ros/ros_comm#1298]
I am on latest kinetic (Ubuntu 16.04.3). When building with  -pedantic

/opt/ros/kinetic/include/ros/console.h:158:82: warning: extra ‘;’ [-Wpedantic]
     const char* function, const char* fmt, ...) ROSCONSOLE_PRINTF_ATTRIBUTE(7, 8);

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request (targeting the default branch, currently `lunar-devel`) to address this.

**Comment by dirk-thomas** [comment]
This issue was moved to ros/rosconsole#9
