### ISSUE TITLE
Use std::allocator_traits<ContainerAllocator>::template rebind instead of ContainerAllocator::template rebind

### ISSUE THREAD

**Issue by eric-wieser** [ros/ros_comm#1304]
`allocator_traits` is not available till C++11, so this might be in the backlog for a while. Switching conditionally on the compiler version might be reasonable.

Using `::rebind` directly on the type is deprecated as of C++17.

Thankfully, no changes are needed to `ContainerAllocator` to make this work.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this.

**Comment by eric-wieser** [comment]
Is there precedent elsewhere in ROS for checking for C++ features before using them?

**Comment by dirk-thomas** [comment]
I don't think that is necessary. Assuming that the change is within a `.cpp` file ROS Kinetic and newer already require a C++11 compiler. So it should be safe to use.

**Comment by eric-wieser** [comment]
I really need to start pushing to move off indigo!
