### ISSUE TITLE
ros environment hook sets ROS_ROOT incorrectly

### ISSUE THREAD

**Issue by wjwwood** [ros/ros_comm#131]
When building ros_comm packages from tarballs (downloaded individually from github) into a devel space, the resulting ros environment hooks will incorrectly set the ROS_ROOT.  It is incorrect because it assumes that the roslib package is located relatively to other packages in the ros_comm repository.  This relative layout is changed when the packages are released and segmented by bloom.

**Comment by dirk-thomas** [comment]
This should be resolved since some time by ros/ros@e826d1039eda1f1b7e89f0f45807c1c41af07b1f
