### ISSUE TITLE
Mismatch between ROS wiki and code for ROS_[INFO/...]_..._THROTTLE C++ macros

### ISSUE THREAD

**Issue by dmcconachie** [ros/ros_comm#1312]
The wiki entry (http://wiki.ros.org/roscpp/Overview/Logging) for the various THROTTLE rosconsole C++ macros does not match the code itself. The wiki states (correctly) that you provide a period, however the macros themselves use "rate".
```C++
...
#define ROS_INFO_THROTTLE(rate, ...) ROS_LOG_THROTTLE(rate, ::ros::console::levels::Info, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
#define ROS_INFO_STREAM_THROTTLE(rate, args) ROS_LOG_STREAM_THROTTLE(rate, ::ros::console::levels::Info, ROSCONSOLE_DEFAULT_NAME, args)
#define ROS_INFO_THROTTLE_NAMED(rate, name, ...) ROS_LOG_THROTTLE(rate, ::ros::console::levels::Info, std::string(ROSCONSOLE_NAME_PREFIX) + "." + name, __VA_ARGS__)
...
```
This has the potential for confusion if one uses the macro definition as a way of looking up what the macros do instead of going to the wiki.

This is obviously a low priority issue but if someone happens to be working in the area anyway, this could be cleaned up at the same time.

**Comment by dirk-thomas** [comment]
`period` sounds indeed more accurate than `rate`. Please see #1318.
