### ISSUE TITLE
error: ‘ros_steadytime’ is not a member of ‘ros’

### ISSUE THREAD

**Issue by ghost** [ros/ros_comm#1349]
Please suggest a way to fix this error: ‘ros_steadytime’ is not a member of ‘ros’. I am building this package on Ubuntu 16, ROS Kinetic, Python 3.5.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now.

---

Just guessing what exactly you are trying to do: you might be building a current checkout of this repo but not have an up-to-date version of the `roscpp_core` repo / `rostime` package which would lead to that kind of mismatch.
