### ISSUE TITLE
roscpp should get rid of pthread dependencies

### ISSUE THREAD

**Issue by vrabaud** [ros/ros_comm#135]
io.h and other headers include pthread. Either pthread should be stated as a dependency, either boost threads should be used (that would be more cross-platform and easier to port to C++11 threads later).

We never had problems before because pthread is automatically included by Boost on Ubuntu. On Fedora, that is not the case and that causes some packages depending on roscpp to fail at compile time:
https://github.com/ros-perception/image_pipeline/issues/16

**Comment by dirk-thomas** [comment]
There is no replacement in boost for `pthread_sigmask`. Instead state dependency cleanly to downstream packages.
