### ISSUE TITLE
message_filters::Synchronizer build error

### ISSUE THREAD

**Issue by ahuer2435** [ros/ros_comm#1355]
I build 7.2 ExactTime Policy sample in http://wiki.ros.org/message_filters#Time_Synchronizer as following：

pose_heading.cpp file 
#include <message_filters/subscriber.h>
#include <message_filters/synchronizer.h>
#include <message_filters/sync_policies/exact_time.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/CameraInfo.h>

using namespace sensor_msgs;
using namespace message_filters;

void callback(const ImageConstPtr& image, const CameraInfoConstPtr& cam_info)
{
  // Solve all of perception here...
}

int main(int argc, char** argv)
{
  ros::init(argc, argv, "vision_node");

  ros::NodeHandle nh;
  message_filters::Subscriber<Image> image_sub(nh, "image", 1);
  message_filters::Subscriber<CameraInfo> info_sub(nh, "camera_info", 1);

  typedef sync_policies::ExactTime<Image, CameraInfo> MySyncPolicy;
  // ExactTime takes a queue size as its constructor argument, hence MySyncPolicy(10)
  Synchronizer<MySyncPolicy> sync(MySyncPolicy(10), image_sub, info_sub);
  sync.registerCallback(boost::bind(&callback, _1, _2));

  ros::spin();

  return 0;
}

build error as following:
CMakeFiles/pose_heading_node.dir/src/pose_heading.cpp.o: In function `message_filters::Synchronizer<message_filters::sync_policies::ExactTime<sensor_msgs::Image_<std::allocator<void> >, sensor_msgs::CameraInfo_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType> >::disconnectAll()':
pose_heading.cpp:(.text._ZN15message_filters12SynchronizerINS_13sync_policies9ExactTimeIN11sensor_msgs6Image_ISaIvEEENS3_11CameraInfo_IS5_EENS_8NullTypeES9_S9_S9_S9_S9_S9_EEE13disconnectAllEv[_ZN15message_filters12SynchronizerINS_13sync_policies9ExactTimeIN11sensor_msgs6Image_ISaIvEEENS3_11CameraInfo_IS5_EENS_8NullTypeES9_S9_S9_S9_S9_S9_EEE13disconnectAllEv]+0x3f): undefined reference to `message_filters::Connection::disconnect()'
CMakeFiles/pose_heading_node.dir/src/pose_heading.cpp.o: In function `message_filters::Connection message_filters::SimpleFilter<sensor_msgs::Image_<std::allocator<void> > >::registerCallback<ros::MessageEvent<sensor_msgs::Image_<std::allocator<void> > const> const&>(boost::function<void (ros::MessageEvent<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&)':
pose_heading.cpp:(.text._ZN15message_filters12SimpleFilterIN11sensor_msgs6Image_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE[_ZN15message_filters12SimpleFilterIN11sensor_msgs6Image_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE]+0xa4): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
CMakeFiles/pose_heading_node.dir/src/pose_heading.cpp.o: In function `message_filters::Connection message_filters::SimpleFilter<sensor_msgs::CameraInfo_<std::allocator<void> > >::registerCallback<ros::MessageEvent<sensor_msgs::CameraInfo_<std::allocator<void> > const> const&>(boost::function<void (ros::MessageEvent<sensor_msgs::CameraInfo_<std::allocator<void> > const> const&)> const&)':
pose_heading.cpp:(.text._ZN15message_filters12SimpleFilterIN11sensor_msgs11CameraInfo_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE[_ZN15message_filters12SimpleFilterIN11sensor_msgs11CameraInfo_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE]+0xa4): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
collect2: error: ld returned 1 exit status
[ 98%] Built target twist_tester
[ 98%] Built target dbw_mkz_can_dbw_node
make[2]: *** [/home/yanqiao/workspace/Autopilot_demo/catkin_ws/devel/lib/msg_convert/pose_heading_node] Error 1
make[1]: *** [msg_convert/CMakeFiles/pose_heading_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target twist_controller
make: *** [all] Error 2

build environment：
os：ubuntu14.04
ros：indigo

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
