### ISSUE TITLE
Rosservice calls within rosservice tool module fail with initialization of the rosservice node for getting time

### ISSUE THREAD

**Issue by dchatarpaul** [ros/ros_comm#1363]
Could not call services using the rosservice module as part of one of the ros comm tools because rospy.init_node() has already been called. This seems to be done purely so that the rostime() function call doesn't fail with a `ROSInitException: time is not initialized. Have you called init_node()?` error. 

Here is the line of code with a commenting eluding to the problem:
```
    # can't use time w/o being a node. We could optimize this by
    # search for the now/auto keywords first
    import std_msgs.msg
    rospy.init_node('rosservice', anonymous=True)
```

**Comment by mikepurvis** [comment]
If you're within a script, call services using the rospy API, not by importing `rosservice`:

http://wiki.ros.org/rospy/Overview/Services

Support questions of this kind are best asked first on ROS Answers, see: http://wiki.ros.org/Support#When_something_fails
