### ISSUE TITLE
topic_tools: demux crashes when using __none

### ISSUE THREAD

**Issue by lfdebrux** [ros/ros_comm#1366]
The demux node in topic_tools crashes when it receives a message and the selected topic is the magic "__none" topic

Steps to reproduce

    rosrun topic_tools demux in out_1 out_2
    rosservice call /demux/select "__none"
    rostopic pub -1 /in std_msgs/Empty

demux then crashes with a segmentation fault

This was tested in kinetic on Ubuntu 16.04.

I believe this is due to a null pointer dereference in https://github.com/ros/ros_comm/blob/283818529002c6d37e8b9ec554a17b40c6075c20/tools/topic_tools/src/demux.cpp#L156

**Comment by peci1** [comment]
Argh... bumped into this now on melodic... When will there finally be a new release of ros_comm???

**Comment by peci1** [comment]
For others who suffer by this bug: as a workaround, you can always add a "blackhole" topic which nobody subscribes, and redirect the output to it instead of `__none`.

**Comment by dirk-thomas** [comment]
> Argh... bumped into this now on melodic... When will there finally be a new release of ros_comm???

This issue was closed when the referenced commit was merged: 2b3f43d on Apr 24, 2018. And that commit has been released for a very long time into Melodic (around May 2018). So if you still experience issues you might want to double check if there is an open ticket describing it or create a new issue.

**Comment by peci1** [comment]
You're right, in the end it looks like a different issue, but with very similar symptoms. See #1889 .
