### ISSUE TITLE
Allow rostest to attach to existing master  (ros ticket #2351)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#137]
Sometimes it's much more convenient to attach rostest to an existing master on the default port (11311).  I can leave things like rxplot and rviz up and connected as I switch between running rostests and running other applications.  An option to rostest for attaching to my existing master would be helpful.

trac data:
- Owner: **kwc**
- Reporter: **sglaser**
- Reported at: **Fri Jan 15 16:25:02 2010**
- URL: https://code.ros.org/trac/ros/ticket/2351

**Comment by tfoote** [comment]
[kwc] This is a fairly tough thing to allow, at least as described. Part of rostest's architecture is that for full launches it brings up and tears down a master between each run in order to keep tests independent and provide them with the same initial state (e.g. parameters).

There are other ways of looking at the problem that might provide more straightforward technical solutions and not confuse the contract of what rostest is doing. One is that a rostest file can be roslaunch'd, so I could just add an option to rostest to launch a named test within a test file, which would run against any existing launch/master. 

I'm assuming what you're describing implies that you want to focus on a specific test, right? Having rxplot bounce around as a bunch of different tests run seems less useful.

**Comment by tfoote** [comment]
[sglaser] The use-case is that some test(s) is failing and I want to run the test locally, attaching visualization nodes, possibly some scaffolding nodes, and maybe changing parameters around.
1. The master should stay up (so that the scaffolding and viz nodes stay connected).
2. The master should be on the default port (all my environments assume 11311.  I think it's convenient to have the test connect to this one too).
3. Different tests should connect to the same master (so I can quickly switch between tests as I change functionality).

Understand that I don't expect rostest to have this behavior by default, I just want an option to enable this behavior.

Looking closely, I'm pretty sure you've described what I want:

> One is that a rostest file can be roslaunch'd, so I could just add an option to rostest to launch a named test within a test file, which would run against any existing launch/master.

**Comment by trainman419** [comment]
+1. This would be useful to me as well.

**Comment by dirk-thomas** [comment]
Closed by #637.
