### ISSUE TITLE
Failed xmlrpcpp

### ISSUE THREAD

**Issue by Vibrane** [ros/ros_comm#1398]
I am using the install script to install ROS Lunar and the installation got stuck in xmlrpcpp. Since, this showed up to be part of the ros_comm package, I assume this is the right place to post this issue. 

I do not know what to do to fix this. 

[build.make.000.log](https://github.com/ros/ros_comm/files/2003165/build.make.000.log)

**Comment by mikepurvis** [comment]
Please try the changes pending in #1392, and report there if it works for you.
