### ISSUE TITLE
Unable to change a python nodes logger level while it is running

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#14]
This was brought up last year on ros answers and it didn't make it onto the list of todos.
http://answers.ros.org/question/9802/change-python-node-log-level-while-running/

**Comment by ablasdel** [comment]
To be specific this is apparently roscpp functionality that never made it in to rospy.

In the answer ken also mentions that a general API cleanup might also be in order.

**Comment by jonbinney** [comment]
I think austin implemented this? Check the pull request he has waiting: https://github.com/ros/ros_comm/pull/6

**Comment by ahendrix** [comment]
Correct; I had to reach a bit into the logging module to get the desired behavior, but it's implemented and works for me.

**Comment by 130s** [comment]
See https://github.com/ros-visualization/rqt/issues/5 that I just closed.
