### ISSUE TITLE
ROS_MASTER_URI is not parsing  (ros ticket #3677)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#140]
only some applications complain about invalid urls even if they're truely malformed. 

This needs to be researched and likely tickets filed for each client library.

trac data:
- Owner: **tfoote**
- Reporter: **tfoote**
- Reported at: **Mon Sep 19 16:59:26 2011**
- URL: https://code.ros.org/trac/ros/ticket/3677

**Comment by tfoote** [comment]
[gerkey] I second this.  More than once I've accidentally set `ROS_MASTER_URI` to the value I intended for `ROS_PACKAGE_PATH`, and it's not obvious what the problem is.

**Comment by tfoote** [comment]
[kwc] while we're digging around in there, it would be nice to set the standard where:

No ROS_MASTER_URI = http://localhost:11311

ROS_MASTER_URI = host -> http://host:11311

ROS_MASTER_URI = http://host -> http://host:11311

**Comment by dirk-thomas** [comment]
Similar problems have been addressed in the past. If further cases are still an issue please comment and the ticket can be reopened.
