### ISSUE TITLE
[rosconsole] C++ stream operators for containers?

### ISSUE THREAD

**Issue by bmagyar** [ros/ros_comm#1400]
I've been using a header file that I carry with me from project to project for a while now. 
The main contribution of it is this template that allows to print vectors without having to write the same boilerplate over and over again.

```
template <typename T>
std::ostream& operator<< (std::ostream& stream, const std::vector<T>& list)
{
  stream << "[";
  for(const T& elem : list)
    stream << elem << ", ";
  if(not list.empty())
    stream.seekp(-2, std::ios_base::end); // remove last ", "
  stream << "]";
  return stream;
}
```

Is something like this welcome in `rosconsole` or you are trying to offer the same functionality with `printf`-style logging and other languages?

**Comment by dirk-thomas** [comment]
This issue was moved to ros/rosconsole#10
