### ISSUE TITLE
ros_comm 1.4.1 breaks socketcan_bridge tests

### ISSUE THREAD

**Issue by mathias-luedtke** [ros/ros_comm#1408]
I just noticed that one test started to fail for melodic shadow-fixed (1.4.1), but works for main (1.3.6).
https://travis-ci.org/ipa-mdl/ros_canopen/builds/381469509

The [failing test](https://github.com/ros-industrial/ros_canopen/blob/melodic-devel/socketcan_bridge/test/to_socketcan_test.cpp#L157), runs `ros::spinOnce()` to fetch one message.

Digging through the commits https://github.com/ros/ros_comm/pull/1365 raised my attention.
I will run further tests, but this seems to change the behaviour at least for this test.

**Comment by mathias-luedtke** [comment]
I was not able to fix this test with an additional wait. It might be that the message got lost.
So it looks more like https://github.com/ros/ros_comm/pull/1393 is the cause.

The only external depedencies are
```
executing command [apt-get install -y ros-melodic-roscpp]
executing command [apt-get install -y ros-melodic-class-loader]
executing command [apt-get install -y ros-melodic-message-runtime]
executing command [apt-get install -y ros-melodic-std-msgs]
executing command [apt-get install -y ros-melodic-roslint]
executing command [apt-get install -y ros-melodic-rostest]
executing command [apt-get install -y ros-melodic-rosunit]
executing command [apt-get install -y ros-melodic-message-generation]
executing command [apt-get install -y libboost-all-dev]
```

**Comment by dirk-thomas** [comment]
@guillaumeautran Can you please take a closer look at this.

**Comment by mathias-luedtke** [comment]
I was not able to dermine the cause of this problem, perhaps it's the combination of different commits.
However, I was able to come up with a test case.
For some reason the `/rosout` handling seems to be involved.

**Comment by mikepurvis** [comment]
Assuming you're on Linux, I'd be doubtful that #1393 could directly be the issue, since that was a fix for non-epoll systems such as macOS.

Does the test still fail if you build ros_comm from source but override `HAVE_EPOLL=0` in this spot?

https://github.com/ros/ros_comm/pull/1217/files#diff-af96143090deaa643970030f962c964dR70

That would kick it back to the legacy poll implementation for handling IO.

**Comment by guillaumeautran** [comment]
I am taking a look right now but the specific tests passes for me at this time. Still doing some more digging.

**Comment by mathias-luedtke** [comment]
> Assuming you're on Linux

The test case fails on travis, ROS buildfarm  (#1409) and in a local docker environment (`run_ci`).

>  Does the test still fail if you build ros_comm from source but override HAVE_EPOLL=0 in this spot?

I will push a commit to the test case PR

I did not have a deeper look at the other PRs.

**Comment by guillaumeautran** [comment]
So, looks like a setup/teardown problem. I was able to reproduce the issue (only happens on the ros_comm melodic branch) but a soon as I comment out the first test case, the second test (which was failing originally) starts to pass. 
Something must not have been cleaned up properly between the tests.

**Comment by mathias-luedtke** [comment]
The only other difference of package versions is `rosconsole`: 1.13.6 -> 1.13.7

**Comment by mathias-luedtke** [comment]
> Something must not have been cleaned up properly between the tests.

If I add a `ros::NodeHandle` to `main()`, both tests pass.

**Comment by mathias-luedtke** [comment]
Finally, I ran `git bisect`. The test case  started to fail with d21a33cdcee55ac09a58f702baf415539eebbacf (#1241)

**Comment by dirk-thomas** [comment]
> Finally, I ran `git bisect`. The test case  started to fail with d21a33cdcee55ac09a58f702baf415539eebbacf (#1241)

@trobertson-cpr FYI

**Comment by mathias-luedtke** [comment]
I have resolved this by adding the `NodeHandle`.
Nevertheless, #1241 changed the behavior and affects at least the logging performance in rospy.
