### ISSUE TITLE
rostopic list --verbose fails in latest distro melodic (v1.14.1)

### ISSUE THREAD

**Issue by per-atth** [ros/ros_comm#1412]
There is an error in line 1140 in /opt/ros/melodic/lib/python2.7/dist-packages/rostopic/__init__.py causing python error message when running $rostopic list -v
Changing llist to tlist in line 1140 fix this:
print(indent+" * %s [%s] %s subscribers"%(t, ttype, len(tlist)))

**Comment by per-atth** [comment]
I see that the underline characters in the .py filename is removed (by GitHub Issues) replacing them by bold, causing the filename above to be incorrect. Add two underlines before and after init.

**Comment by dirk-thomas** [comment]
Thanks for reporting. This has already been fixed in #1407.
