### ISSUE TITLE
Provide empty string as roslaunch argument substitution

### ISSUE THREAD

**Issue by artifactz** [ros/ros_comm#1447]
Cross-post from [here](https://answers.ros.org/question/296116/provide-empty-string-as-roslaunch-argument-substitution/), since it seems to be a bug.

Empty string substitutions to a launch file argument are ignored, i.e. the default value specified in the launch file is used instead.

**Example**

A `default.launch` file has the following argument declaration:

    <arg name="arg1" default="hello world" />

This call won't set `arg1` to `""` as expected:

    roslaunch pkg default.launch arg1:=""

(Ubuntu 16.04 / ROS Kinetic)

**Comment by cwecht** [comment]
This seems to be an issue of the Bash. Try this snippet here:

     python -c "import sys; print str(sys.argv)" arg:=""

This will result in

     ['-c', 'arg:=']

The Bash uses quotation marks to group space-separated strings in a single entry of argv. But you can use single quotes around the double quotes. This way

     python -c "import sys; print str(sys.argv)" arg:='""'

will result in

    ['-c', 'arg:=""']

Another solution could be to allow empty arguments, but I don't know if this a good idea.

**Comment by artifactz** [comment]
Wow... :man_facepalming: That totally makes sense, thank you.
