### ISSUE TITLE
roscpp refuses to receive messages with a size over 1gb

### ISSUE THREAD

**Issue by matt-attack** [ros/ros_comm#1453]
There appears to be an arbitrary message size limit enforced inside of roscpp that drops packets over 1gb. Rospy does not appear to have this limit as I am able to use the console tools to echo these messages.

I am encountering this issue when sending large pointclouds and trying to visualize them in Rviz.

The limit is implemented here.
https://github.com/ros/ros_comm/blob/melodic-devel/clients/roscpp/src/libros/transport_publisher_link.cpp#L172

Is it possible to make this limit larger or tie it to an actual tcpros limit instead of a completely arbitrary 1gb?

**Comment by dirk-thomas** [comment]
Closing duplicate.
