### ISSUE TITLE
C++14 specification in CMakeLists.txt

### ISSUE THREAD

**Issue by kunaltyagi** [ros/ros_comm#1454]
My default compiler doesn't have C++14 as the default standard. Would adding '-std=c++14' in the CMakeLists.txt make sense?

I'm specifically referring to `rosbag` and `rosbag_storage` packages since these 2 packages `#include` headers from `class_loader` which use the new standard features.

[For more tangentially related details](https://github.com/ros/class_loader/issues/100)

**Comment by mikaelarguedas** [comment]
As discussed in https://github.com/ros/class_loader/issues/100 this should be handled at the distribution level and not on a per package basis.

If you are using a distribution not officially supported by melodic, you should pass the C++ standard to all the packages you compile in your workspace.
This can be done by passing `-DCMAKE_CXX_STANDARD=14` during the build tool invocation (or in the build tool config file if it supports it).

A discussion covering the different ways this could be done at the distribution level: https://github.com/ros/catkin/issues/936
