### ISSUE TITLE
Time sequencer does not compile

### ISSUE THREAD

**Issue by piraka9011** [ros/ros_comm#1456]
I've been trying to get the time sequencer to work however, it doesn't compile despite following the documentation.
I have opened a ROS Answers question regarding it [here](https://answers.ros.org/question/283432/message-filters-time-sequencer-not-compiling-roscpp/).

Any input as to why this does not compile?
Thanks!

**Comment by dirk-thomas** [comment]
Please don't cross post your question. That is against the etiquette (see http://wiki.ros.org/Support).
