### ISSUE TITLE
SROS Docker and Ubuntu install fails due to missing dependencies etc.

### ISSUE THREAD

**Issue by TomL92** [ros/ros_comm#1461]
Hello,

While trying to follow the official SROS Tutorials ([http://wiki.ros.org/SROS/Tutorials](http://wiki.ros.org/SROS/Tutorials)), I had some issues when trying to start the `sroskeyserver`. The same errors also occur when running the prebuilt Docker container, so i suppose, that the problem is due to some inconsistencies in the SROS repository or its dependencies.

At first i've pulled the docker and tried to run the command from the install page:
<details> 
  <summary>command (click to expand)</summary>

  ```bash
  docker run --rm -it \
    osrf/sros \
    bash -c "source /ros_entrypoint.sh && \
        sroskeyserver & \
        sleep 3 && \
        sroslaunch rospy_tutorials talker_listener.launch"
  ```
</details>

Somehow this runs into the following problem:

<details>
  <summary> Error (click to expand) </summary>

  ```
  Traceback (most recent call last):
  File "/root/sros_catkin_ws/install/bin/sroskeyserver", line 2, in <module>
    import sros
  File "/root/sros_catkin_ws/install/lib/python2.7/dist-packages/sros/__init__.py", line 7, in <module>
    import rosgraph.sros_consts as sros_consts
  ImportError: No module named rosgraph.sros_consts
  Traceback (most recent call last):
  File "/root/sros_catkin_ws/install/bin/sroslaunch", line 2, in <module>
    import sros
  File "/root/sros_catkin_ws/install/lib/python2.7/dist-packages/sros/__init__.py", line 7, in <module>
    import rosgraph.sros_consts as sros_consts
  ImportError: No module named rosgraph.sros_consts
```

</details>

Therefore I checked the ros_comm package, which is not available in the Docker container as it is ignored by using an `AMENT_IGNORE` file.
<details>
  <summary>see here (click to expand)</summary>

  ```bash
  ./src/ros_comm/ros_comm/AMENT_IGNORE
  ./src/ros_comm/clients/AMENT_IGNORE
  ./src/ros_comm/tools/rostopic/AMENT_IGNORE
  ./src/ros_comm/tools/rosmsg/AMENT_IGNORE
  ./src/ros_comm/tools/roslaunch/AMENT_IGNORE
  ./src/ros_comm/tools/rosbag/AMENT_IGNORE
  ./src/ros_comm/tools/rosparam/AMENT_IGNORE
  ./src/ros_comm/tools/topic_tools/AMENT_IGNORE
  ./src/ros_comm/tools/rosnode/AMENT_IGNORE
  ./src/ros_comm/tools/rosbag_storage/AMENT_IGNORE
  ./src/ros_comm/tools/rosservice/AMENT_IGNORE
  ./src/ros_comm/tools/rosout/AMENT_IGNORE
  ./src/ros_comm/tools/rosconsole/AMENT_IGNORE
  ./src/ros_comm/tools/rosgraph/AMENT_IGNORE
  ./src/ros_comm/tools/rosmaster/AMENT_IGNORE
  ./src/ros_comm/test/AMENT_IGNORE
  ./src/ros_comm/utilities/AMENT_IGNORE
  ```
</details>

So I tried to remove the `AMENT_IGNORE` files, which (after building again) resulted at least in a usable ros_comm installation (i.e. import in python was working), however also resulted in "abandoned packages".

Furthermore i tried again to start the ```sroskeyserver```, but there were some packages missing (cryptography, pyopenssl, apparmor).

After finally installing all of the missing dependencies, i ran into the following error trying to start the keyserver again:

<details>
  <summary> keyserver referenced before assignment (click to expand)</summary>

```bash
root@5c14d417a2ec:~/sros_catkin_ws# sroskeyserver 
Starting an XML-RPC server to bootstrap SSL key distribution...
Traceback (most recent call last):
  File "/root/sros_catkin_ws/install/bin/sroskeyserver", line 3, in <module>
    sros.sroskeyserver_main()
  File "/root/sros_catkin_ws/install/lib/python2.7/dist-packages/sros/__init__.py", line 179, in sroskeyserver_main
    keyserver.start_keyserver(keyserver_config, keystore_path, keyserver_mode, port)
  File "/root/sros_catkin_ws/install/lib/python2.7/dist-packages/rosgraph/keyserver.py", line 143, in start_keyserver
    keyserver.stop()
UnboundLocalError: local variable 'keyserver' referenced before assignment
root@5c14d417a2ec:~/sros_catkin_ws# sroskeyserver 
Starting an XML-RPC server to bootstrap SSL key distribution...
Traceback (most recent call last):
  File "/root/sros_catkin_ws/install/bin/sroskeyserver", line 3, in <module>
    sros.sroskeyserver_main()
  File "/root/sros_catkin_ws/install/lib/python2.7/dist-packages/sros/__init__.py", line 179, in sroskeyserver_main
    keyserver.start_keyserver(keyserver_config, keystore_path, keyserver_mode, port)
  File "/root/sros_catkin_ws/install/lib/python2.7/dist-packages/rosgraph/keyserver.py", line 143, in start_keyserver
    keyserver.stop()
UnboundLocalError: local variable 'keyserver' referenced before assignment
```
</details>

So this looks like an more in-depth error for me and since i used the official Docker image, I was wondering if there is already a known solution for this. Is SROS still maintained or should I check out SROS2? Even if SROS is not maintained anymore, I am still interested in a solution for this problem, as I am currently evaluating different security concepts for ROS.
It would be nice, if someone could help me.

Thank you

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
