### ISSUE TITLE
roscpp: add ability to display name of logger to rxconsole display  (ros ticket #2485)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#147]
I've written the NODELET_DEBUG etc to use the named loggers however, in rxconsole there is no way to tell which logger it came from.

trac data:
- Owner: **kwc**
- Reporter: **tfoote**
- Reported at: **Wed Mar  3 11:02:44 2010**
- URL: https://code.ros.org/trac/ros/ticket/2485

**Comment by tfoote** [comment]
[jfaust] This is a limitation of the current `roslib/Log` message.

Ken, there seems to be a lot of roscpp-specific stuff in the Log message (and I'd like to add more -- the thread id).  What do you think about adding a way of providing generic information, e.g. an array of string/string pairs?

**Comment by tfoote** [comment]
[kwc] Definitely in favor of changing the roslib/Log message. It really is too roscpp-specific

**Comment by tfoote** [comment]
[gerkey] Passing to Ken to decide who should own it.

**Comment by dirk-thomas** [comment]
This will be closed since rxconsole is basically end-of-life. If this is still relevant for other use cases please comment and I will reopen.
