### ISSUE TITLE
rospy: unexpected behavior in latched topics

### ISSUE THREAD

**Issue by ernestmc** [ros/ros_comm#1481]
If you modify the message object after it has been published into a latched topic, the change propagates into the messages for new subscribers. Not sure if this is the designed behavior but it's certainly not documented nor intuitively expected.

## Steps to reproduce

1. Write the following `test.py` code:
```
import rospy
from std_msgs.msg import Bool
rospy.init_node("test_node")
pub = rospy.Publisher("/test", Bool, queue_size=10, latch=True)
rospy.sleep(1)
msg = Bool()
msg.data = False
pub.publish(msg)
rospy.sleep(1)
msg.data = True
rospy.spin()
```
2. Subscribe to the topic before running the program. Once you run it you will get this output:
```
$ rostopic echo /test
data: False
---
```
3. Now leave the program running, unsubscribe from the topic and subscribe again. You should see this:
```
^C$ rostopic echo /test
data: True
```

So with only one call to publish you get two different messages, which goes against ROS' documentation where it states:

> When a connection is latched, the last message published is saved and automatically sent to any future subscribers that connect.

**Comment by dirk-thomas** [comment]
Since messages are objects in Python the are passed "by reference". The API avoids to copy the passed message simply for performance reasons. So the behavior you see is what I would expect to happen.

If you think this can be clarified in the documentation please consider providing a patch to update the docblock(s) in the code and/or update the wiki page(s) describing the API.

**Comment by ernestmc** [comment]
Ok, thanks for the clarification @dirk-thomas

**Comment by cwecht** [comment]
There was actually an error in the rospy.Publisher documentation in the wiki. I fixed that. If think, this issue can be closed now.

**Comment by dirk-thomas** [comment]
@cwecht Can you please post a link to the wiki changes for future readers.

**Comment by cwecht** [comment]
@dirk-thomas sure! the change can be found [here](http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers#rospy.Publisher_initialization): the documentation of the latch-paramters had to be changed.

**Comment by dirk-thomas** [comment]
@cwecht Thanks for addressing this!

Link to the actual diff: http://wiki.ros.org/action/diff/rospy/Overview/Publishers%20and%20Subscribers?action=diff&rev1=38&rev2=39
