### ISSUE TITLE
Rosbag read_message ignoring nsces in start_time argument

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ros/ros_comm#1504]
I am not sure if this is an intended behaviour or a bug, but when reading a message with start_time specified the nsecs argument is ignored and the first timestamp is always the first message in the bag.
Code to reproduce:
```
import rosbag
import rospy
bag = rosbag.Bag("any_bag.bag")
start_time = rospy.Time(1536832350, 267408)
for topic, msg, t in bag.read_messages(topics=topics, start_time=start_time):
    print(msg.header.stamp)
```

I would expect the first timestamp to be after 267408 nsecs, but the first timestamp that gets printed is: 1536832350010483147.
I'm not sure how to look up the implementation, my ide does not really help me locate the code that is being called. Let me know if you need more information.
OS: Ubuntu 16.04
ROS: Kinetic

**Comment by dirk-thomas** [comment]
If I split the timestamps you posted above into seconds and nanoseconds:
* `start_time`: 1536832350s 267408ns
* first message: 1536832350s 10483147ns

it seems to be that the seconds part is equal and the nanoseconds part of the first message is greater than the nanoseconds part of the start time. That is what I would expect?

**Comment by Kaju-Bubanja** [comment]
Oh my bad, I somehow thought the ns were aligned. I just saw 26 and 01 and assumed it is less. But of course 0.000267408s is smaller than 0.010483147s
