### ISSUE TITLE
rosbag cannot record or play a bag file

### ISSUE THREAD

**Issue by junzengx14** [ros/ros_comm#1550]
ROS Kinetic
Linux 16.04

When I tried to play a bagfile, the following lines appear:
```
[ INFO] [1543303294.917432793]: Connected to master at [localhost:11311]
[ INFO] [1543303294.930954195]: Opening 2018-11-25-15-24-15.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
```
and then the execution is over. But when I use `rostopic list`, every topics are listed, even I closed that terminal. I tried to subscribe them in rviz but I failed, it's very strange...

When I tried to record a bagfile, the following lines appears:
```
[ INFO] [1543303585.625516606]: Subscribing to /rosout
```
and then the execution is over.

I use `top` in the terminal and notice that `rosout` has very high CPU occupation after I tried to record or play some bags.

**Comment by BoukeKromTNO** [comment]
The output doesn't look strange to me, and I experience no issues with rosbag. Since this does not seems to be an issue with the code directly, I think you're better off finding help at [answers.ros.org](https://answers.ros.org/questions/).

**Comment by junzengx14** [comment]
I tried to replay the same bag in my another computer, it works. it's really quite strange and I'm wondering if maybe it has some conflict with anaconda or other stuff. I will look for help in answers.ros.org. Thank you anyway!
