### ISSUE TITLE
sudo usage in test_udp_with_dropped_packets.sh

### ISSUE THREAD

**Issue by andersfischernielsen** [ros/ros_comm#1567]
`ros_comm/test/test_roscpp/test/scripts/test_udp_with_dropped_packets.sh` fails to run on a ROS container in docker.
`sudo` is unavailable in the docker container (the default user is already super user).

**Comment by betab0t** [comment]
not only sudo but also ifconfig and iptables :confused:

you can install them manually from inside the container shell like that:
```
apt-get update
apt-get install sudo net-tools iptables
```
**also notice that for iptables to work inside the container you need to pass the `--privileged` flag
`sudo docker run --privileged -it ros:melodic`

**Comment by andersfischernielsen** [comment]
Thanks! 😃

**Comment by betab0t** [comment]
I believe this issue can be closed
