### ISSUE TITLE
roscpp: roscpp xmlrpc does not support all documented API calls  (ros ticket #3228)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#157]
From the definition at: http://www.ros.org/wiki/ROS/Slave_API

getSubscriptions and getPublications, among others seem to be missing

trac data:
- Owner: **straszheim**
- Reporter: **leibs**
- Reported at: **Mon Jan  3 22:36:23 2011**
- URL: https://code.ros.org/trac/ros/ticket/3228

**Comment by tfoote** [comment]
[leibs] The attached patch adds support for the getSubscriptions and getPublications xmlRpc calls.  Could I get someone to double-check and see if there is anything glaringly wrong in what I've done?  I've been living in python and bash land for too long to trust myself to commit to roscpp trunk at this hour.

**Comment by tfoote** [comment]
[leibs] Troy thought the patch seemed reasonable and I double-checked it just now. I just pushed the change in r12744 since I'm blocked on it to close a rosbag ticket.  I'm leaving this ticket open for someone to implement the remaining xmlrpc slave api calls.

**Comment by dirk-thomas** [comment]
After breifly reviewing the documented slave API I could not see anything missing. Therefore closing for now. If you find API which is not documented please comment and I will reopen it.
