### ISSUE TITLE
roscpp: roscpp topic unsubscribe callbacks not called if no messages published  (ros ticket #3403)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#158]
I've noticed that the unsubscribe callbacks in roscpp, set up with advertise options, don't get called if the publisher doesn't publish any messages before the disconnection. 

Specifically:
- Set up publisher with subscribe/unsubscribe callbacks
- Subscribe to topic, subscribe callback gets called
- Don't publish messages
- Unsubscribe to topic, unsubscribe callback doesn't get called

Attached is a modified version of talker.cpp to test this problem. To verify:
- Run modified talker.cpp
  - It won't publish
- Run "rostopic echo chatter", then ctrl-C a few times
- Run "rostopic info chatter" to make sure topic not subscribed to
- Unsubscribe callback never gets hit.

trac data:
- Owner: **straszheim**
- Reporter: **watts**
- Reported at: **Tue Mar 15 13:41:00 2011**
- URL: https://code.ros.org/trac/ros/ticket/3403

**Comment by tfoote** [comment]
[watts] I should add that if messages actually publish from a publisher, then the unsubscribe callback does get hit.

**Comment by tfoote** [comment]
[watts] I've noticed several problems with subscriber connection callbacks using the openni_launch Kinect driver. Some of the nodelets use lazy subscriptions for Kinect data. I have noticed a warning message that the topic "camera/depth/image_rect_raw" wasn't sync'd. It turns out that this topic was not being published, because the nodelet wasn't subscribed to "camera/depth/image_raw". (Nodelet is image_proc/src/nodelets/rectify.cpp). 

Patrick, I'm using the Electric openni_kinect stack from "default", version 445. 

Troy, can you investigate this problem and see if  we have any other problems with these connection callbacks?

**Comment by tfoote** [comment]
[mihelich] I've noticed this issue with unsubscribe callbacks too. However, it's not true that they're never called; they _do_ get called exactly 60s after you subscribe.

In practice this shouldn't normally be an issue. In each nodelet we use connect callbacks to control whether it hooks into a data source (camera or ROS topic). As long as it's getting data, it publishes some processed output. So if all subscribers to the output unsubscribe, the next call to `publish()` triggers the disconnect callback, which unhooks from the data source. So as long as you're streaming data, disconnects will be timely.

It's still annoying and can cause odd behavior in practice - e.g. if the register nodelet doesn't get the tf data it needs, it can't `publish()`, so it takes the full 60s to disconnect. So I'd like to see this fixed, or at least know why it happens.

I've been hacking a lot on the OpenNI drivers recently and there were other connection-callback-related bugs in that code. The biggest issue was that all the nodelets had a race condition on startup - when you do something like `pub_ = it_.advertise("image", 1, cb, cb);` in `onInit()` you have to be careful. An `image_transport::Publisher` takes some non-negligible amount of time to create, so if a waiting subscriber connects immediately the connect callback can be scheduled onto a nodelet worker thread and called before `pub_` gets assigned to. Then the connect callback sees `pub_.getNumSubscribers() == 0` because `pub_` is empty. Yay nodelets.

I'm working to get all affected stacks released now that I'm back. If you want all the fixes now you also need image_pipeline and nodelet_core, see http://answers.ros.org/question/2993/registered-depth-only-works-sometimes-with.

**Comment by tfoote** [comment]
[adolforodriguez] I haven't verified the internals of roscpp, but the 60s timeout sounds like it may have something to do with TCP_FIN_TIMEOUT, which defaults to 60s for linux kernels > 2.2 (before it used to be a whooping 180s). The value can be verified by running cat /proc/sys/net/ipv4/tcp_fin_timeout

What condition must be verified for the unsubscribe() callback to be triggered?. If it's socket resource release, then this takes place by default 60s after the socket has been closed. When a socket connection is closed it follows the state sequence: ESTABLISHED -> CLOSED_WAIT ->TIME_WAIT. Citing [1]:

"TCP_FIN_TIMEOUT: This setting determines the time that must elapse before TCP/IP can release a closed connection and reuse its resources. During this TIME_WAIT state, reopening the connection to the client costs less than establishing a new connection. By reducing the value of this entry, TCP/IP can release closed connections faster, making more resources available for new connections."

Any chance that this is related to the problem at hand?.

[1] http://www.speedguide.net/articles/linux-tweaking-121

**Comment by tfoote** [comment]
[mihelich] That sounds plausible, and should be easy to test. The relevant socket code should be in `TransportTCP`: http://ros.org/doc/unstable/api/roscpp/html/transport__tcp_8cpp_source.html. Or maybe `PollSet`: ros.org/doc/unstable/api/roscpp/html/poll__set_8cpp_source.html

**Comment by dirk-thomas** [comment]
Closing due to a combination of age and the assumption that #1704 might resolve this case.
