### ISSUE TITLE
roscpp: roscpp getParamCached returns true after deleting a parameter  (ros ticket #3963)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#162]
I've attached a file that contains an example of this issue.

Basically, getting a calling ros::NodeHandle.getParamCached after having deleted the parameter returns true and an XmlRpcValue with this contents: <value><struct></struct></value>

The funny thing is that the first call after deleting the parameter sometimes has correct behaviour, but the following ones have the behaviour described above.

trac data:
- Owner: **dthomas**
- Reporter: **vlopez**
- Reported at: **Fri May 11 03:50:28 2012**
- URL: https://code.ros.org/trac/ros/ticket/3963

**Comment by dirk-thomas** [comment]
The current caching strategy for parameters in C++ does not allow to fix this issue as it does not preserve the necessary information. Marking it as `untargeted`.

**Comment by RainCT** [comment]
Note that the patch I provided in https://github.com/ros/ros_comm/issues/351 fixes this.

**Comment by dirk-thomas** [comment]
Addressed by #384.
