### ISSUE TITLE
roscpp: Transport plugins for roscpp  (ros ticket #3980)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#163]
Hi,

I've been experimenting with modifying roscpp to include a system of transport and filter plugins. The attach patch provides the required modifications, but no plugins except tcp and udp transport. 

The goal of transport plugins is to provide a way to use different transports than UDP or TCP, in particular shared memory and UDP multicast, but with no changes of API. 

The goal of the filter plugins is to provide way to implement pre/post-processing filters applied to the serialized message before sending. Typical examples would be compression, message signature, bandwidth control, ...

This version of the patch required pluginlib to be accessible for catkin (I have a version of the CMakeLists.txt) for that. Removing the dependency requires to comment one defines in the TransportPluginManager class. With the dependency, available transports are loaded automatically in ros::init.

The modifications can be grouped in 4 sets:
- Added the TransportPlugin abstract class, the TransportDescription and the TransportPluginManager classes, as well as FilterPlugins and FilterDescription.
- Modify TransportHints to use the more generic transport description and filters, and adapt the code using TransportHints where required.
- Modify ros::init to call the dynamic loading/unloading functions.
- Move the negociation mechanism from subscription.cpp and topic_manager.cpp toward classes in tcp_transport_plugin.cpp and udp_transport_plugin.cpp.

Test conducted so far show no change of behaviour of roscpp nodes.

Implemented plugins so far include shared memory, udp multicast and bz2 compression. They are not included in this patch but could be sent independently if necessary.

trac data:
- Owner: **dthomas**
- Reporter: **cedricpradalier**
- Reported at: **Wed Jun  6 03:32:13 2012**
- URL: https://code.ros.org/trac/ros/ticket/3980

**Comment by tfoote** [comment]
[cedricpradalier] The formatting did not work so well. So here it is again, hopefully with proper formatting: 

The modifications can be grouped in 4 sets:
- Added the TransportPlugin? abstract class, the TransportDescription? and the TransportPluginManager? classes, as well as FilterPlugins? and FilterDescription?.
- Modify TransportHints? to use the more generic transport description and filters, and adapt the code using TransportHints? where required.
- Modify ros::init to call the dynamic loading/unloading functions.
- Move the negociation mechanism from subscription.cpp and topic_manager.cpp toward classes in tcp_transport_plugin.cpp and udp_transport_plugin.cpp.

**Comment by dirk-thomas** [comment]
It is absolutely agreed on that the feature is a valuable extension to roscpp.

But there were also a lot of concerns:
- divergent of roscpp and rospy
- effect on existing API
- guarantee stability of existing code without regressions
- urgency to introduce these changes before ROS 2.0

Therefore it is not planned that the provided patch will be applied to roscpp.
Instead users can utilize the more flexible and powerful features from https://github.com/ethz-asl/ros-message-transport if they want.
