### ISSUE TITLE
roscpp: atexit() in libros.so (ros::init()) is harmful  (ros ticket #4023)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#164]
Hi,

ros::init() from libros.so installs an atexit(3) handler as seen here: https://code.ros.org/trac/ros/changeset/6740

This causes a segfault during program exit when libros is dlopen(3)'ed and dlclose(3)'d before the program termination.
A few libc work around this by implementing non-standard atexit() that behaves differently when called from a shared library. However, assuming standard posix behaviour, the atexit problem is almost impossible to workaround cleanly.

I think a library should not alter the global program state anyway, so I'd suggest providing the atexit() feature in libros as a separate function instead of calling it from ros::init() where it can't be disabled (e.g., ros::install_atexit_handler(), that the user can call if he needs this feature).

What do you think?

trac data:
- Owner: **dthomas**
- Reporter: **tho**
- Reported at: **Sat Aug  4 13:54:22 2012**
- URL: https://code.ros.org/trac/ros/ticket/4023

**Comment by tfoote** [comment]
[dthomas] To temporary work around it you can set g_atexit_registered to true before calling ros::init().

**Comment by dirk-thomas** [comment]
I do agree that it would be cleaner to not register the atexit handler per default but all existing ROS nodes do rely on the current implementation. Disabling it by default is therefore not an option as it changes behavior.

Please use the mentioned workaround to skip the atexit registration.
