### ISSUE TITLE
Wrong comparison of string literals in publisher.h:112

### ISSUE THREAD

**Issue by meyerj** [ros/ros_comm#165]
Since commit aa3adf0020e451005e5fea9ba9d9085fe87c676c gcc 4.6.3 emits the following warning message when compiling packages using roscpp publishers:

```
/opt/ros/groovy/include/ros/publisher.h: In member function ‘void ros::Publisher::publish(const M&) const [with M = sensor_msgs::JointState_<std::allocator<void> >]’:
/opt/hector/groovy/stacks/hector/monstertruck/monstertruck_gazebo_plugins/src/all_wheel_steering_plugin.cpp:467:37:   instantiated from here
/opt/ros/groovy/include/ros/publisher.h:112:12: warning: comparison with string literal results in unspecified behaviour [-Waddress]
```

The new code compares a const char \* returned by `mt::md5sum<M>(message)` with the string literal "*" in [publisher.h:112](https://github.com/ros/ros_comm/blob/aa3adf0020e451005e5fea9ba9d9085fe87c676c/clients/roscpp/include/ros/publisher.h#L112) directly without creating a temporary string object or using the strcmp function.

Also reported here: http://answers.ros.org/question/53930/roscpp-warning-in-rospublisherpublish/.

**Comment by cmastalli** [comment]
I would like to know how can I include this change in my machine? I tried it with sudo apt-get install --reinstall ros-groovy-roscpp but doesn't happen. I'm novice with subversion repositories and its methods to include modifications.

Thanks for advance!

**Comment by dirk-thomas** [comment]
The patch has been applied after 1.9.41 has been released. So you have to either wait for 1.9.42 to be released and the Debian package is available or build the package from source.

**Comment by cmastalli** [comment]
Thanks Dirk

**Comment by wmeeusse** [comment]
Do you have some info on the ETA for ros-comm 1.9.42?  This warning makes Groovy look pretty 'rough', and shows up every single time anyone compiles any ros code.  As a developer, my life on Groovy will be much better when I don't have to parse through pages of warnings when I compile my code. Anyway, I was just trying to emphasize the importance of this fix ;-)

**Comment by dirk-thomas** [comment]
Currently the shadow-fixed repository contains several bug fixes which should be synced soon - it was delayed a couple of times since several new releases (xacro, calibration, ...) introduced issues. Only after that sync has been made the current version of ros_comm (now already 1.9.45) will be build and arrive in shadow-fixed. Than it needs to wait again until all packages in shadow-fixed are "ok" to be synced to public.
