### ISSUE TITLE
ros::Timer::isValid() is not a const operation

### ISSUE THREAD

**Issue by turlac** [ros/ros_comm#1650]
I believe `ros::Timer::isValid()` could be made `const`. It seems to only rely on `ros::Duration::isZero()` which is a `const` operation. Or am I missing something here?

Source: 
https://github.com/ros/ros_comm/blob/melodic-devel/clients/roscpp/include/ros/timer.h#L75 
https://github.com/ros/ros_comm/blob/melodic-devel/clients/roscpp/src/libros/timer.cpp#L52

**Comment by dirk-thomas** [comment]
I don't see a reason why it could not be const. Please feel free to create a pull request for it. To not break ABI you will likely need to add a new const method rather then changing the existing signature.
