### ISSUE TITLE
Confusing: C++ waitForService timeout is milisec, Python wait_for_service timeout is seconds

### ISSUE THREAD

**Issue by peci1** [ros/ros_comm#1658]
The function docs say it, but it still seems to me confusing that the C++ part takes in milisec and Python seconds.
C++ has another method that takes in `ros::Duration` as timeout. However, Python only accepts doubles. 

I understand that it's impossible to change either behavior of the C++ or the Python calls regarding doubles, but could the Python version try to parse the argument as `rospy.Duration`?

**Comment by dirk-thomas** [comment]
Allowing to pass a duration sounds feasible. Please consider to provide a pull request for this feature idea.

**Comment by peci1** [comment]
Ok, I'll do the Python PR. 

I also had the idea of deprecating the int/double APIs. What's your view on that?

**Comment by dirk-thomas** [comment]
Deprecating existing API in use (since there is no other API) for no apparent reason other than "niceness" isn't something I would merge. Sorry.

**Comment by peci1** [comment]
Okay, no problem, I understand that. But when this issue is resolved, there will be the ros::Duration alternative API both in Python and C++. Maybe for N turtle?

**Comment by dirk-thomas** [comment]
> Maybe for N turtle?

The benefit needs to clearly outweigh the effort. And honestly I don't see any benefit for existing code to change.

**Comment by peci1** [comment]
;)

**Comment by peci1** [comment]
Fix published in https://github.com/ros/ros_comm/pull/1703 .
