### ISSUE TITLE
[Feature request] --all-nodes-required

### ISSUE THREAD

**Issue by Timple** [ros/ros_comm#1678]
roslaunch can handle a node attribute required:

> required="true"(optional)
> 
> ROS 0.10: If node dies, kill entire roslaunch.

However in some situations all nodes a required. E.g. when running as a systemd service (systemd can then trigger a restart if the process died with an error code)
Or when running CI to check if your roslaunch works.

But enabling required=true for all nodes is impractical
- when launching locally, you might not want this behavior
- when using launch files provided by others.

Therefor I suggest an argument `--all-nodes-required`

**Comment by mikepurvis** [comment]
This seems reasonable. There's prior art in the `--screen` flag, which is similarly equivalent to adding `output="screen"` to every node element. Patches welcome!
