### ISSUE TITLE
Persistent services frozen if service call returns false

### ISSUE THREAD

**Issue by v-lopez** [ros/ros_comm#168]
Hi, I'm having the following issue.

Using a persistent service client and calling a service that will returns false blocks the persistent client in the call method.

I'm using ROS Fuerte, installed from this debian: ros-fuerte-ros-comm_1.8.15-0precise-20120908-1755-+0000_i386.deb

This issue is critical because of what I described here: https://github.com/ros/ros_comm/issues/149#issuecomment-12960130

We're forced to use persistent services, because non-persistent calls create and destroy so many sockets that it slow downs our computer and affects heavily the global performance. But we're having many show-stopping issues using them such as the one described in this ticket and the one in #149 

I have a test that reproduces this issue but I can't upload it here, as it seems that  it only accepts images.

**Comment by v-lopez** [comment]
Tested on the latest groovy version in the debian packages and still happens. 

If you compile and execute the server below, you'll see that on the 10th iteration the server calls and never finishes the call.

Service server:

``` C++
#include "ros/ros.h"
#include "beginner_tutorials/AddTwoInts.h"

bool add(beginner_tutorials::AddTwoInts::Request  &req,
         beginner_tutorials::AddTwoInts::Response &res)
{
  res.sum = req.a + req.b;
  ROS_INFO("request: x=%ld, y=%ld", (long int)req.a, (long int)req.b);
  ROS_INFO("sending back response: [%ld]", (long int)res.sum);

  //If this number is provided, the service will return false
  if (req.b == 1234)
     return false;
  return true;
}

int main(int argc, char **argv)
{
  ros::init(argc, argv, "add_two_ints_server");
  ros::NodeHandle n;

  ros::ServiceServer service = n.advertiseService("add_two_ints", add);
  ROS_INFO("Ready to add two ints.");
  ros::spin();

  return 0;
}
```

Service client:

``` C++
#include "ros/ros.h"
#include "beginner_tutorials/AddTwoInts.h"


int main(int argc, char **argv)
{
  ros::init(argc, argv, "persistent_service_test");
  ros::NodeHandle n;

  ros::ServiceClient client = n.serviceClient<beginner_tutorials::AddTwoInts>("add_two_ints", true);

  beginner_tutorials::AddTwoInts srv;
  srv.request.a = 2;
  for (int i = 0; i < 100; i++)
  {
    srv.request.b = 2;

    if (i == 10)   //On iteration number 10, we send a number that is hard coded to return false on the server 
      srv.request.b = 1234;
   else
      srv.request.b = 2;

   ROS_INFO("Calling service server, iteration %d", i);
   if (client.call(srv))
   {
    ROS_INFO("Call successfull");
   }
   else
   {
     ROS_ERROR("Failed to call service ");
  }
}

  return 0;
}
```

**Comment by dpinol** [comment]
I found the problem. It's actually at roscpp_core/roscpp_serialization/include/ros/serialization.h
This commit https://github.com/ros/roscpp_core/commit/a5b8d2cd7ead809cf90c58c75a376f3f4769128f mad the failing service calls to always return the exception, but forgot to serialize the message size before the message.
For me it works if I just revert the code to send always "ok" and message in the same way no matter if the call failed or succeeded.

/**
- \brief Serialize a service response
  */
  template<typename M>
  inline SerializedMessage serializeServiceResponse(bool ok, const M& message)
  {
  SerializedMessage m;

//  if (ok)
  {
    uint32_t len = serializationLength(message);
    m.num_bytes = len + 5;
    m.buf.reset(new uint8_t[m.num_bytes]);

```
OStream s(m.buf.get(), (uint32_t)m.num_bytes);
serialize(s, (uint8_t)ok);
serialize(s, (uint32_t)m.num_bytes - 5);
serialize(s, message);
```

  }
/\*  else
  {
    uint32_t len = serializationLength(message);
    m.num_bytes = len + 1;
    m.buf.reset(new uint8_t[m.num_bytes]);

```
OStream s(m.buf.get(), (uint32_t)m.num_bytes);
serialize(s, (uint8_t)ok);
serialize(s, message);
```

  }
*/
  return m;
}

**Comment by dirk-thomas** [comment]
Reverting the above mentioned change breaks other case i.e. passing an exception to the client.

**Comment by dpinol** [comment]
Thank you Dirk, it now works perfectly!
