### ISSUE TITLE
rosparam YAMLLoadWarning

### ISSUE THREAD

**Issue by mbuijs** [ros/ros_comm#1686]
Recently I've been seeing the following warning when I run `rosparam set` from commandline.
```
$ rosparam set /use_sim_time true
/opt/ros/melodic/lib/python2.7/dist-packages/rosparam/__init__.py:370:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as
the default Loader is unsafe. Please read https://msg.pyyaml.org/load for
full details.
  set_param_raw(param, yaml.load(value), verbose=verbose)
```

As far as I could find this is related to the new release of pyyaml deprecating the use of `yaml.load(..)` as is described here: https://github.com/yaml/pyyaml/pull/257

Good to note is that I have PyYAML version 5.1 installed in my user directory through pip, this won't happen when using pyyaml from the Ubuntu repositories, since that's currently still version 3.12.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request to use `yaml.safe_load()` instead.
