### ISSUE TITLE
New release with ROSOUT_DISABLE_FILE_LOGGING?

### ISSUE THREAD

**Issue by marting87** [ros/ros_comm#1693]
Hi, 

The last release v1.14.3 was made on Aug 6, 2018. I would like to know when a new release/tag is planned.

I've been waiting a while for [Disable rosout.log by using environment variable (#1425) ](https://github.com/ros/ros_comm/commit/678ad4f239926111c7684c20f39ed91644aa1c13) where it would be possible to disable file logging of _/rosout_ by setting the parameter **ROSOUT_DISABLE_FILE_LOGGING** to True. This commit was made exactly 1 commit after  v1.14.3.

On my system I would like to prevent ROS writing to the file system, and run as much read-only as possible. 

Maybe it is possible to release this commit as v1.14.4?

Thanks!

**Comment by dirk-thomas** [comment]
A new release is being made when there is time to do it.

If you would like to speed up the process please consider to contribute to the effort: see https://discourse.ros.org/t/ros-comm-request-for-help/5840 and #1496.
