### ISSUE TITLE
[ROSLAUNCH] Unable to launch workspace nodes

### ISSUE THREAD

**Issue by clacarbone** [ros/ros_comm#170]
Is this by design?

[Architecture](http://ros.org/wiki/roslaunch/Architecture) says the user configuration is ignored when connecting via ssh.

Is there a way to have roslaunch access a user's workspace to load nodes?
[ROS Answers original question](http://answers.ros.org/question/54756/roslaunch-cant-find-my-node/)

**Comment by tfoote** [comment]
Yes you need to set the environment in the launch file.  Use the env_loader element in the machine tag: http://www.ros.org/wiki/roslaunch/XML/machine

**Comment by clacarbone** [comment]
I tried loading the user's own bashrc but it quits saying the user doesn't have the permission to access it.
So where does the env have to be stored?
Only ROS_ROOT works?

**Comment by dirk-thomas** [comment]
Please post the questions on http://answers.ros.org
