### ISSUE TITLE
Performance enhancements for rosbag filter

### ISSUE THREAD

**Issue by mikepurvis** [ros/ros_comm#1711]
Currently, `rosbag filter` deserializes every message in a bag, in a single threaded process, with a fresh `eval` each time. This is all enormously expensive and slow:

https://github.com/ros/ros_comm/blob/29053c4832229efa7160fb944c05e3bc82e11540/tools/rosbag/src/rosbag/rosbag_main.py#L374-L383

Some possibilities for how to improve this situation:

- Lazy deserialization: Instead of deserializing every time, pass a proxy object which uses __getattr__ to deserialize on demand and pass through accesses. This would prevent unnecessary deserialization expense for the use-cases which only filter on topic name or timestamp.
- Wrap the `eval` in a lambda, so that it needs to be compiled just once rather than on each use: https://stackoverflow.com/a/12467755/109517
- Use multiprocessing to parallelize the eval invocations—would have to check how much of a gain there is to be had here, particularly with the added cost of managing the work queue to maintain sequence.

**Comment by dirk-thomas** [comment]
Addressed by #1712.
