### ISSUE TITLE
Coverity - deadcode caused by logic error

### ISSUE THREAD

**Issue by danielwangksu** [ros/ros_comm#1745]
Event assignment: | Assigning: "found_new_type" = "False".
https://github.com/ros/ros_comm/blob/29053c4832229efa7160fb944c05e3bc82e11540/tools/rosbag/src/rosbag/migration.py#L830

 "found_new_type" = "False". the if can never reached
https://github.com/ros/ros_comm/blob/29053c4832229efa7160fb944c05e3bc82e11540/tools/rosbag/src/rosbag/migration.py#L841

It is probably should be:
```
if (found_new_type and (tmp_sn.new_class._type != new_type)):
```

**Comment by artivis** [comment]
This actually looks like a false alarm.

**Comment by danielwangksu** [comment]
> This actually looks like a false alarm.

Thanks I will close it
