### ISSUE TITLE
Coverity - forward null

### ISSUE THREAD

**Issue by danielwangksu** [ros/ros_comm#1746]
Event null_check: Comparing "f" to a null-like value implies that "f" might be null-like.
https://github.com/ros/ros_comm/blob/29053c4832229efa7160fb944c05e3bc82e11540/tools/rosgraph/src/rosgraph/roslogging.py#L61-L62

Event property_access: | Accessing a property of null-like value "f".
https://github.com/ros/ros_comm/blob/29053c4832229efa7160fb944c05e3bc82e11540/tools/rosgraph/src/rosgraph/roslogging.py#L76

There is a path for a null-valued variable to be dereferenced. But "f" might still be None

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this.
