### ISSUE TITLE
rostopic hz frequency measurement accuracy

### ISSUE THREAD

**Issue by scpeters** [ros/ros_comm#175]
The frequency measurement used by rostopic hz seems to be inaccurate at times. We are testing the atlas robot in the drcsim package, which publishes /clock at 1000 Hz. Each time I run `rostopic hz /clock`, it starts off with measurements near 1000 Hz but these steadily drift downwards. If I kill the command and restart it always starts again at 1000 Hz and drifts down. I've attached an example output at:

Here's a summary of the start:

```
subscribed to [/clock]
average rate: 1000.000
    min: 0.001s max: 0.001s std dev: 0.00000s window: 973
average rate: 1000.000
    min: 0.001s max: 0.001s std dev: 0.00000s window: 1949
average rate: 998.975
    min: 0.001s max: 0.003s std dev: 0.00004s window: 2926
average rate: 999.233
    min: 0.001s max: 0.003s std dev: 0.00004s window: 3908
```

and after a minute or so:

```
average rate: 986.563
    min: 0.001s max: 0.021s std dev: 0.00044s window: 50000
average rate: 986.543
    min: 0.001s max: 0.021s std dev: 0.00044s window: 50000
average rate: 986.426
    min: 0.001s max: 0.021s std dev: 0.00044s window: 50000
```

I've attached a full log to:

https://dl.dropbox.com/u/96660379/rostopic_hz_accuracy.txt

**Comment by tfoote** [comment]
I think the measurement is accurate.  It looks like you're dropping packets/experiencing network latency.  Note that at the beginning of your log the min and max times are both 0.001s while as the log goes on the max time between messages increases to 0.021s suggesting that you're missing 20 messages.  If you have network congestion and non-zero buffers that's not unreasonable.

**Comment by scpeters** [comment]
That makes sense. We also have frequency measurement of certain topics in gztopic and have been trying to reconcile the differences. Seeing this behavior made me think rostopic was doing something funny, but it seems like dropped packets could be a factor. Thanks.
