### ISSUE TITLE
css assets not served over https making site look broken

### ISSUE THREAD

**Issue by tom-spalding** [ros/ros_comm#1754]
sorry, I'm at a loss where to put this issue, so I'm just dropping it here and I hope someone can forward it to the correct party.

the main ROS page doesnt serve its css assets over https, making the page look broken.

![image](https://user-images.githubusercontent.com/2218331/61017140-f7169000-a346-11e9-954a-e012bc2369d8.png)

it looks like the page is using wordpress, so whomever is in charge of that may want to know. thanks in advance.

**Comment by tfoote** [comment]
Duplicate: https://github.com/osrf/www.ros.org/issues/78

**Comment by tfoote** [comment]
Thanks for flagging it. We're working to update it but haven't yet had time to focus on it.
