### ISSUE TITLE
This seems a deadcode

### ISSUE THREAD

**Issue by danielwangksu** [ros/ros_comm#1776]
https://github.com/ros/ros_comm/blob/7b69fc9e439c8e5b28a4f6a8e1c451ca7c96a8e8/tools/rosbag/src/rosbag/migration.py#L841-L842

due to https://github.com/ros/ros_comm/blob/7b69fc9e439c8e5b28a4f6a8e1c451ca7c96a8e8/tools/rosbag/src/rosbag/migration.py#L830-L840

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this.
