### ISSUE TITLE
rosmaster lacks a dependency on rospy

### ISSUE THREAD

**Issue by trainman419** [ros/ros_comm#179]
rosmaster uses rospy, but doesn't declare a dependency on it in its package.xml. This means that when installing the low-level packages, rosmaster and roslaunch can be installed without rospy.

**Comment by trainman419** [comment]
Similarly, rostopic appears to be missing a dependency on rosbag.

**Comment by dirk-thomas** [comment]
Can you please point to the line in the sources where rosmaster imports anything from rospy? I searched for rospy in the rosmaster package and got no results.

**Comment by trainman419** [comment]
The traceback from rosmaster is:

```
Traceback (most recent call last):
  File "/opt/ros/groovy/bin/rosmaster", line 35, in <module>
    rosmaster.rosmaster_main()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosmaster/main.py", line 73, in rosmaster_main
    configure_logging()   
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosmaster/main.py", line 57, in configure_logging
    _log_filename = rosgraph.roslogging.configure_logging('rosmaster', logging.DEBUG, filename=filename)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 105, in configure_logging
    logging.config.fileConfig(config_file, disable_existing_loggers=False)
  File "/usr/lib/python2.7/logging/config.py", line 78, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python2.7/logging/config.py", line 153, in _install_handlers
    klass = _resolve(klass)
  File "/usr/lib/python2.7/logging/config.py", line 88, in _resolve
    found = __import__(used)
ImportError: No module named rospy
```

The logger configuration in /opt/ros/groovy/share/rosgraph/conf/python_logging.conf uses a logger from within rospy, but doesn't depend on rospy; I think this is actually my fault.

At that level in the packages, I'm a little worried that adding more dependencies will create circular dependencies if we're not careful; it may be easier to move that configuration file to another package.

**Comment by dirk-thomas** [comment]
You can visualize the dependency graph with rqt_dep.
rospy depends on rosgraph, so the other way around is not possible.

**Comment by ahendrix** [comment]
It looks like the right solution here is to move the configuration file into rospy, and ship a default configuration file that doesn't depend on rospy with rosgraph, for the utilities that use rosgraph logging directly (roslaunch, rosmaster and rostest).

This also means adding arguments to rosgraph.roslogging.configure_logging to modify the search path for configuration files.
