### ISSUE TITLE
service exception using tf listener in rospy

### ISSUE THREAD

**Issue by bit-pirate** [ros/ros_comm#18]
This has been brought up on ros answers a while ago, but this minor bug is still around in Fuerte (on Ubuntu Precise 64bit).

http://answers.ros.org/question/10777/service-exception-using-tf-listener-in-rospy/

And regarding Tully's answer, he is right, this exception is only thrown on creation.

PS: I hope this is the right place for new tickets or should I report this on trac?
PPS: If this is the right place, we should update the "rospy wiki":http://www.ros.org/wiki/rospy.

**Comment by dirk-thomas** [comment]
This is the right place. The wiki page looks up-to-date linking to this repo.

**Comment by bit-pirate** [comment]
The source points to the right place, but posting bugs and requesting enhancements still points to code.ros.org.

**Comment by buzzer** [comment]
As this seems to be not fixed on Fuerte as of today I created a patch and want to share it. Where can I do that? Does it get applied upstream?

Anyway here is the patch:
https://github.com/ros/geometry/pull/26

**Comment by dirk-thomas** [comment]
I will this ticket since the new created geometry one is more appropriate to track this.
