### ISSUE TITLE
rosservice no longer executable from a launch file

### ISSUE THREAD

**Issue by dawonn** [ros/ros_comm#180]
In ROS-F I used the following line in my launch file to call a service once at launch time:

```
<node pkg="rosservice" type="rosservice" name="global_loc" args="call --wait /global_localization"/>
```

As of ROS-G, this no longer works.

**Comment by dawonn** [comment]
rostopic still works as expected, example:
    <node pkg="rostopic" type="rostopic" name="rbt_enable" args="pub /cmd_motor_state p2os_driver/MotorState  1"/>

If you compare the CMakeLists file in rosservice and rostopic, it would appear that the rosservice version is missing the install command. I have an untested fix in https://github.com/dawonn/ros_comm

**Comment by dawonn** [comment]
Pull request: https://github.com/ros/ros_comm/issues/181 

(Is there a way to merge these issues or for me to attach the pull request to this issue report? I don't see one... )

**Comment by dirk-thomas** [comment]
You can only attach a pull request to an already existing issue when you use the GitHub specific git api. See `git pull-request` at https://github.com/defunkt/hub.
I merged your pull request.
