### ISSUE TITLE
roslauch '-->' parsing error

### ISSUE THREAD

**Issue by dawonn** [ros/ros_comm#182]
I attempted to comment out the following line:

```
<!-- Distribute pose array across free space 
  <node pkg="rosservice" type="rosservice" name="global_loc" args="call --wait /global_localization"/>
-->
```

but roslaunch barfed on '--wait' because it was looking for '-->'

**Comment by dirk-thomas** [comment]
Please provide more information.

**Comment by dawonn** [comment]
dummy.launch:

```
<launch>
    <!-- 
    <node pkg="rosservice" type="rosservice" name="global_loc" args="call --wait /global_localization"/>
    -->
</launch>
```

If you try to use roslaunch on this file, you will get an error about a bad '--' token. 

If you replace '--wait' with '-!-wait' the script will execute normally.

**Comment by dirk-thomas** [comment]
This is invalid XML according to the spec: http://www.w3.org/TR/REC-xml/#sec-comments
roslaunch can do nothing about it.
