### ISSUE TITLE
Apt release of Melodic 1.14.4

### ISSUE THREAD

**Issue by Doomerdinger** [ros/ros_comm#1906]
Everything I see seems to indicate that 1.14.4 should've been pushed to apt, but it does not seem to be there. Am I missing something?

**Comment by flixr** [comment]
The packages have been built, but are still in the testing (shadow) repo.
They will become available in the main repo with the next sync.

You can also see that status here: http://repositories.ros.org/status_page/ros_melodic_default.html?q=ros_comm

**Comment by Doomerdinger** [comment]
Great! Thank you very much.
