### ISSUE TITLE
replacement for $(find PKG) to run scripts in catkin packages

### ISSUE THREAD

**Issue by dirk-thomas** [ros/ros_comm#192]
$(find PKG) returns the share folder of a package and can therefore not be used to run scripts from catkin packages as they are in lib/PKGNAME.

**Comment by dirk-thomas** [comment]
The problem is that the return value of a replacement is not determinable without the knowledge which path/file is used after the base path. Furthermore `rosrun`-like heuristic to search for files recursively is not desired because of the overhead.

**Comment by jonbinney** [comment]
Any progress on this? Can this be targeted for I-turtle?

**Comment by trainman419** [comment]
+1

In addition to scripts, this also applies to URDF components. Does this require changes to xacro as well?

**Comment by jonbinney** [comment]
Fixing this in roslaunch should mostly take care of xacro. Inside of the xacro code, it calls roslaunch.substitution_args to expand arguments. If that function call changes in roslaunch, then a couple of lines in xacro would need to be changed, but nothing major.

**Comment by dirk-thomas** [comment]
I have prepared a pull request to address this: #228 

It contains more comments on how it is supposed to work. Please take a closer look and provide feedback.

**Comment by dirk-thomas** [comment]
#233 fixed the eminent issue. #228 was closed due to not agreed on functionality.
