### ISSUE TITLE
XmlRpcValue: Implement a constructor that takes a ValueStruct

### ISSUE THREAD

**Issue by caioaamaral** [ros/ros_comm#1926]
I think it would be something like this:

`XmlRpcValue(ValueStruct const& value) : _type(TypeStruct) { _value.asStruct = new TypeStruct(value); }` *

It would be easier making XmlRpcValue as struct than using ` bool structFromXml(std::string const& valueXml, int* offset);` 

Faster to mock and by the end I could also generate the XML tags using `std::string XmlRpcValue::structToXml() const`

***should check if all XmlRpcValue inside it are true of course**

**Comment by dirk-thomas** [comment]
This repo contains a snapshot of the `XmlRpc++` library which isn't actively being maintained. There is no intention to do any kind of feature addition to it.

Therefore I am going to close this as a wontfix. Sorry.
