### ISSUE TITLE
relay_field fails when input topic does not exist yet

### ISSUE THREAD

**Issue by marcelino-pensa** [ros/ros_comm#1942]
ROS version: Kinetic

As mentioned in the title, `relay_field` cannot run if the input topic does not exist.
I am having trouble with this because I launch `relay_field` together with other nodes in a launch file. As the other nodes take longer to initialize their publishers, `relay_field` fails when there is no input topic. 
`relay_field` seems to have been designed to work that way ([see this](https://github.com/ros/ros_comm/blob/c7f7598e8a49b1b4eb6f3e42f698147e151a811d/tools/topic_tools/scripts/relay_field#L90)), but I think that it should change. The reason for `relay_field` to fail when there is no input topic is because it has no way to know the input topic message type, so it can't create the subscriber.

**Comment by marcelino-pensa** [comment]
Basic usage would be:

```
$ rosrun topic_tools relay_field /chatter /image sensor_msgs/Image "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: m.data
height: 0
width: 0
encoding: ''
is_bigendian: 0
step: 0
data: ''"

$ rosrun rospy_tutorials talker.py

$ rostopic echo /image
header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: hello world 1436995720.88
height: 0
width: 0
encoding: ''
is_bigendian: 0
step: 0
data: ''
...
```

**Comment by marcelino-pensa** [comment]
Sorry, I have just realized that there is an input argument `--wait-for-start`, which does what I want. 

The following works:
```
$ rosrun topic_tools relay_field /chatter /image sensor_msgs/Image "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: m.data
height: 0
width: 0
encoding: ''
is_bigendian: 0
step: 0
data: ''" --wait-for-start

$ rosrun rospy_tutorials talker.py

$ rostopic echo /image
header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: hello world 1436995720.88
height: 0
width: 0
encoding: ''
is_bigendian: 0
step: 0
data: ''
...
```

**Comment by lucasw** [comment]
Linking back to this question where topic_tools `transform` was failing with 

    ERROR: Wrong input topic (or topic field)`

https://answers.ros.org/question/349655/topic_tools-transform-works-in-console-but-not-in-launch-file

Is there a reason why `--wait-for-start` isn't on by default?  `rostopic echo` and I think everything else handles this gracefully:

     WARNING: topic [/fsd] does not appear to be published yet
