### ISSUE TITLE
std::bad_alloc on rosbag record -a

### ISSUE THREAD

**Issue by maximiliankir** [ros/ros_comm#1956]
After I built the rosbag package with catkin, I get a std::bad_alloc exception when running `rosbag record -a`. It seems like the exception is thrown in the constructor of Recorder. 

This Exceeption at this point makes absolutely no sense to me.
What am I doing wrong when building the rosbag package?

I get the following warnings while building:
```
/usr/bin/ld: warning: libboost_filesystem.so.1.65.1, needed by /home/maximilian/adda_ros/devel/lib/librosbag.so, may conflict with libboost_filesystem.so.1.54.0
/usr/bin/ld: warning: libboost_regex.so.1.54.0, needed by /home/maximilian/adda_ros/devel/lib/librosbag.so, may conflict with libboost_regex.so.1.65.1
/usr/bin/ld: warning: libboost_system.so.1.54.0, needed by /usr/local/lib/libboost_filesystem.so, may conflict with libboost_system.so.1.65.1
/usr/bin/ld: warning: libboost_filesystem.so.1.65.1, needed by /home/maximilian/adda_ros/devel/lib/librosbag.so, may conflict with libboost_filesystem.so.1.54.0
/usr/bin/ld: warning: libboost_system.so.1.54.0, needed by /usr/local/lib/libboost_filesystem.so, may conflict with libboost_system.so.1.65.1
```
Are these warnings related to the problem and how can I solve it?

### System Info
Ubuntu 18.04
ROS Melodic

**Comment by dirk-thomas** [comment]
It sounds like you are mixing `boost` version. Ubuntu Bionic ships with 1.65.1. You seem to have a different version installed beside that. You need to make sure to only have one `boost` version in your environment and if it is different from the default you need to build all ROS packages from source.

In general questions like this should be asked on aswers.ros.org.
