### ISSUE TITLE
[roslaunch] --ros-args option fails in noetic

### ISSUE THREAD

**Issue by xaver-k** [ros/ros_comm#1971]
# Short description

Running `roslaunch` with the option `--ros-args` under ROS noetic fails.

# Expected behavior

Print the arguments of the launch file like under ROS melodic.
As an example, getting the arguments of roslaunch's own example launch-file via
```
docker run --rm -it ros:melodic-robot roslaunch roslaunch example.launch --ros-args
```
gives
```
Optional Arguments:
  commandline_true_arg (default "true"): undocumented
```

# Acutual behavior

Running any of the below commands
```
docker run --rm -it ros:noetic-robot roslaunch roslaunch example.launch --ros-args
docker run --rm -it ros:noetic-robot roslaunch --ros-args roslaunch example.launch
docker run --rm -it ros:noetic-robot roslaunch /opt/ros/noetic/share/roslaunch/resources/example.launch --ros-args
docker run --rm -it ros:noetic-robot roslaunch --ros-args /opt/ros/noetic/share/roslaunch/resources/example.launch
```

Gives 
```
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 275, in main
    import arg_dump as roslaunch_arg_dump
ModuleNotFoundError: No module named 'arg_dump'
```

# Thoughts

I suspect that https://github.com/ros/ros_comm/blob/7ee09ea5cc215733014f47394e6c55ccff69d814/tools/roslaunch/src/roslaunch/__init__.py#L277

should be 
```python
from . import arg_dump as roslaunch_arg_dump 
```
because of the switch to python 3.

**Comment by dirk-thomas** [comment]
Please create a pull request with the proposed change.
