### ISSUE TITLE
rospy fails to release socket resources: too many open files error (ros ticket #3808)

### ISSUE THREAD

**Issue by dpinol** [ros/ros_comm#198]
https://code.ros.org/trac/ros/ticket/3808 is happening again with both "ros-fuerte-ros-comm 1.8.15" and "ros-groovy-ros-comm 1.9.41".

I have ubuntu 12.4 32 bits

**Comment by dirk-thomas** [comment]
Please provide more information / a reproducible example.

The one mentioned in the issue on code.ros.org does not output the mentioned error for me. For the record I am using ROS groovy, ros_comm 1.9.41 on Ubuntu 12.10 64 bit.

**Comment by dirk-thomas** [comment]
Closed due to lack of response.
If the requested information is provided the issue can be reopened.
