### ISSUE TITLE
Invent a replacement for roslaunch (find ...) for executables in catkin packages

### ISSUE THREAD

**Issue by tkruse** [ros/ros_comm#199]
As a consequence of the problem that scripts need to be both rosrun-able and also roslaunch findable.
https://github.com/ros/xacro/issues/2

I suggest something like (find-runnable package executable name) that maps to the same thing rosrun uses.

(find ...) may stay for non-executable resources (e.g. yaml files)

**Comment by dirk-thomas** [comment]
duplicate #192
