### ISSUE TITLE
New Noetic Release

### ISSUE THREAD

**Issue by hikinggrass** [ros/ros_comm#1996]
Is a new release before the next noetic sync planned?
I think that would be very good, given the merged fixes since the last version.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-noetic-sync-2020-07-03/15171/4

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-noetic-sync-2020-07-03/15171/5

**Comment by dirk-thomas** [comment]
The patch release 1.15.8 has been tagged and ros/rosdistro#25909 is pending.
