### ISSUE TITLE
New Melodic release

### ISSUE THREAD

**Issue by smipi1** [ros/ros_comm#1997]
Would it be possible for a new Melodic release?
The Ubuntu bionic package is stuck at 1.4.1 and fixes for a few nasty bugs only landed in 1.4.4.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-noetic-sync-2020-07-03/15171/5

**Comment by dirk-thomas** [comment]
> The Ubuntu bionic package is stuck at 1.4.1 and fixes for a few nasty bugs only landed in 1.4.4.

The latest released version in Melodic is 1.14.6 (from May 29th): https://github.com/ros/rosdistro/blob/4d65c3c8e7cb173a5f7a0fa584e36fb6470c134a/melodic/distribution.yaml#L8927 / ros/rosdistro#25202.

**Comment by dirk-thomas** [comment]
There are no significant patches in the upcoming Melodic patch release 1.14.7: see #2008.

**Comment by dirk-thomas** [comment]
Actually #1932 was also merged for the upcoming Melodic patch release which contains a significant patch.

**Comment by smipi1** [comment]
Thanks for the update!

**Comment by dirk-thomas** [comment]
#1684 and #2014 were also merged for the upcoming Melodic patch release - with a significant fix.

**Comment by dirk-thomas** [comment]
New Melodic release 1.14.7 in flight: ros/rosdistro#26012.
