### ISSUE TITLE
Rospy import *

### ISSUE THREAD

**Issue by UnexpectedLobster** [ros/ros_comm#2004]
Hi, 

Doing 
```python
from rospy import *
```
raises the following exception : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rospy' has no attribute 'NodeProxy'
```
After some investigations, `NodeProxy` doesn't seem to exist anymore in the codebase. Simply removing it from the exports should do the trick.

**Comment by dirk-thomas** [comment]
Please consider to contribute a pull request for the suggested fix.

**Comment by dirk-thomas** [comment]
To resolve this bug in the upcoming patch release I went ahead and created #2007.
