### ISSUE TITLE
rosbag leaves an ".active" file dangling when receiving SIGTERM

### ISSUE THREAD

**Issue by thomas-moulard** [ros/ros_comm#2006]
Currently, rosbag leaves a dangling ".active" file when stopped with SIGTERM.

1. Can we update `rosbag` so that the behavior of SIGTERM and SIGINT is the same?
2. Would it be acceptable to backport this behavior to Kinetic, and Melodic?

**Comment by emersonknapp** [comment]
Extra note: SIGINT on the main process has the same behavior. SIGINT on the process group works as expected

**Comment by dirk-thomas** [comment]
Please consider to contribute a pull request for this.

> Would it be acceptable to backport this behavior to Kinetic, and Melodic?

That depends on the patch necessary. The intended behavior change (to clean up a dangling file) sounds reasonable.
