### ISSUE TITLE
rostopic latch messages in the rate mode when piped

### ISSUE THREAD

**Issue by bgromov** [ros/ros_comm#201]
`rostopic` latch messages in the _Rate mode_ when piped, although latching is not explicitly turned on. Same happens when publishing messages from a file.

Relevant [question](http://answers.ros.org/question/59070/disable-latching-for-rostopic-in-piping-mode/) on Answers.

**Comment by dirk-thomas** [comment]
Please post more information: i.e. executed commands as well as expected and actual output.

**Comment by bgromov** [comment]
Here are the commands with their respective outputs:

```
# Not latching
$ rostopic pub -r 10 /str std_msgs/String "Hello world"
<No output here>
^C

# Still not latching
$ rostopic pub -r 10 --latch /str std_msgs/String "Hello world"
<No output here>
^C

# Latching again
$ rostopic pub -r 10 /another_str std_msgs/String "Test" &
$ rostopic echo /another_str | rostopic pub -r 10 /str std_msgs/String
publishing and latching message for 3.0 seconds
publishing and latching message for 3.0 seconds
...
publishing and latching message for 3.0 seconds
^C
```

The expected behaviour is non-latching in rate mode (by default). However the actual latching was not tested yet, so this is based on the console output only.

**Comment by bgromov** [comment]
Here is a small test (duplicate from discussion on Answers)

```
$ for i in {1..1000}; do printf "data: ${i}\n---\n"; sleep 0.5; done | rostopic pub /test std_msgs/UInt64 > /dev/null & sleep 2 && rostopic echo /test
[1] 12431
data: 1
---
data: 2
---
data: 3
---
data: 4
---
data: 5
---
^C
$ kill $!
```

From the next one we can see that every message is latched indeed for 3 seconds (note the delay before echo for **9** seconds):

```
$ for i in {1..1000}; do printf "data: ${i}\n---\n"; sleep 0.5; done | rostopic pub /test std_msgs/UInt64 > /dev/null & sleep 9 && rostopic echo /test
[1] 12605
data: 18
---
data: 19
---
data: 20
---
data: 21
---
^C
$ kill $!
```

**Comment by tfoote** [comment]
To test for latching you need to publish at a slow rate.  Let one message be published, and then start a subscriber and see if it gets the message immediately or waits until the next time the rate comes around.  

From my tests, case 1 doesn't latch. Case 2 latches.  Case 3 is really hard to test due to the sequencing.  But as far as I can tell it's working fine.  

Your bash scripts don't test or demonstrate latching or not.  I'm not sure what the rate option means when combined with a pipe.  

I'm marking as minor untargeted as I don't know of a use case that this breaks. In general latching is recommended for anything which is going to be potentially only short lived.

**Comment by dirk-thomas** [comment]
I checked the behavior of `rostopic pub`.
When invoked without arguments it does send one latched message.

When using a rate argument it does not perform latching by default.
When using a rate like `-r 0.2` and listen to the topic using `rostopic echo` you might have to wait up to 5 seconds until the next message arrives.

When using a rate argument with the `--latch` option it performs latching as expected.
When using a rate like `-r 0.2` and listen to the topic using `rostopic echo` you will receive the first message immediately and then up to 5 seconds until the next message arrives.

I can not follow the example with the for loops. I do neither understand what you expect from the test nor how the result differences from your expectation.

I will close this as it does not seem to be a bug from our understanding. Please comment if think it is still an issue and provide more information.
