### ISSUE TITLE
1.14.9 on melodic breaks actionlib wait_for_server() and rostopic echo

### ISSUE THREAD

**Issue by daenny** [ros/ros_comm#2030]
After the update to 1.14.9 on melodic since yesterday something in the message passing seems wrong.

```
roscore
rostopic pub /test std_msgs/String "data: 'test'" -r 1
rostopic hz /test  # works
rostopic echo /test # does not show anything
```

Also running the `actionlib_tutorials` on python hangs on `wait_for_server`.

Downgrading to `ros_comm` `1.14.7` via source checkout fixes this issues.

**Comment by daenny** [comment]
Running another `sudo apt upgrade` fixed this issue

**Comment by knorth55** [comment]
we have a similar issue.
we can get `rostopic hz /robotsound` but we cannot get `rostopic echo /robotsound` with `sound_play/SoundRequest`/
which package should be upgraded?

cc. @708yamaguchi @pazeshun
