### ISSUE TITLE
advertisetest ist not installed

### ISSUE THREAD

**Issue by beetleskin** [ros/ros_comm#2045]
**What did you try?**
I stumbled upon [advertisetest](https://github.com/ros/ros_comm/blob/melodic-devel/tools/rostest/nodes/advertisetest) (https://github.com/ros/ros_comm/pull/1761), and tried to use it in my stack with ROS from melodic ppa.

**What did you observe?**
There is no _advetisetest_ executable installed on my machine.

**What did you expect?**
_advetisetest_ to be installed, similar to _hztest_ and the others.

**All said?**
- It seems it was just forgotten to be installed, see https://github.com/ros/ros_comm/pull/1761/files#diff-0de0276d02036474cf5bb304030cf6ae
- The script seems quite similar to publishtest, why are there two implementations of almost the same tests?
- There is no documentation on http://wiki.ros.org/rostest/Nodes?
- Is it on purpose, that _advertisetest_ does not adhere remappings?

**Comment by dirk-thomas** [comment]
Addressed by #2046.
