### ISSUE TITLE
[Hydro-devel] $(find <PKG>) should provide a way to search BIN, LIB, or SHARED DESTINATION

### ISSUE THREAD

**Issue by jihoonl** [ros/ros_comm#205]
I was trying to parse turtlebot description using catkin version of xacro in the install space.

```
 <arg name="urdf_file" default="$(find xacro)/xacro.py '$(find turtlebot_description)/robots/$(arg base)_$(arg stacks)_$(arg 3d_sensor).urdf.xacro'" />
```

The issue is that 'xacro.py' is located in lib and $(find <PKG>) only searches shared directory.

$(find <PKG>) should provide a way to search BIN, LIB, or SHARED in smarter way.

**Comment by tfoote** [comment]
A replacement for $(find) is ticketed in #192  

For existing packages you need to install a redirect script in share to keep old packages working.  There's an open issue ros/xacro#2 Note you also need to take care of the devel space too. 

Closing duplicate.
