### ISSUE TITLE
Backport #2038 to Melodic

### ISSUE THREAD

**Issue by dabonnie** [ros/ros_comm#2060]
Backport the fix in #2038 (which resolves #2006) to Melodic.

**Comment by dabonnie** [comment]
FYI @dirk-thomas and @chapulina: is this the preferred way to track a backport? If so I will file another ticket for Kinetic as well. 

Do either of you have a sense of the backport timeline?

**Comment by dirk-thomas** [comment]
Closing for the same reason as stated in #2058.

#2038 has been marked with the "consider-backport" label and will be backported for the next patch release. There is no timeline when that will happen and I can't provide an estimate. It solely depends on when enough significant bug fixes have accumulate which warrant a new release.
