### ISSUE TITLE
rqt_bag won't show context menu to enable publishing

### ISSUE THREAD

**Issue by jbohren** [ros/ros_comm#207]
When I try to right-click on the timelines in rqt_bag after loading a bag file, I see this error in the console about a hundred times:

```
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rqt_bag/bag_timeline.py", line 444, in on_mouse_move
    self._timeline_frame.on_mouse_move(event)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rqt_bag/timeline_frame.py", line 1068, in on_mouse_move
    clicked_x = self._clicked_pos.x()
AttributeError: 'NoneType' object has no attribute 'x'
```

Since I can't right click, I can't enable any of the topics to be published.

rqt_bag is version `0.2.14-0-precise-20130329011410+0000`

**Comment by dirk-thomas** [comment]
This issue seems to be unrelated to ros_comm. Please consider opening a ticket in the repository containing rqt_bag: http://github.com/ros-visualization/rqt_common_plugins
