### ISSUE TITLE
non persistent rospy ServiceProxy is not thread-safe

### ISSUE THREAD

**Issue by kevinshchang** [ros/ros_comm#2078]
Relevant code

https://github.com/ros/ros_comm/blob/090daa56f57d18c39946f107bcee5e3efefb2cac/clients/rospy/src/rospy/impl/tcpros_service.py#L481-L537

The self.transport gets set during a service proxy call, and then gets unset if the proxy is not persistent. 

This behavior is not thread safe if multiple threads are trying to use the same service proxy, as it could get unset as another thread is about to use the self.transport variable.

running the following should lead to errors
```python
     #!/usr/bin/env python

    import rospy
    from std_srvs.srv import Empty, EmptyResponse
    from threading import Timer

    class Test():
        def __init__(self):
            rospy.Service('/test', Empty, self.handle_request)
            self.proxy = rospy.ServiceProxy('/test', Empty, persistent=False)
        
        def handle_request(self, request):
            rospy.sleep(0.1)
            return EmptyResponse()
        
        def call_service(self):
            response = self.proxy.call()
            rospy.logwarn(response)
        
    if __name__ == "__main__":
        rospy.init_node("test")
        t = Test()
        a1 = Timer(2.01, t.call_service)
        a2 = Timer(2.02, t.call_service)
        a3 = Timer(2.03, t.call_service)
        a4 = Timer(2.04, t.call_service)
        a5 = Timer(2.05, t.call_service)
        a1.start()
        a2.start()
        a3.start()
        a4.start()
        a5.start()  
        rospy.spin()
```

**Comment by hamidreza-abrar** [comment]
i use anaconda in windows64 . python 3
line1: import rospy -> dosen work for me. and this error happen: 
(ModuleNotFoundError: No module named 'rospy')
how an i install rospy module in anaconda
