### ISSUE TITLE
compile rosbag_storage

### ISSUE THREAD

**Issue by neilzhy** [ros/ros_comm#2093]
I want to compile rosbag_storage for debuging. I can not find notebook to compile rosbag_storage.
Can anyone help me?

**Comment by sloretz** [comment]
Please ask this question on https://answers.ros.org. See the [ROS Support guidelines](http://wiki.ros.org/Support) for tips on where to go for help in the future.

You may be interested in this wiki page on building ROS 1 from source: http://wiki.ros.org/Installation/Source
