### ISSUE TITLE
raw_input does not exist in python3

### ISSUE THREAD

**Issue by bst** [ros/ros_comm#2141]
[rosbag_main.py ](https://github.com/ros/ros_comm/blob/b6c23e1282815823c8e07b47384391cf7cf0eab4/tools/rosbag/src/rosbag/rosbag_main.py#L554) and [makerule.py](https://github.com/ros/ros_comm/blob/b6c23e1282815823c8e07b47384391cf7cf0eab4/tools/rosbag/scripts/makerule.py#L136) still use `raw_input()`, which was renamed to `input()` in python 3. Both do not work on noetic with python 3.

**Comment by jacobperron** [comment]
Resolved in #2143
