### ISSUE TITLE
missing noetic rosbag API documentation

### ISSUE THREAD

**Issue by flynneva** [ros/ros_comm#2157]
similar to #2153, but I noticed on the [rosbag noetic wiki](http://wiki.ros.org/rosbag) that the [link for the Python API](http://wiki.ros.org/rosbag/Code%20API#py_api) for rosbag is broken/exists but [nothing is there.](https://docs.ros.org/en/api/rosbag/html/python/)

Is there someplace else that the documentation is hosted for noetic?
is it OK to just use [Melodic API documentation](http://docs.ros.org/en/melodic/api/rosbag/html/python/)?

**Comment by gavanderhoorn** [comment]
Is this https://github.com/ros-infrastructure/rosdoc_lite/issues/98?

**Comment by flynneva** [comment]
yes that's it! sorry I'll close this

**Comment by gavanderhoorn** [comment]
No need to apologise.
