### ISSUE TITLE
LICENSE for v1.12.17

### ISSUE THREAD

**Issue by oanastanca** [ros/ros_comm#2174]
Hello,

 Can you please specify which BSD(full text), mentioned in https://github.com/ros/ros_comm/blob/1.12.17/ros_comm/package.xml applies on ros_comm v1.12.17 ?
 
There is no LICENSE file regarding the BSD that applies on ros_comm 1.12.17.

 Thank you

**Comment by mikepurvis** [comment]
The individual source files all include a full-text license header, eg:

https://github.com/ros/ros_comm/blob/1.12.17/clients/roscpp/include/ros/ros.h#L1-L33

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/status-of-os-license-clearing-for-ros2/33753/6
