### ISSUE TITLE
Clarify the documentation for method getNumSubscribers()

### ISSUE THREAD

**Issue by blaroche** [ros/ros_comm#22]
This is an enhancement issue based on the discussions about this question: http://answers.ros.org/question/11167/how-do-i-publish-exactly-one-message

The method getNumSubscribers() returns the number of subscribers that are currently connected to the local publisher, and not the total number of subscribers for that topic.

The documentation should be clarified to avoid misinterpretations. Also, it could link to a method that would return the total number of subscribers for that topic.

**Comment by dirk-thomas** [comment]
Please point to the documentation which you would like to be updated.
The publisher API do states that already: http://ros.org/doc/groovy/api/roscpp/html/classros_1_1Publisher.html#ad56c8e954020290dcb87cd6bbd330a2b

**Comment by blaroche** [comment]
Oh no, now I can't find the web page anymore. I think that I was initially following a tutorial/example, rather than looking at the API. If I find it again, I'll post it here.

An alternative would be to deprecate this method and make one called getNumConnectedSubscribers()
