### ISSUE TITLE
roslaunch: Inappropriate ioctl when running nodes in gdb through roslaunch

### ISSUE THREAD

**Issue by jarvisschultz** [ros/ros_comm#223]
As mentioned in [this answers.ros.org question](http://answers.ros.org/question/48056/using-roslaunch-with-gdb-gives-error-tcsetpgrp-failed-in-terminal_inferior-inappropriate-ioctl-for-device/), when using roslaunch to run a node in `gdb` e.g. with `launch-prefix="gdb -ex run --args"`, the following error is printed many times:

```
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
```

this does not happen when directly running the binary in `gdb`. It doesn't seem to matter much, but it would be nice to fix nonetheless.

**Comment by dirk-thomas** [comment]
It seems to be that this is a bug in gdb: http://sourceware.org/ml/gdb/2007-08/msg00170.html
If you can provide more insight how this could be resolved in roslaunch I would be happy to hear it. Else I suspect that there is not much we can do about it.

**Comment by jarvisschultz** [comment]
I certainly have no insight as to what is actually causing the problem, it definitely could be purely a `gdb` issue.  It is strange that it doesn't happen with `gdb` in general, but only when adding `gdb` launch-prefix args in launch files.

**Comment by dirk-thomas** [comment]
The reason why it only happens via roslaunch for you is because then gdb is not running in a normal terminal anymore but as a subprocess.

**Comment by dirk-thomas** [comment]
Closing since it is supposed to be an issue of gdb which we can't do anything about it.
