### ISSUE TITLE
catkin_make runs multiple rostests in parallel with the same MASTER_URI

### ISSUE THREAD

**Issue by DLu** [ros/ros_comm#224]
See discussion here: http://answers.ros.org/question/62553/multiple-cores-running-in-rostest/

**Comment by dirk-thomas** [comment]
rostest uses a fixed rosmaster and can therefore not be invoked in parallel. This has already been fixed in catkin_make ros/catkin@c199d7b2f356b55ba4bf83ea45900482f8bd7a96 which will be released with the next patch release.
