### ISSUE TITLE
Executing Roslaunch commands inside a running container

### ISSUE THREAD

**Issue by tecena** [ros/ros_comm#2287]
Hi,

I am trying to run autoware with carla. Autoware is running as a container in linux machine. now after starting the container, with the following commands 

**docker run \
    -d \
    -it --rm \
    --volume=$(pwd)/autoware-contents:/home/autoware/autoware-contents:ro \
    --env="DISPLAY=${DISPLAY}" \
    --privileged \
    --net=host \
    $RUNTIME \
    carla-autoware:latest**, the container is up 

now I want to launch my launch files to start the auotware nodes using
**roslaunch carla_autoware_agent carla_autoware_agent.launch town:=Town04 synchronous_mode:=true** 
with out entering into the container so I tried to run with docker exec, I am getting the following error 
**OCI runtime exec failed: exec failed: unable to start container process: exec: "roslaunch": executable file not found in $PATH: unknown**

How do I run the roslaunch command in a linux machine without entering into the container either using shell script.

**Comment by mikepurvis** [comment]
Hey there— this issue tracker is for reporting bugs. For general support, please use ROS Answers: https://answers.ros.org/questions/
