### ISSUE TITLE
New rospy noetic release

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros/ros_comm#2291]
Could we get a new noetic release for rospy (and maybe the other packages as well).

As I would like to have the fix from #2233 released.

**Comment by mogumbo** [comment]
I'll second that. We see that problem in our sim as well, and we'd like to have that workaround.

**Comment by MatthijsBurgh** [comment]
Friendly reminder @jacobperron @mjcarroll @sloretz

**Comment by MatthijsBurgh** [comment]
Please also include https://github.com/ros/ros_comm/pull/2290

**Comment by MatthijsBurgh** [comment]
Friendly reminder @jacobperron @mjcarroll @sloretz

**Comment by sloretz** [comment]
https://github.com/ros/rosdistro/pull/35405
