### ISSUE TITLE
Possibility to limit rosbag open memory requirements

### ISSUE THREAD

**Issue by kis-balazs** [ros/ros_comm#2323]
Hi!

We are looking into extracting .csv files from ROS bags, and some of the bags are quite large (>40Gb). We tried limiting the soft limit of the memory usage for the python process executing - not to exceed certain required thresholds. This triggers a very specific MemoryException piping into "rosbag.bag.ROSBagUnindexedException: Unindexed bag" exception.

Do you have any recommendations how to limit/handle this in a better way? :)

Thank you!

**Comment by kis-balazs** [comment]
Hi, any update on this? :)

**Comment by mikepurvis** [comment]
@kis-balazs Questions of a "how do I" nature are better suited for answers.ros.org— this is a bug/feature tracker.

That said, I would try to implement your csv-extractor in C++ instead, as I believe the C++ interface to rosbag is more disciplined about not trying to load the whole thing into memory: http://wiki.ros.org/rosbag/Code%20API#C.2B-.2B-_API
