### ISSUE TITLE
roslaunch: provide catkin implementation of rosbuild_add_roslaunch_check()

### ISSUE THREAD

**Issue by jack-oquin** [ros/ros_comm#241]
No equivalent is listed in the documentation. Some catkin solution to that problem is needed.

See: http://answers.ros.org/question/64476/catkin-version-of-rosbuild_add_roslaunch_check/

I originally opened ros/catkin#439 for this problem, but was told it should be addressed in **roslaunch**, instead.

**Comment by jack-oquin** [comment]
Once this is released, I suppose I will need to add this to my package.xml?

```
<test_depend>roslaunch</test_depend>
```

**Comment by dirk-thomas** [comment]
You will need to build_depend on roslaunch since you have to find_package() it in order to use it at CMake time.

**Comment by dirk-thomas** [comment]
Initial patch had a bug #257.
