### ISSUE TITLE
rostopic echo of uint8[] seems to be displayed as a string, rather than array

### ISSUE THREAD

**Issue by scpeters** [ros/ros_comm#242]
Trying to rostopic echo a message with a uint8[] array (see the k_effort field in [atlas_msgs/AtlasCommand](https://bitbucket.org/osrf/drcsim/src/7ff63e8aab47973b10539420d5a8685aa2bb9384/ros/atlas_msgs/msg/AtlasCommand.msg?at=default) in drcsim as an example) causes the array not to be displayed properly; it seems to be interpreted as a string.

**Comment by scpeters** [comment]
To reproduce:

First terminal

```
rostopic pub /test std_msgs/UInt8MultiArray '{data: [82, 79, 83]}' -r 1
```

Second terminal

```
rostopic echo /test/data
```

**Comment by dirk-thomas** [comment]
That only happens when you try to output individual message fields (because the actual type information is lost). When you call:

```
rostopic echo /test
```

the array is printed correctly.

**Comment by scpeters** [comment]
When you have large messages, you may need to filter down in order to see the field that you're interested in. In the case of the [AtlasCommand](https://bitbucket.org/osrf/drcsim/src/7ff63e8aab47973b10539420d5a8685aa2bb9384/ros/atlas_msgs/msg/AtlasCommand.msg?at=default) message, we found that `rostopic echo /atlas/atlas_command | grep k_effort` was a functional workaround, but only because k_effort was easily greppable. The user shouldn't be forced into text manipulation in order to work around this bug.

**Comment by dirk-thomas** [comment]
My comment did not imply any judgement if the issue should be addressed or not. I just wanted to state the scenario more precisely.

I created a pull request addressing it: #243

**Comment by scpeters** [comment]
Thanks!

**Comment by dirk-thomas** [comment]
This change seems to break `rostopic topic/field[index]` as reported here: http://answers.ros.org/question/72940/does-rostopic-echo-no-longer-work-for-arrays/

**Comment by swinterbotix** [comment]
Not sure if this is the same issue but...

I made a custom ROS service where one of the fields is a uint8_t array. If I call and display the whole service response message using rospy.loginfo in Python or use 'rosservice call' in the terminal, the array displays properly. However, if I try to use rospy.loginfo to just display the uint8_t array, it just shows up blank. Similarly, if I try to access an element in the array, Python doesn't seem to recognize it as a uint8_t type. It just gets mad about it not being the right type. For now, I've switched over to using int32_t as that seems to work, but as the data I'm working with will only have values from 0 - 255, I'd rather stick to the uint8_t type.

**Comment by dirk-thomas** [comment]
@swinterbotix your comment on a 6.5 years closed ticket won't get much attention. Either all your question on answers.ros.org or create a new ticket with sufficient context (your environment, exact steps, expected/actual behavior, etc.).

**Comment by swinterbotix** [comment]
@dirk-thomas,

I wasn't sure if I should create a new ticket since I saw this issue being referenced in 2017 as well. But I'll keep that in mind for future issues.

In any event, after looking at http://wiki.ros.org/msg, I saw that Python2 treats uint8 arrays as strings which was why my data wasn't showing up properly.
