### ISSUE TITLE
roslaunch does not accept a package name if a file with the same name exists in the current directory

### ISSUE THREAD

**Issue by meyerj** [ros/ros_comm#256]
Reproduce with:

```
roscreate-pkg roslaunch_test
cd roslaunch_test
mkdir bin
mkdir launch
touch bin/roslaunch_test
echo "<launch/>" > launch/example.launch
cd bin
roslaunch roslaunch_test example.launch
```

Error output:

```
Usage: roslaunch [options] [package] <filename> [arg_name:=value...]

roslaunch: error: The following input files do not exist: example.launch
```

Without the file in `bin/` or with another working directory roslaunch executes without errors (and exits immediately as there are no nodes).

I am using roslaunch 1.9.47 installed from the binary package repository in ROS hydro.

**Comment by dirk-thomas** [comment]
Can you please try the patch from pull request #269 and confirm that it fixes the issue for you?

**Comment by meyerj** [comment]
The patch works for me. Thanks, Dirk!

**Comment by LOKAKSHAI** [comment]
I'm getting this error


Usage: roslaunch [options] [package] <filename> [arg_name:=value...]
       roslaunch [options] <filename> [<filename>...] [arg_name:=value...]

If <filename> is a single dash ('-'), launch XML is read from standard input.

roslaunch: error: The following input files do not exist: rvizconfig

**Comment by careful111** [comment]
I'm also having this issue, did you solve it?
