### ISSUE TITLE
Need new macro: add_rosgtest()

### ISSUE THREAD

**Issue by hershwg** [ros/ros_comm#258]
There is a very common test scenario which in my opinion is not well supported.  A rostest in which the "test" node is an executable which uses gtest to do its testing.  We can't use the usual catkin_add_gtest() macro, because that would run the executable outside of rostest.  We can't _just_ use add_rostest(), because that would not build the executable.  So then we're left to read through gtest.cmake and try and figure out which parts of the 33-line macro and associated other content are relevant to building an executable with gtest but not running it.

What I would like is something like:

```
add_rosgtest(my_test my_test.cpp my_test.launch)
```

in which mytest.launch refers to the executable called my_test.

Could call it add_rostest_gtest() or add_gtest_rostest() or add_grostest() or even add_gtest_within_rostest()

Finally it would be great if somewhere on the internets this common case were at least documented.  This http://answers.ros.org/question/54075/how-does-rostest-work-with-catkin/ describes the basic problem but ignores the fact that the executable should probably have EXCLUDE_FROM_ALL set, needs `${GTEST_LIBRARIES}` linked, and needs various dependencies connected in order to build and run correctly.  (and possibly other things that I'm not aware of and doing wrong currently)

**Comment by adolfo-rt** [comment]
+1. Having good support for rostest + gtest is a must, especially because it was already supported in rosbuild and there are quite a few packages that rely on this.

**Comment by dirk-thomas** [comment]
This issue is not about _supporting_ this combination - you can already use it and many packages actually do. It is about syntactic sugar - making it easier to write.

Please give PR #260 a try and see if that fits your expectations.

**Comment by jack-oquin** [comment]
:+1:  Seems worthwhile to me.

I'll add documentation, based on how this gets resolved.
