### ISSUE TITLE
topic throttler does not working properly

### ISSUE THREAD

**Issue by jihoonl** [ros/ros_comm#26]
I tried to throttle image topic using topic_tool throttle and didn't work.

jihoonl@whoolala:/opt/ros/groovy/stacks/openni_launch/launch$ rosrun topic_tools throttle messages /camera/rgb/image_color 5

jihoonl@whoolala:/opt/ros/groovy/stacks/openni_launch/launch$ rostopic info /camera/rgb/image_color
Type: sensor_msgs/Image

Publishers: 
- /camera_nodelet_manager (http://whoolala:49640/)

Subscribers: 
- /image_color_throttle_1353303817772763152 (http://whoolala:36997/)
## jihoonl@whoolala:/opt/ros/groovy/stacks/openni_launch/launch$ rosnode info /image_color_throttle_1353303817772763152 

Node [/image_color_throttle_1353303817772763152]
Publications: 
- /rosout [rosgraph_msgs/Log]

Subscriptions: 
- /camera/rgb/image_color [sensor_msgs/Image]

Services: 
- /image_color_throttle_1353303817772763152/get_loggers
- /image_color_throttle_1353303817772763152/set_logger_level

contacting node http://whoolala:36997/ ...
Pid: 32139
Connections:
- topic: /rosout
  - to: /rosout
  - direction: outbound
  - transport: TCPROS
- topic: /camera/rgb/image_color
  - to: /camera_nodelet_manager (http://whoolala:49640/)
  - direction: inbound
  - transport: TCPROS

jihoonl@whoolala:/opt/ros/groovy/stacks/openni_launch/launch$

**Comment by LucidOne** [comment]
I can't tell if this is the same issue I am having with Fuerte. The android app is being started in the /turtlebot/applications name space and is looking for the throttled topic in the namespace

**Comment by jihoonl** [comment]
That would be different issue. Currently , some android app in fuerte would not work by my fault.  I made some changes in app interface files for new app manager and it broke the system. I will revert it back the commit to get it working again tomorrow.

I will test it in fuerte tomorrow and confirm you.

**Comment by jihoonl** [comment]
I confirmed that throttle works in fuerte.

So this issue is only for groovy.

**Comment by dirk-thomas** [comment]
topic_throttle seems to work fine for me (with the current Groovy packages). I tried the following:
`rostopic pub -r 10 /foo std_msgs/Int32 42`
`rosrun topic_tools throttle messages /foo 1`
`rostopic hz /foo` shows an average of 10 msg/s
`rostopic hz /foo_throttle` shows an average of 1 msg/s
Please try to reproduce the problem on your machine with this command sequence.

**Comment by jihoonl** [comment]
Yeah it was my mistake to set up the experiment. I think i made a mistake setting nodelet improper way.
It is working. Thank you Dirk
