### ISSUE TITLE
rostest: wiki pages lack catkin documentation

### ISSUE THREAD

**Issue by jack-oquin** [ros/ros_comm#261]
The [rostest](http://ros.org/wiki/rostest) wiki pages give rosbuild examples, but lack catkin documentation.

**Comment by dirk-thomas** [comment]
I have added the catkin-way of registering rostests in CMakeLists.tx files: http://ros.org/wiki/rostest/Writing

**Comment by dirk-thomas** [comment]
I suppose the modifications are sufficient and close this ticket.
