### ISSUE TITLE
rospy nodes are hard to kill if master is not running

### ISSUE THREAD

**Issue by danepowell** [ros/ros_comm#262]
If you run a node before starting the master, you get the expected message:

```
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
```

However, it doesn't respond to Ctrl-C or kill commands. The only way to stop it is to find the pid and use kill -9.

**Comment by dirk-thomas** [comment]
Could you please mention for which ROS distro you experience?

When I run `rosrun rospy_tutorials talker.py` on Groovy I get the expected message but Ctrl+C works perfectly fine for me there. Can you post which specific node you run which is not abortable?

**Comment by danepowell** [comment]
Sorry, I'm on groovy. And I can confirm that talker.py works as expected. But I was using the visualization_tutorials, i.e. `rosrun interactive_marker_tutorials basic_controls.py`, and it can't be killed. Oddly, even if I wrap `rospy.init_node("basic_controls")` in a try / except, no exception gets thrown. I suspect I'm just missing something here...

**Comment by danepowell** [comment]
A better example - notice that although talker.py behaves as expected, listener.py does not.

**Comment by dirk-thomas** [comment]
Can you please try the branch from pull request #264 and check if it works for you?

**Comment by danepowell** [comment]
Sorry for the delayed response, I was out of town- but yes it works great. Thanks!
