### ISSUE TITLE
rosparam set/get do not check naming conventions

### ISSUE THREAD

**Issue by tkruse** [ros/ros_comm#266]
e.g.:

```
$ rosparam set x:! 42
$ rosparam get x:! 
42
```

Should error on forbidden keystrokes as early warning to users that their action will not have any effect on a ros node. See http://www.ros.org/wiki/Parameter%20Server

**Comment by dirk-thomas** [comment]
Yes, none of the ROS parameter API performs a check against the naming convention.

The problem with just adding this now is that there is a good chance that this will break existing code that does not conform to the naming convention. So just making it an error now is not really an option. We could output a warning and in the next cycle make it an error?

**Comment by tkruse** [comment]
Fair enough. In that case a note on ros-users would also not hurt.

**Comment by dirk-thomas** [comment]
I think that a message to ros-users is neither necessary nor appropriate. This has been the case in ROS forever and is not a recent change.

If you think a note is useful to users I would suggest adding a paragraph to the wiki page which states that rosparam does not check names against the naming conventions.

**Comment by tkruse** [comment]
Let's decide on the change first and worry about announcements later.

**Comment by dirk-thomas** [comment]
Imo their is no need to change the behavior. Even a warning seems to be not necessary since nothing bad i going to happen - you can just use whatever string you want for the param key. A note in the wiki page is indeed a good idea.

If nobody will propose a different strategy I will go ahead adding the note and closing this ticket.

**Comment by tfoote** [comment]
A note in the docs is good.  But it should be to the effect.  "The naming conventions are not enforced at the moment.  However in the future they may be so you should follow them." So as not to implicitly expand the spec.

**Comment by tkruse** [comment]
Fine with me.

**Comment by dirk-thomas** [comment]
Done: http://www.ros.org/wiki/Parameter%20Server?action=diff&rev2=38&rev1=37
