### ISSUE TITLE
Change from Boost::signal to Boost::signals2::signal

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#267]
In newer versions of Boost Boost.Signal has been deprecated.  

William identified it here: https://github.com/ros/geometry/issues/23

But in changing that I found that the underlying message_filter class exposes boost::signal in it's API.

**Comment by dirk-thomas** [comment]
Since this is an API breaking change it is not happening for Groovy/Hydro but earliest for Indigo.

**Comment by trainman419** [comment]
+1 to putting this into Indigo before boost removes it completely in a future version. This could affect compatibility with future versions of Ubuntu

Also +1 to any solution that makes the warning messages go away.

**Comment by dirk-thomas** [comment]
Done in #381.
