### ISSUE TITLE
Need to release new ros_comm 1.9.49 to Groovy 

### ISSUE THREAD

**Issue by davetcoleman** [ros/ros_comm#283]
A new gtest command in Hydro that is missing in Groovy is causing gazebo_ros_pkgs to fail building in Groovy, see:
http://answers.ros.org/question/76018/ros_controllers-package-catkin_make-error/

**Comment by dirk-thomas** [comment]
Please do not open a ticket for that - you already commented on one of the other tickets. And by the way ros_comm 1.9.49 was already released into Groovy yesterday (ros/rosdistro#2164).
