### ISSUE TITLE
setup.py uses invalid param install_requires

### ISSUE THREAD

**Issue by tkruse** [ros/ros_comm#29]
for distutils, should be just 'requires' instead.

Causes:

```
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
```

  warnings.warn(msg)

on makeinstall of groovy underlay. Here is a list of all setup.py files in groovy underlay

./ros_comm/tools/rostest/setup.py
./ros_comm/tools/rosgraph/setup.py
./ros_comm/tools/rosbag/setup.py
./ros_comm/tools/rosmaster/setup.py
./ros_comm/tools/rostopic/setup.py
./ros_comm/tools/rosnode/setup.py
./ros_comm/tools/roslaunch/setup.py
./ros_comm/tools/rosservice/setup.py
./ros_comm/tools/rosmsg/setup.py
./ros_comm/tools/rosparam/setup.py
./ros_comm/clients/rospy/setup.py
./ros_comm/utilities/roswtf/setup.py
./ros_comm/utilities/message_filters/setup.py
./diagnostics/diagnostic_common_diagnostics/setup.py
./gencpp/setup.py
./ros/core/roslib/setup.py
./ros/tools/rosmake/setup.py
./ros/tools/rosunit/setup.py
./ros/tools/rosclean/setup.py
./ros/tools/roscreate/setup.py
./genlisp/setup.py
./actionlib/setup.py
./genpy/setup.py

some are outside ros_comm, maybe you can fix those without a ticket each?

**Comment by dirk-thomas** [comment]
Fixed for the above list except `diagnostics/diagnostic_common_diagnostics`. Can you point me to the right repo for that?
Also fixed it for `dynamic_reconfigure` and `rxbag`.

**Comment by tkruse** [comment]
https://github.com/ros/diagnostics/tree/groovy-devel
note the package does not exist in master branch

**Comment by dirk-thomas** [comment]
fixed `diagnostics/diagnostic_common_diagnostics` https://github.com/ros/diagnostics/commit/b3c2e9477eaa5b3cdd7e1136219346c117d44b3b
