### ISSUE TITLE
rosbag migration does not work for messages outside of catkin

### ISSUE THREAD

**Issue by kwatts** [ros/ros_comm#293]
I noticed that rosbag "migration.py" does not work for messages outside of catkin.

Specifically, this is because the "genpy" module does not load message classes unless the message class is loaded in "/opt/ros/groovy/lib/python-2.7". After calling "roslib.load_manifest" for the package, the message will be loaded.

Example (using JoQ's "ackermann_msgs" package, but you get the idea):

``` python
import genpy

# Loading std_msgs is no problem
hdr_cls = genpy.message.get_message_class("std_msgs/Header")

# Returns None for valid message instance
returns_none = genpy.message.get_message_class("ackermann_msgs/AckermannDrive")

# load_manifest, then it will actually work
import roslib; roslib.load_manifest("ackermann_msgs")
ackermann_cls = genpy.message.get_message_class("ackermann_msgs/AckermannDrive")
```

This is easy to duplicate using any ROS message that exists outside of "/opt/ros/groovy/lib". 

Because rosbag's "migration.py" system uses this method of generating message classes, bag migration will not work for any message that is not installed.

**Comment by kwatts** [comment]
Example line where this is used in migration.py:

https://github.com/ros/ros_comm/blob/groovy-devel/tools/rosbag/src/rosbag/migration.py#L639

**Comment by dirk-thomas** [comment]
_migration.py_ will have to check the type of the package and invoke `roslib.load_manifest()` for dry packages.

Can you please attach an example migration rule and the command sequence which you used? That will make it easier to get this fixed.

**Comment by kwatts** [comment]
I created a simple test package that demonstrates this problem:
https://github.com/kwatts/ros_comm/blob/groovy-devel/migration_msgs.tgz
(github does not allow file attachments in issues, wtf)

Details
- Package contains a simple message, which has an "old" and "new" version in the "msg/" directory
- "old_message.bag" is a bag recorded with a single old message
- "migration_msgs.saved" is a saved copy of the old message 
- "migration_rules/migration_msg.bmr" is a ''Bag Migration Rule'' file that should allow you to migrate messages

To duplicate:

``` bash
rosmake migration_msgs

# Try to make a bag migration rule
rosrun rosbag makerule.py migration_msgs.saved test_bmr_file.bmr -n
# This fails because of the same problem with genpy message loading

# Use the working bag migration rule to migrate the bag file
rosrun rosbag fixbag.py old_message.bag new_message.bag migration_rules/migration_msg.bmr -n
# Fails because of genpy message problem
```

I used the "-n" option to for both rosbag tools (no plugins) because it will reduce problems to look at. It doesn't prevent any problems.
