### ISSUE TITLE
roslaunch: Add arg description

### ISSUE THREAD

**Issue by liborw** [ros/ros_comm#294]
It would be nice to have a simple description attached to the launchfile args so that the `roslaunch --ros-args` would print something more descriptive.

**Comment by tlind** [comment]
+1

**Comment by jbohren** [comment]
Possible implementation plan for arguments in a top-level launchfile:

---

Modify [`XmlLoader::_arg_tag`](https://github.com/ros/ros_comm/blob/indigo-devel/tools/roslaunch/src/roslaunch/xmlloader.py#L257) to add an optional "description" attribute.

Modify [`ContextLoader::add_arg`](https://github.com/ros/ros_comm/blob/indigo-devel/tools/roslaunch/src/roslaunch/loader.py#L212) to accept an optional "description" argument, and to store that description in the context. 

Update [`arg_dump.py`](https://github.com/ros/ros_comm/blob/indigo-devel/tools/roslaunch/src/roslaunch/arg_dump.py#L60) to output each argument's default value and documentation string.

---

**Comment by dirk-thomas** [comment]
That sounds like a good additional. Could someone please put together a pull request with this?

**Comment by jbohren** [comment]
Writing a PR now.

**Comment by jbohren** [comment]
PR submitted: https://github.com/ros/ros_comm/pull/379
