### ISSUE TITLE
Please add logexc function (for logging exception tracebacks)

### ISSUE THREAD

**Issue by RainCT** [ros/ros_comm#312]
Hi,

Python's logging module provides an exception() method which will log an error and print the full traceback. It'd be handy if this was also provided by rospy.

Have you considered adding it?

Best,

**Comment by dirk-thomas** [comment]
I don't see a need for _rospy_ to support this use case with specific functionality. You should be able to just pass a stacktrace yourself to the existing logging functions.

Does this work as you would like it to be:

```
import rospy
import traceback
rospy.logerr('My error message\n' + ''.join(traceback.format_stack()))
```

**Comment by RainCT** [comment]
Hi Dirk,

It does, but it's verbose for using it often, and given that rospy is actually using Python's logging module it seems weird that it's not available.

Anyway, feel free to close this if you disagree.

**Comment by dirk-thomas** [comment]
We don't intend to implement this feature since it can be achieved with minimal code in user land. Therefore I will mark this issue as _wontfix_.

If you think the feature is valuable please feel free to provide a PR to implement it.

**Comment by skycoop** [comment]
Just in case anyone else finds this issue and wants an easier solution than formatting the exception by hand, you can actually pass `exc_info=True` to any `rospy` logging method and it will add the formatted exception to the log message :slightly_smiling_face:

**Comment by gonzalocasas** [comment]
The documentation is definitely lacking on this one. There's no mention of `exc_info` on http://wiki.ros.org/rospy/Overview/Logging
