### ISSUE TITLE
roscpp depends on nonexistant 0.3.17 version of cpp_common

### ISSUE THREAD

**Issue by acornacorn** [ros/ros_comm#317]
Roscpp seems to depend on version 0.3.17 of cpp_common and roscpp_traits:

https://github.com/ros/ros_comm/blob/hydro-devel/clients/roscpp/package.xml

but the latest (hydro-devel) cpp_common is version 0.3.16:

https://github.com/ros/roscpp_core/blob/hydro-devel/cpp_common/package.xml

Does 0.3.16 exist?

**Comment by dirk-thomas** [comment]
The not yet released version of the roscpp package in this repo depends on the not yet released packages of the roscpp_core repo. So once this repo is released it makes sure that roscpp_core has also been released (hence why the package.xml already states a dependency on a not yet available version number).

If you want to build ros_comm from source make sure to also checkout roscpp_core.
