### ISSUE TITLE
rosmaster doesn't fully clean up closed sockets (Groovy)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#325]
When nodelets shutdown the rosmaster doesn't cleanup all it's sockets correctly. 

You can simply verify that problem by launching nodelet_tutorial_math.

```
$ lsof -nl | grep rosmaster | grep -c CLOSE_WAIT
=> 0
$ roslaunch nodelet_tutorial_math plus.launch
Ctrl-C
$ lsof -nl | grep rosmaster | grep -c CLOSE_WAIT
=> 4
```

Repeated running and stopping of a nodelet causes the count of CLOSE_WAIT sockets to increase.

Originally filed https://github.com/ros/nodelet_core/issues/10
Marking as minor and untargeted.

**Comment by dirk-thomas** [comment]
@garaemon FYI

This affects _Groovy_ only. In _Hydro_ the problem has already been fixed.

Since the necessary changes are not likely to be backported you might want to consider upgrading to _Hydro_.

**Comment by garaemon** [comment]
I think this problem still exists on the latest hydro

**Comment by dirk-thomas** [comment]
Please see #610 which might describe your issue.

**Comment by garaemon** [comment]
I will check it out

2015年5月5日火曜日、Dirk Thomasnotifications@github.comさんは書きました:

> Please see #610 https://github.com/ros/ros_comm/issues/610 which might
> describe your issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros/ros_comm/issues/325#issuecomment-98814702.

## 

✉︎ from iPhone
