### ISSUE TITLE
roslaunch dependency check test looks in manifest.xml for dependency

### ISSUE THREAD

**Issue by shaun-edwards** [ros/ros_comm#332]
The `roslaunch_add_file_check` macro complains about missing dependency in manifest.xml file.  It's not clear if the script is looking for the manifest.xml file (in which case it would fail under catkin) or if the dependency is truly missing (which I don't think it is).

The following steps reproduce the problem:
1. Clone the repo:
   `git clone https://github.com/shaun-edwards/industrial_core.git`
   `git checkout rosi_issue_11_launch_test`
2. Make/run the tests:
   `catkin_make run_tests_industrial_robot_simulator`

Resulting output:

```
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/ros/ros/release/build/test_results/industrial_robot_simulator
  /opt/ros/hydro/share/roslaunch/cmake/../scripts/roslaunch-check -o /home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml /home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch 
checking *.launch in directory /home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch
checking /home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch/robot_interface_simulator.launch
...writing test results to /home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml
FAILURE:
[/home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch/robot_interface_simulator.launch]:
    Missing manifest dependencies: industrial_robot_simulator/manifest.xml: industrial_robot_client
wrote test file to [/home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml]
-- run_tests.py: verify result "/home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml"
```

The test was added to CMakeLists.txt:

```
<snip>
find_package(roslaunch)
roslaunch_add_file_check(launch)
<snip>
```

The package xml has the following depends:

```
<build_depend>industrial_robot_client</build_depend>
<run_depend>industrial_robot_client</run_depend>
```

This appears to be a bug in the roslaunch test macros.

**Comment by gavanderhoorn** [comment]
Seems adding a dummy `manifest.xml` to `industrial_robot_simulator` containing just:

```
<package>
  <depend package="industrial_robot_client" />
</package>
```

makes the test pass.

**Comment by dirk-thomas** [comment]
The problem is that the dependency (industrial_robot_client) is not released and rospkg is unable to resolve that since it is only barely aware of wet stuff. #333 explicitly falls back to catkin_pkg to resolve the actual run dependencies.
