### ISSUE TITLE
Couldn't register C++ subscriber when using ros java master

### ISSUE THREAD

**Issue by tulku** [ros/ros_comm#335]
We noticed a small difference in the way the rosjava master and the roscpp master respond to `registerSubscriber` when no publisher on the same topic is present. This prevents the subscriber from registering correctly.

To reproduce we are using:
1. ros master (either roscore or rosjava master)
2. $ rostopic echo /rosout
3. $ rosrun  roscpp_tutorials listener

As there is no registered publisher of the `/chatter` topic, then the master reply has an empty field (the publisher list), where we found the difference. rosjava master uses an [empty tag](http://www.w3.org/TR/REC-xml/#NT-content) (`<data/>`) while roscore sends `<data></data>`. Both are valid XML expressions, and both should work.

@damonkohler, did you ever encountered this issue?

Trace of the registration to rosjava master (the reply was indented for clarity):

```
POST / HTTP/1.1
User-Agent: XMLRPC++ 0.7
Host: localhost:11311
Content-Type: text/xml
Content-length: 286

<?xml version="1.0"?>
<methodCall><methodName>registerSubscriber</methodName>
<params><param><value>/listener</value></param><param><value>/chatter</value></param><param><value>std_msgs/String</value></param><param><value>http://libelula:48303/</value></param></params></methodCall>


HTTP/1.1 200 OK
Server: Apache XML-RPC 1.0
Connection: close
Content-Type: text/xml
Content-Length: 230

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
 <param>
  <value>
   <array>
    <data>
     <value><i4>1</i4></value>
     <value>Success</value>
     <value><array><data/></array></value>
    </data>
   </array>
  </value>
 </param>
</params>
</methodResponse>
```

The listener node produces this out to /roscore (read by doing rostopic echo /rosout):

```
-- header: 
  seq: 0
  stamp: 
    secs: 1389372832
    nsecs: 723912679
  frame_id: ''
level: 4
name: /listener
msg: couldn't register subscriber on topic [/chatter]
file: /tmp/buildd/ros-hydro-roscpp-1.9.50-0precise-20131015-1959/src/libros/topic_manager.cpp
function: TopicManager::subscribe
line: 289
topics: ['/rosout']

---
```

The same trace using the roscore master:

```
POST / HTTP/1.1
User-Agent: XMLRPC++ 0.7
Host: localhost:11311
Content-Type: text/xml
Content-length: 286

<?xml version="1.0"?>
<methodCall><methodName>registerSubscriber</methodName>
<params><param><value>/listener</value></param><param><value>/chatter</value></param><param><value>std_msgs/String</value></param><param><value>http://libelula:51206/</value></param></params></methodCall>


HTTP/1.0 200 OK
Server: BaseHTTP/0.3 Python/2.7.3
Date: Fri, 10 Jan 2014 16:56:09 GMT
Content-type: text/xml
Content-length: 268

<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><array><data>
<value><int>1</int></value>
<value><string>Subscribed to [/chatter]</string></value>
<value><array><data>
</data></array></value>
</data></array></value>
</param>
</params>
</methodResponse>
```

When opening first the publisher and then the subscriber, the setup works with both masters. Next, you can find the trace corresponding to a rosjava master:

```
POST / HTTP/1.1
User-Agent: XMLRPC++ 0.7
Host: localhost:11311
Content-Type: text/xml
Content-length: 286

<?xml version="1.0"?>
<methodCall><methodName>registerSubscriber</methodName>
<params><param><value>/listener</value></param><param><value>/chatter</value></param><param><value>std_msgs/String</value></param><param><value>http://libelula:37162/</value></param></params></methodCall>
HTTP/1.1 200 OK
Server: Apache XML-RPC 1.0
Connection: close
Content-Type: text/xml
Content-Length: 273

<?xml version="1.0" encoding="UTF-8"?><methodResponse><params><param><value><array><data><value><i4>1</i4></value><value>Success</value><value><array><data><value>http://libelula:33011/</value></data></array></value></data></array></value></param></params></methodResponse>
```

**Comment by tulku** [comment]
We have just "hacked" the Apache Commons XML library to never create the empty tags and we don't see this error anymore.

We actually solved the problem in the following [question](http://answers.ros.org/question/86296/rosjava_core-turtlesim-compatibility-problems/) with this hack.

We will try to make a small test, just testing the xml library used in roscpp to reproduce this bug.

**Comment by tulku** [comment]
I'm cc @adamantivm who is also working on this issue.

**Comment by tulku** [comment]
@adamantivm pushed the hack to the Apache XML, and can be seen [here](https://github.com/adamantivm/rosjava_core/commit/f84db524fc19664b8d76e4f1eea9adc4db75a966#diff-7f6688704d761a4f5031746dfccae731R243)

**Comment by dirk-thomas** [comment]
In order to reproduce the problem (and confirm that any patch fixes the problem) I need to run the Java ROS core. But I could not find any documentation on it. Any pointers would be welcome.

**Comment by damonkohler** [comment]
There is no binary for it. You'll need to write a small Java binary. You
can invoke it like so:

RosCore rosCore = RosCore.newPublic(11311);
rosCore.start();
System.out.println(rosCore.getUri());

HTH,
Damon

On Wed, Jan 22, 2014 at 3:53 AM, Dirk Thomas notifications@github.comwrote:

> In order to reproduce the problem (and confirm that any patch fixes the
> problem) I need to run the Java ROS core. But I could not found any
> documentation on it. Any pointers would be welcome.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/ros_comm/issues/335#issuecomment-32989177
> .

## 

Damon Kohler

Google Germany GmbH
Dienerstr. 12, 80331 München

Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschäftsführer: Graham Law, Katherine Stephens

**Comment by adamantivm** [comment]
@dirk-thomas in case it helps, I pushed a sample master to the rosjava-master branch of in my rosjava_core fork: https://github.com/adamantivm/rosjava_core/tree/rosjava-master

I also prepared a self-contained "binary" which I hung from my Dropbox account here: https://www.dropbox.com/s/p7yn7v6jhrmd13d/rosjava-master.tgz

EDIT: The code for the master itself is here: https://github.com/adamantivm/rosjava_core/blob/rosjava-master/rosjava/src/main/java/com/c77/JavaRosCore.java

**Comment by dirk-thomas** [comment]
`roscpp` does currently not accept a response if the third argument is missing (which is specified as being optional in the spec: http://wiki.ros.org/ROS/Master_API#line-64). The pull request #339 should address the problem.

Can you please confirm that it also works for you when building the version from the pull request branch from source?

**Comment by adamantivm** [comment]
@dirk-thomas just to be sure, the problem here is not that rosjava is sending a response with the third argument missing, but rather it is encoded as an abbreviated data element.

In other words, the Apache XML serializer is writing

```
<value><array><data/></array></value>
```

instead of 

```
<value><array><data></data></array></value>
```

or an empty parameter.

Does this PR still apply in this case?

**Comment by dirk-thomas** [comment]
It fixed the issue described in this ticket for me. I might be related to how XmlRpc++ does the parsing of the response. Please give it a try.

**Comment by adamantivm** [comment]
Ok, thanks @dirk-thomas, we'll give it a spin and report.

On Wed, Jan 22, 2014 at 5:05 PM, Dirk Thomas notifications@github.comwrote:

> It fixed the issue described in this ticket for me. I might be related to
> how XmlRpc++ does the parsing of the response. Please give it a try.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/ros_comm/issues/335#issuecomment-33061697
> .

## 

-- Julian Cerruti

**Comment by adamantivm** [comment]
@dirk-thomas I can confirm this fixes the issue for this test case. Thanks!
