### ISSUE TITLE
Missing function: createAdvertiseOptions

### ISSUE THREAD

**Issue by kohrt** [ros/ros_comm#338]
Hi,

after I updated ROS the compiler complained about an missing function.

ros::AdvertiseOptions createAdvertiseOptions(const ConnectionInfo *c, uint32_t queue_size)

After the refactoring in commit e73774f6696892b643be7e71421c375e74401e2b the implementation moved tools/rosbag/src/player.cpp. But there is no definition in the corresponding header file.

Best regards,
Thiemo

**Comment by dirk-thomas** [comment]
This is indeed a regression of #299. Thanks for pointing it out.

Can you please confirm that my recent commit fixes the problem for you and comment on this ticket? Just checkout this repository into your workspace should make it work again.

**Comment by kohrt** [comment]
Yes, this should fix it! Thanks
