### ISSUE TITLE
Nodelets not working when setting IPs in ROS_IP/ROS_HOSTNAME

### ISSUE THREAD

**Issue by bit-pirate** [ros/ros_comm#34]
When setting an IP in ROS_IP/ROS_HOSTNAME, roslaunch gets stuck at waiting for the nodelet manager's "load nodelet" service.

Everything is smooth, when using names or when using an IP address _only_ in ROS_MASTER_URI.

**Comment by bit-pirate** [comment]
Might be due to the same bug described here: #35

**Comment by dirk-thomas** [comment]
Likely fixed with #35.
