### ISSUE TITLE
Incorrect warning on advertise of std_mgs/Empty

### ISSUE THREAD

**Issue by davetcoleman** [ros/ros_comm#344]
From [ROS Answers](http://answers.ros.org/question/121971/warning-on-advertise-of-std_mgsempty/):

"Recently (maybe since some update...), whenever I advertise a topic of topic std_msgs/Empty I receive WARNING:"

> Advertising on topic [/topic_name] with an empty message definition. Some tools (e.g. rosbag) may not work correctly.

This seems to be a bug in `clients/roscpp/src/libros/topic_manager.cpp:327`

**Comment by dirk-thomas** [comment]
The regression is actually in `gencpp`: ros/gencpp@82b5116f405dddbe8885fc8921deb021cf1dd977
I created a patch to fix the problem: ros/gencpp#14
