### ISSUE TITLE
roscpp subscribers don't connect properly when using ROS_IP/ROS_HOSTNAME

### ISSUE THREAD

**Issue by ahendrix** [ros/ros_comm#35]
This issue has come up a few times on the ROS-Release mailing list. I've come up with good instructions on how to reproduce it. It only appears to be a problem with roscpp subscribers; rospy subscribers are unaffected, and setups which don't use ROS_IP or ROS_HOSTNAME on the publisher are also unaffected.

To reproduce this, you must have two machines on a network; it doesn't seem to reproduce when all nodes are run on the same machine.

Steps to reproduce:
On machine 1, start a roscore
On machine 1, set ROS_IP and rosrun roscpp_tutorials talker
On machine 2, set the ROS_MASTER_URI to machine 1
On machine 2, rosrun roscpp_tutorials listener
On machine 2, rosrun rospy_tutorials listener

Observed results:
the rospy listener receives messages correctly; the roscpp listener does not

Expected results:
both listeners receive messages correctly.

**Comment by hershwg** [comment]
I am suspicious of this commit: https://github.com/ros/ros_comm/commit/8f6063025665b87e6de73f1f3c1e100f747eff78
which adds IPv6 support, but I haven't tested the 'before' version yet.

**Comment by ahendrix** [comment]
Something else of note:
With the roscpp nodes running in this setup, rosnode info /talker doesn't show any outgoing connections, but rosnode info /listener indicates that it's connected.

I would guess that this means that the subscriber is receiving the list of publishers properly, but isn't setting up the TCP connection for the topic.

**Comment by hershwg** [comment]
I have just confirmed that this bug exists in 1.9.34 but does not exist in 1.9.32.

**Comment by bit-pirate** [comment]
Please let me know me, when you guys have a new version out for testing!

**Comment by schneider42** [comment]
I'll have a look into it.

**Comment by dirk-thomas** [comment]
I am currently looking at the code. It is definitely an issue in the modified code of `TransportTCP::connect()`.

A simple scenario to reproduce is:
- three shells A, B and C
- A and B which normal ROS groovy environment
- C with ROS_IP set to the ip of the machine
- A: `roscore`
- C: `rosrun ros(cpp|py)_tutorials talker`
- B: `rosrun roscpp_tutorials listener`

B is not receiving any messages from C.

**Comment by schneider42** [comment]
Thanks for fixing it. I obviously misused the inet_pton function there.
