### ISSUE TITLE
Time being zero in simulation

### ISSUE THREAD

**Issue by RainCT** [ros/ros_comm#354]
Hi,

The fact that time is initially zero in simulation is quite annoying, I've seen several bugs related to it (both in ROS and in our own code).

Not sure if it'd make sense to have init_node() wait until it receives a valid time, but if not it'd be useful to at least have some wait_for_time() function available.

**Comment by trainman419** [comment]
The ros::Time class already has [`ros::Time::waitForValid()`](http://docs.ros.org/indigo/api/rostime/html/classros_1_1Time.html#ab61825bb028f8c10c5e94aeca32bbfda) which waits for the ROS clock to become valid - no sim time or nonzero sim time.

Does this address your use case?

**Comment by dirk-thomas** [comment]
I am closing this due to lack of feedback. Please feel free to comment and the ticket can be reopened.
