### ISSUE TITLE
Linker error due to missing symbols from rostime

### ISSUE THREAD

**Issue by meyerj** [ros/ros_comm#36]
Compiiing a dry package that depends on rosbag only currently fails in ROS fuerte (installed from the Ubuntu repositories), as rosbag does not depend on package rostime or imports the rostime linker flags via the pkgconfig call:

Linking CXX executable ../bin/frame_id_adder
/usr/bin/cmake -E cmake_link_script CMakeFiles/frame_id_adder.dir/link.txt --verbose=1
/usr/lib/ccache/c++   -m64  -O2 -g     -pthread CMakeFiles/frame_id_adder.dir/src/frame_id_adder.o  -o ../bin/frame_id_adder -rdynamic -L/opt/ros/fuerte/lib -lrosbag -Wl,-rpath,/opt/ros/fuerte/lib 
/usr/bin/ld: CMakeFiles/frame_id_adder.dir/src/frame_id_adder.o: undefined reference to symbol 'ros::TIME_MIN'
/usr/bin/ld: note: 'ros::TIME_MIN' is defined in DSO /opt/ros/fuerte/lib/librostime.so so try adding it to the linker command line
/opt/ros/fuerte/lib/librostime.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status

**Comment by meyerj** [comment]
Okay, there are some more unresolved symbols from roscpp_serialization and roscpp_traits. Seems that I have to add roscpp as a dependency in the manifest to compile my package successfully, even though I do not want to create a node, subscribers, publishers...

**Comment by dirk-thomas** [comment]
Fixed in f6956b8f5315270fa21312ef8c6b0cd4a56b5e1a
