### ISSUE TITLE
no description about `subst_value` attribute in roslaunch wiki

### ISSUE THREAD

**Issue by jihoonl** [ros/ros_comm#368]
`subst_value` which is one of attribute in rosparam tag is not described in ros wiki.

https://github.com/ros/ros_comm/blob/indigo-devel/tools/roslaunch/src/roslaunch/xmlloader.py#L199

**Comment by dirk-thomas** [comment]
The feature was added in #218.

@jihoonl Please mention the wiki page where you were looking for the rosparam tag. Was it http://wiki.ros.org/roslaunch/XML/rosparam ?

@stonier Could you please add a short description of the added attribute to the wiki page?

**Comment by jihoonl** [comment]
Yes http://wiki.ros.org/roslaunch/XML/rosparam is the page I looked for.

**Comment by stonier** [comment]
Done.

**Comment by dirk-thomas** [comment]
Thank you!
