### ISSUE TITLE
Check licensing on ifaddrs.py in rosgraph

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#37]
https://github.com/ros/ros_comm/blob/master/tools/rosgraph/src/rosgraph/ifaddrs.py

apparent source:
http://carnivore.it/2010/07/22/python_-_getifaddrs

**Comment by schneider42** [comment]
I'll ask the author if he want to license it under BSD. If necessary I'll reimplement the file.

**Comment by dirk-thomas** [comment]
Any news on this? Else we should reimplement it...

**Comment by schneider42** [comment]
I've asked the author directly, but had no response. I'll try again on his blog, and reimplement it over the weekend if nothing happens.

**Comment by schneider42** [comment]
I've added a pull request for this issue: https://github.com/ros/ros_comm/pull/130

**Comment by dirk-thomas** [comment]
That file has been removed and replaced with an existing Python module.
