### ISSUE TITLE
rostopic bw confusing results

### ISSUE THREAD

**Issue by dawonn** [ros/ros_comm#370]
$ rostopic bw /camera/image 

subscribed to [/camera/image]
average: 32.48MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 8
average: 31.06MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 16
average: 30.62MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 24
average: 30.40MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 32
average: 30.27MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 40
average: 30.19MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 48
average: 30.13MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 56
average: 30.08MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 64
average: 30.05MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 72
average: 30.02MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 80
average: 30.00MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 88
average: 29.98MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 96
average: 29.96MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 100
average: 29.96MB/s
    mean: 3.72MB min: 3.72MB max: 3.72MB window: 100

**Comment by dirk-thomas** [comment]
Can you please desribe what you find confusing about the output?

**Comment by dawonn** [comment]
the average is 30MB/s and the mean min and max are all 3.72MB.

Perhaps those are not the mean, min, and max of the _bandwidth_ but the actual message sizes?

**Comment by dirk-thomas** [comment]
The first line is the *average bandwidth in MB per second.

The second line is per message information: _mean / min / max message sizes_ and the _window_ used for that. Therefore it says _MB_ instead of _MB/s_ which would be bandwidth.

**Comment by dawonn** [comment]
I suppose that makes sense now.
