### ISSUE TITLE
Using queue_size in a rospy publisher causes slowdown when there are multiple subscribers

### ISSUE THREAD

**Issue by jonbinney** [ros/ros_comm#373]
When a rospy publisher uses a queue_size, if there are multiple subscribers (more than 2), I see lots of dropped messages. This happens even when the messages are small, and the CPU load is nowhere near maxed. It happens even if the queue_size is very large.  To reproduce, use this `pub` script:

``` python
#!/usr/bin/env python
import rospy
import sys
from std_msgs.msg import String

pub_rate = int(sys.argv[1])
queue_size = None
if len(sys.argv) > 2:
    queue_size = int(sys.argv[2])

rospy.init_node('pub', anonymous=True)
pub = rospy.Publisher('foo', String, queue_size = queue_size)

r = rospy.Rate(pub_rate)
while not rospy.is_shutdown():
    pub.publish(String('helloooooooo'))
    r.sleep()
```

In one terminal, do `./pub 150 1000` to publish messages at 150 Hz on topic "foo" with a queue_size of 1000. Then in open 3 or 4 other terminals and run `rostopic hz /foo -w200`. For each rostopic hz you add, the rate drops. On my computer, with 3 of them, I get 100-130 hz instead of 150hz.  Checking top shows only 12% CPU usage for the publisher node.

If you run the same experiment, but start the publisher with `./pub 150`, it will create the publisher without queue_size, and you should see all subscribers getting 150 hz.

Since the publisher doesn't seem to be CPU limited or network limited, I'm not sure what is going on. Maybe lock contention somewhere?

**Comment by jonbinney** [comment]
(i'm running this all on one machine, with everything talking to localhost)

**Comment by dirk-thomas** [comment]
This looks like bad locking / signaling strategy. Please try PR #374 which should address this issue.

@mikeferguson Since you were the user trying this feature can you please also try the referenced PR and confirm that it works for your use case (the same or likely even better then before)?

**Comment by mikeferguson** [comment]
@dirk-thomas I can test this, but I'm not sure if I will get to it today. Worst case, I will test over the weekend.
