### ISSUE TITLE
rostopic.get_topic_type returns wrong type

### ISSUE THREAD

**Issue by jihoonl** [ros/ros_comm#376]
The following issue describes it.

https://github.com/RobotWebTools/rosbridge_suite/issues/85#issuecomment-37260395

**Comment by dirk-thomas** [comment]
I tried the following sequence (all in separate shells) based on the referenced ticket:

```
rostopic pub /ns/string std_msgs/String "str"
rostopic pub /ns/string/int std_msgs/Int16 5
rostopic list
rostopic echo /ns/string
rostopic echo /ns/string/int
rostopic type /ns/string
rostopic type /ns/string/int
```

All of the commands return the correct values (the data and types of that specific publisher).

Please clarify what exact sequence of commands (preferably just `rostopic`) you are running, what results you get and what you expect.

**Comment by jihoonl** [comment]
I was testing by the following

```
rostopic type /should_be_string   # expected to be unknown type
rostopic pub /should_be_string std_msgs/String "str"
rostopic type /should_be_string  # expected to be std_msgs/String

rostopic type /should_be_string/should_be_int # expected to be unknown type but returned std_msgs/String
```

My expected output from the last code was unknown topic since it is unpublished yet. To be specific, I expected `rostopic.get_topic_type` to return (None, None, None). However, it returns the type of its namespace instead. 

So I was wondering if it is expected behavior. And if it is desired behavior, I wondered if you have any suggestion to detect the presence of `topic` as well as its type.

`rostopic.get_topic_type` is used to detect the topic presence and its type in rosbridge in the following code. What the code does is that it checks the presence of topic and sets up a publisher when it received `publish()` request from rosbridge client.

https://github.com/RobotWebTools/rosbridge_suite/blob/hydro-devel/rosbridge_library/src/rosbridge_library/internal/publishers.py#L125-L160

So far, we found the workaround solution suggested by @garaemon in https://github.com/RobotWebTools/rosbridge_suite/issues/85#issuecomment-37260827, which is checking whether the third return value of `rostopic.get_topic_type` is presented or not.

I would like to know if there is more efficient way to achieve this.

**Comment by dirk-thomas** [comment]
Yes, that is currently the expected behavior which is also documented like this in the API: https://github.com/ros/ros_comm/blob/indigo-devel/tools/rostopic/src/rostopic/__init__.py#L320

The problem is that `rostopic` uses the same separator (`/`) withing the topic name as for separating the field inside the topic. E.g. the following works with rostopic:

```
rostopic type /should_be_string/data  # expected to be std_msgs/String since it assumes that "data" is a field inside the message
rostopic echo /should_be_string/data  # only outputs the data field of the messages
rostopic type /should_be_string/field_does_not_exist  # also returns std_msgs/String since it still assumes that "field_does_not_exist" is a field inside the message
```

`rostopic` can not look ahead into the message type and check if the suffix is actually a valid field or not. Simply because it might not even have the message definition.

This could only be addressed if `rostopic` would use a different separator for the field name inside of a topic. Until then checking the third return value is the way to go.

**Comment by dirk-thomas** [comment]
Actually I came up with a PR (#378) which at least checks if the potential messages types are known and checks if the fields actually exist. This would at least cover the cases where the system knows the message type and allows to reject non-existing field suffixes.

Please give it a try with the branch and provide feedback if that would be valuable for your use case.

**Comment by jihoonl** [comment]
Thanks. I will give it a try and reply.

**Comment by jihoonl** [comment]
It solved the issue that we have found :)  Thanks @dirk-thomas!
