### ISSUE TITLE
message_filters.Subscriber

### ISSUE THREAD

**Issue by schlichtanders** [ros/ros_comm#380]
`message_filters.Subscriber` in python doesn't support either `.unregister()` as rospy.Subscriber or `.unsubscribe()` as it is implemented in the cpp variant.

**Comment by dirk-thomas** [comment]
A `message_filters.Subscriber` has a public member variable `pub` which stores a rospy publisher. You might just want to invoke `unsubscribe()` on that?

```
message_filters_subscriber.sub.unsubscribe()
```

**Comment by schlichtanders** [comment]
Thank you very much for the fast response.
I guess you mean `message_filters_subscriber.sub.unregister()` and yes this
is what I searched for.

Thanks

**Comment by tfoote** [comment]
I think this is resolved. Closing. Please comment if not and we can reopen.
