### ISSUE TITLE
Serialize directly to provided stream

### ISSUE THREAD

**Issue by GasparPizarro** [ros/ros_comm#388]
I would be nice to have a serialization method that makes an array of bytes directly instead of needing a buffer, like pickle (I've tried pickle.dumps on a message and it adds much more data than the message's fields).

**Comment by dirk-thomas** [comment]
Can you please provide more information what exactly you want to achieve? Should the string contain also the field names or only the values with some kind of separator?

**Comment by GasparPizarro** [comment]
What I'm trying to do is to take a message, and use the serialize method to make a array of bytes (or a string) out of it. Let's say I have this message:

Point:
   uint16 x
   uint8 y

and an instance (x=257, y=50)

I want to use the serialize method to have a list of bytes like this: [1, 1, 50]. The first two bytes are the x field and the third one is the y field, and nothing else (no field names or anything). Currently the serialize method does exactly this (maybe there are some endianness issues, but they're not relevant for this enhancement), but the method is intended to be used to write in a file or send through a network, so that it requires a buffer, so in order to get a string out of the message, I have to pass a StringIO.StringIO instance, and then extract the value of the StringIO.StringIO instance. Instead of requiring a buffer, It would be nice to be able to take the string (array of bytes) directly.

I want to do this because I need an array of bytes out of a message, but I have to do some postprocessing to the string (put some headers) before sending it through a network.

Think about the ndarray.tostring method of the numpy library. That is what I'm thinking about.

http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tostring.html

**Comment by dirk-thomas** [comment]
The `serialize` function of a message takes a `buffer` argument. For each field the data is written to that buffer using its `write` method.

You could pass in a StringIO instance and afterwards read the content of your StringIO instance. But you could also pass in an arbitrary other object which provides a `write` method and do any custom logic in there.

I think I don't understand what exactly you would like to have added. The API seems to be flexible enough to suit your needs.

A `tostring()` method on a message would just do exactly the same:

```
def tostring(self):
    s = StringIO()
    self.serialize(s)
    return s.getvalue()
```

**Comment by GasparPizarro** [comment]
Exactly, I am doing exactly that workaround in my code. But my point is that traditional serialization methods (like in pickle or numpy) make strings directly out of the objects (messages in this case) and then you can decide if you want to print it, store in a file, send it through a network, etc. I think that approach is better than assuming that the serialization method is going to be used to do "write" stuff.

I mean, I don't want to "force" to be the way I propose, but it would be nice to have the option in the method itself to make strings.

**Comment by dirk-thomas** [comment]
Having a `tostring` function enforces you to always copy the data before you write them somewhere else, e.g. into a file. The approach to use the `write` function of the passed in `buffer` object allows you to directly pass the data along and is therefore the more flexible way API. Especially for handling message data it is crucial to avoid any unnecessary copy for performance reasons.

I don't think that it makes sense to add a `tostring` function to messages which does what I sketched above. Especially since the binary data are not really of any use in common scenarios.

I would suggest that you perform these three lines in your code base rather then adding it to the message API.

**Comment by GasparPizarro** [comment]
"The approach to use the write function of the passed in buffer object allows you to directly pass the data along and is therefore the more flexible way API."

I must disagree with that. In the ros-generated code (Ros Hydro, on Ubuntu 12.04, 64 bits) there is this:

```
def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3fB3f2B.pack(_x.start.acceleration, _x.start.velocity, _x.start.position, _x.start.command_id, _x.end.acceleration, _x.end.velocity, _x.end.position, _x.end.command_id, _x.axis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))
```

(catkin_ws/devel/lib/python2.7/dist-packages/my_package/srv)

As you can see, the way to do serialization is, first of all, to get a string out of the message, _then_ write it to the buffer. So, a more flexible way to serialize the string would to just take the result of 

```
_struct_3fB3f2B.pack(_x.start.acceleration, _x.start.velocity, _x.start.position, _x.start.command_id, _x.end.acceleration, _x.end.velocity, _x.end.position, _x.end.command_id, _x.axis)
```

and do whatever you want with it, in any case, you are creating a string.

(Btw, thanks for the attention. I didn't think the ROS community was open to suggestions)

**Comment by tfoote** [comment]
The API design with passing in the buffer is more flexible as it makes it possible to use or reuse preallocated buffers. If the API provided return by value it would prevent leveraging the preallocated buffers.  

We do not want to maintain two sets of parallel APIs especially in the generated code as any more complexity at this level propagates a long way. We need to make sure that this core stays very stable as a lot of people build on top of it. 

As adding the return by value method would save only two lines of user code in an uncommon use case it is hard to justify changing or modifying the core API of the message datatypes where we strive for high stability. 

As mentioned the current implementation does not take full advantage of the power available in the API. However, it could be optimized in the future and use the full power of the API and not generate an intermediate copy.

**Comment by GasparPizarro** [comment]
Ok, understood. Thanks for the attention.
