### ISSUE TITLE
Release into hydro

### ISSUE THREAD

**Issue by jonbinney** [ros/ros_comm#392]
@dirk-thomas can you do another release into hydro? The asynchronous publishing performance fix (https://github.com/ros/ros_comm/commit/f577021a701163951e3ee42e0136535f0659060e) has been merged for a while but not released.

**Comment by dirk-thomas** [comment]
Another release will likely happen soon but depends on several other packages to be released at the same time to justify the effort on the farm to rebuild nearly everything and also every user to download all packages again.

In the future please ask on the specific issue / pull request for a release and avoid opening a new ticket for it.
