### ISSUE TITLE
rosconsole enhancement: rosconsole should read env variable

### ISSUE THREAD

**Issue by catskul** [ros/ros_comm#394]
User story:

Rorry the ros user would like to set the debug level without spending the time to create a temporary `log4j` config file and cluttering the file system with said temporary.

We should allow setting of the log levels either as an env var or as a command line switch to `roslaunch` and `rosrun`

```
export log4j_logger_ros=DEBUG
```

or something like

```
roslaunch my_pkg system.launch --set-log-level=ros:DEBUG 
```

**Comment by dirk-thomas** [comment]
Please consider contributing such a feature via a pull request. Since it is not likely that the maintainers have time to work on this feature I will mark it with the milestone "untargeted".

**Comment by catskul** [comment]
If the general idea appears to be acceptable, I would inclined to do so.

**Comment by dirk-thomas** [comment]
The feature is conceptionally problematic since the current logging API only allows two ways to configure the level:
- through the config file which is read at start up time
- through ROS service calls on a node, which can only be used after the node has been started.

Therefore I don't know how you would like to pass these information from roslaunch.

The first option requires temporary configuration files you would like to avoid and the second one would fail to apply the log level during the start up phase of the node which would be an incomplete solution.

Using environment variable like this is commonly considered to be not a good idea.

**Comment by catskul** [comment]
I can see the API problem, but I have to disagree on the idea that using an env variable is a bad idea for this type of setting, especially given the range of things ROS already does use env variables for.

Where I have the free time to do so, I'm inclined to attempt to produce a solution, but I'll probably not do so if the general feeling is that such a feature would be unlikely to be integrated. I generally don't live in the latest dev environment, so it would be a considerable investment for me to set up an environment where I could produce and test a patch that would be integratable with the latest.

As far as implementation is concerned, IMO, temporary config files would certainly be ok if their management was handled by the system itself rather than the user. The principle I'm working from is that frequently done things should be made as frictionless as possible, with the least burden on the user. The actual implementation is less important assuming it does not break expectation.

**Comment by dirk-thomas** [comment]
Environment variables provide zero discoverability compared to command line options.

It is always a good idea to sketch the design and put it out for discussion before spending significant time on the implementation. Especially for more difficult tasks like this. That way more people can contribute and give early feedback and the risk to spend time on an implementation which is not getting accepted is reduced.

E.g. I could imagine using command line options but behind the scene a custom config file is generated and being used by setting an environment variable (but the user does not see any of these). But that is just a rough idea - figuring out the details before committing to a lot of work would be good.

**Comment by catskul** [comment]
> Environment variables provide zero discoverability compared to command line options.

I don't necessarily disagree, but it seems that line was already crossed by having ROSCONSOLE_CONFIG_FILE and ROSCONSOLE_FORMAT as an env vars. For what it's worth, logging is one of the few accepted uses of singletons/global variables, so from that perspective we're in good company.

When I get a moment where I can spend a bit more time on it, I'll take a deeper look and draw up a proposal before doing any in depth work.

**Comment by dirk-thomas** [comment]
Arguing that one suboptimal decision in the past is enough to justify more similar decision in the future is not a good idea imo.

**Comment by dirk-thomas** [comment]
This issue was moved to ros/rosconsole#4
