### ISSUE TITLE
Groovy roscpp version not resolved in common.h

### ISSUE THREAD

**Issue by jack-oquin** [ros/ros_comm#40]
These lines in `<ros/common.h>` should be resolved to the actual roscpp version number.

```
#define ROS_VERSION_MAJOR roscpp_VERSION_MAJOR
#define ROS_VERSION_MINOR roscpp_VERSION_MINOR
#define ROS_VERSION_PATCH roscpp_VERSION_PATCH
```

That failure breaks any code using the ROS_VERSION_GE() or ROS_VERSION_MINIMUM() macros.

**Comment by tfoote** [comment]
There's a ticket closely related #15. Does that fix propagate into dry packages?

**Comment by jack-oquin** [comment]
roscpp should have a unit test case for something this fundamental

**Comment by tfoote** [comment]
There are already tests for this in roscpp. https://github.com/ros/ros_comm/blob/master/test/test_roscpp/test/test_version.cpp  However, they passed for all wet packages as the compile flags were set properly to define those variable at cmake time.
