### ISSUE TITLE
Rostopic pub doesn't set publisher queue_size in Indigo

### ISSUE THREAD

**Issue by chadrockey** [ros/ros_comm#417]
When you publish a topic using rostopic_pub, you get the rospy queue_size warning:

rostopic pub -r 10 /float std_msgs/Float64 100
/opt/ros/indigo/lib/python2.7/dist-packages/rostopic/**init**.py:1207: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub = rospy.Publisher(topic_name, msg_class, latch=latch)

**Comment by dirk-thomas** [comment]
The issue has been fixed in d9b607e4ac34210d7337ad34bfdbc12775a21bd9 already and is released in version 1.11.3.

I assume your are using 1.11.2 or earlier of `rostopic`?

**Comment by chadrockey** [comment]
Yeah, 1.11.2, sorry Dirk.  :(
