### ISSUE TITLE
rostest: Allow test suites to be called in rostest.rosrun

### ISSUE THREAD

**Issue by VGonPa** [ros/ros_comm#423]
See [this question](http://answers.ros.org/question/122786/any-way-to-use-a-testsuite-instead-a-testcase-with-rostest/).

The idea is to extend the functionality of `rostest.rosrun` so it can accept both `unittest.TestCase` and `unittest.TestSuite` in its parameters.

**Comment by heuristicus** [comment]
It looks like this could be added by using [`loadTestsFromName`](https://docs.python.org/2/library/unittest.html#unittest.TestLoader.loadTestsFromName) in the [`rosrun`](https://github.com/ros/ros_comm/blob/2c2e740bf8dd65c36e2a3411b24e9c3f1702b082/tools/rostest/src/rostest/__init__.py#L104) function

**Comment by felixdivo** [comment]
@dirk-thomas Is this still alive?

**Comment by dirk-thomas** [comment]
> Is this still alive?

I am not sure what you mean with "alive".

Looking at the ticket I assume it has been addressed by #722 and therefore I am going to close it.

**Comment by felixdivo** [comment]
Okay that's great! I meant alive like "still unsolved". ;)
