### ISSUE TITLE
message_filters: Incorporate python approximate time synchronizer

### ISSUE THREAD

**Issue by jbohren** [ros/ros_comm#424]
https://github.com/ros-perception/image_pipeline/issues/76

**Comment by dirk-thomas** [comment]
Please consider providing a pull request for this feature and also contribute to the documentation for it.

**Comment by vrabaud** [comment]
Well, it is already here :)
https://github.com/ros/ros_comm/blob/indigo-devel/utilities/message_filters/src/message_filters/__init__.py#L101
So you can close this one.

**Comment by vrabaud** [comment]
sorry, I missed it, this is approximate: should I create a new class or just add a slop parameter like done in the camera_calibration file ? (that would default to infinity I guess)

**Comment by tfoote** [comment]
A parameter seems reasonable. though i'd make the slop default to zero ;-)

For ease of use it might be worth implementing it in the regular syncronizer using a semi protected method, and then have a separate wrapper class which invokes that code path and provides the clear interface.

**Comment by vrabaud** [comment]
guys, it's good, please review https://github.com/ros/ros_comm/pull/433/
