### ISSUE TITLE
roslaunch ROS_HOME should be created before pid file

### ISSUE THREAD

**Issue by LucidOne** [ros/ros_comm#43]
if ~/.ros does not exist the following command fails
`roslaunch --core --pid=/home/turtlebot/.ros/roscore-11311.pid`

~/.ros should be created before pid file is written.

**Comment by dirk-thomas** [comment]
If you are not passing a custom pid the default location is used which is ROS_HOME/roscore-PORT.pid. In this case roslaunch will make sure that the folder exists. It seems that you pass in exactly the same value in the example - why do you specify the pid in that case at all?

If the user specifies a custom path for the pid than it seems to be a feasible assumption that the containing folder must exist. I think that this is pretty common for a lot of tools which write pid files. (I.e. if the user misspells a deep path slightly roslaunch would create the whole hierarchy)

**Comment by LucidOne** [comment]
I was only suggesting ROS_HOME should be created before the pid, not any arbitrary path.
However this is not that important, as I really just wanted it to simplify a bash startup script.

**Comment by dirk-thomas** [comment]
I see, when the custom path equates to a known path like the ROS_HOME that is feasible.
