### ISSUE TITLE
roslaunch: unit tests incorrectly assume 'talker' node is in 'rospy' pkg

### ISSUE THREAD

**Issue by gavanderhoorn** [ros/ros_comm#438]
As per subject: it would seem the tests for roslaunch seem to expect that `talker.py` can be found in the `rospy` package. It is currently (Hydro) in `rospy_tutorials`.

The `test_nodeprocess.py` test is the only one that seems to fail because of this (although at least `test_roslaunch_depends` also refers to `talker.py`).

**Comment by dirk-thomas** [comment]
All unit tests are currently passing: http://jenkins.ros.org/view/Idev/job/devel-indigo-ros_comm/

The test code brings their own talker nodes: https://github.com/ros/ros_comm/tree/indigo-devel/clients/rospy/test_nodes https://github.com/ros/ros_comm/tree/indigo-devel/test/test_rospy/nodes

**Comment by gavanderhoorn** [comment]
Right, seems I missed that directory. Apparently something was wrong with my package path, as `test_nodeprocess.py` was failing with references to it not being able to find `talker.py` in `rospy`.
Sorry for the noise.
