### ISSUE TITLE
rosbag record -O fails if output filename is 3 characters long

### ISSUE THREAD

**Issue by pcamp** [ros/ros_comm#449]
Bug is in the Recorder::updateFilenames function in ros_comm/tools/rosbag/src/recorder.cpp.  In line 334, the programmer's intention is that the condition (ind == prefix.size() - 4) is satisfied when prefix ends with ".bag".  However, the condition is also satisfied whenever the output filename is 3 characters long.  For example,
rosbag record -O abc mytopic
results in the error "terminate called after throwing an instance of 'std::out_of_range'
what(): basic_string::erase".  I suggest changing the condition to (ind != -1 && ind == prefix.size() - 4).

Also, I suggest deleting line 337 (ind = prefix.rfind(".bag");) because ind is never referred to after that.

**Comment by dirk-thomas** [comment]
I assume you refer to `-o` (prefix rather then `-O` for output name)?

The problem should be resolved with #451.

**Comment by pcamp** [comment]
The problem is resolved, but I meant what I said.  Have a look at this line:
https://github.com/ros/ros_comm/blob/indigo-devel/tools/rosbag/src/record.cpp#L109
What comes after the -O ends up in options_.prefix.
