### ISSUE TITLE
Crash under indigo due to concurrent rospy.get_param access

### ISSUE THREAD

**Issue by contradict** [ros/ros_comm#459]
This program crashes when run under ros indigo

``` python
import rospy
import tf

rospy.init_node("test")
tf.TransformListener()
while not rospy.is_shutdown():
    p = rospy.get_param("~test", 0.5)
```

The crash is due to concurrent calls to `rospy.get_param()`, one in the test code and
one inside [SubscriberStatisticsLogger](https://github.com/ros/ros_comm/blob/indigo-devel/clients/rospy/src/rospy/impl/statistics.py#L64). TransformListener subscribes to tf in a new [thread](https://github.com/ros/geometry/blob/indigo-devel/tf/src/tf/listener.py#L238) which causes two requests to be simultaneously issued to the same http connection object.

`rospy.get_param()` is documented to be non-threadsafe, but I am not so
sure about `rospy.Subscriber()`. If `Subscriber()` should be thread safe,
then `SubscriberStatisticsLogger` needs to be modified to avoid
concurrent access to the same http connection object as the rest of
the node. Perhaps it could be given its own connection to the
parameter server? If `Subscriber()` is not intended to be threadsafe,
then `TransformListenerThread` should probably subscribe in `__init__()` instead
of `run()`.

**Comment by tfoote** [comment]
From the comment it sounds like it's a regression from #383

**Comment by dirk-thomas** [comment]
@contradict Can you please post the error you get when running the program?

@forouher FYI since the problem is related to the new statistics code.

**Comment by contradict** [comment]
Reported error is:

```
$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    p = rospy.get_param("~test", 0.5)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 452, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msproxy.py", line 115, in __getitem__
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest
$ 
```

**Comment by forouher** [comment]
rosparam is non thread-safe while Subscriber is supposed to be? I'm not sure about the locking model in rospy. topics.py didn't have much locking (except it's own stuff), so I just assumed to be safe with the TopicStatistics stuff.

What would be the right thing to do? Never call getParam outside the main thread?
