### ISSUE TITLE
Need Provides for Debian dependency

### ISSUE THREAD

**Issue by LucidOne** [ros/ros_comm#46]
We have several external debian packages that can work with either Fuerte or Groovy and need some way to check that ROS is installed but we don't care which version.

To solve this we need to use the Provides directive in the debian control file.

For example ros-groovy-ros-comm could use something like 
Provides: ros-ros-comm
in the debian control file so our package can depend on that instead of maintaining two separate packages just to depend on ros-fuerte-ros-comm or ros-groovy-ros-comm

**Comment by dirk-thomas** [comment]
This is nothing which will be done for this package manually. The concept of "provides" would need to be specified in REP 127 and then be implemented in various tools of the release chain.

**Comment by dirk-thomas** [comment]
Closing this ros_comm specific ticket. Please feel free to open a ticket against the REP which specifies that. The chance to be integrate will be significantly higher if you provide pull requests for the spec and implementation.
