### ISSUE TITLE
roslaunch: Allow roslaunch XML to be passed on stdin

### ISSUE THREAD

**Issue by mikepurvis** [ros/ros_comm#472]
The intent would be enabling templated, xacro'd, or otherwise generated roslaunch, without a temporary file in between. Key design decision would be whether a sentinel is required as the file argument, or if it assumes to look on stdin in the absence of a supplied filename. Eg,

```
rosrun my_pkg create_launch | roslaunch  # assume to use stdin
rosrun my_pkg create_launch | roslaunch -  # sentinel value for file argument
```

Happy to implement this, with the maintainer's blessing to either of the above approaches.

**Comment by dirk-thomas** [comment]
I would think that having a sentinel value makes sense. I lot of users might be confused when calling it without arguments - currently they get a useful usage message.

It would be great if you can provide a PR for this feature.
