### ISSUE TITLE
Node is remapped but parameter is not remapped

### ISSUE THREAD

**Issue by tarukosu** [ros/ros_comm#474]
Node name can be remapped, but parameter is not remapped.
That's why parameter does not work.

This causes trouble when remapping a node whose node name and topic name are the same.

**Comment by dirk-thomas** [comment]
Can you please provide a minimal reproducible example which does not work for you and describe which parameter you expect and what you actually get?

**Comment by tarukosu** [comment]
This is a sample launch file.

```
<launch>
  <remap from="/joy" to="/joy_remap"/>
  <node pkg="joy" type="joy_node" name="joy" output="screen">
    <param name="dev" type="string" value="/dev/input/js1" />
  </node>
</launch>
```

The node name is /joy_remap but the parameter name is /joy/dev.
So I expect the parameter name is also remaped to /joy_remap/dev or node name is not remaped.

**Comment by dirk-thomas** [comment]
The behavior is consistent across all current ROS distros: Groovy, Hydro, Indigo.

Therefore it does not look like a recent regression. Also all remapping related unit tests pass. It might be that you expect a behavior which is not implemented that way.

Anyway I won't have time in the near future to look into in depth. Please consider investigating it  and if necessary provide a pull request.

**Comment by tarukosu** [comment]
I see.
But I think this is a bag of roslaunch because node name and parameter should be remapped in the same way.

However, we can avoid this problem by changing node name , so it is not urgent.
If I have time to improve, I will send a pull request.
Thank you.
