### ISSUE TITLE
rostopic echo topic/field fails if a topic with the same name has existed

### ISSUE THREAD

**Issue by miikka** [ros/ros_comm#487]
```
# Let's leave the publisher for /foo running in the background.
$ rostopic pub /foo std_msgs/String 'hello' &
$ rostopic echo -n 1 /foo
data: hello

---
$ rostopic echo -n 1 /foo/data
hello

---
# Now, let's publish /foo/data.
$ rostopic pub /foo/data std_msgs/String 'world' &
$ rostopic echo -n 1 /foo/data
data: world

---
# At this point, kill the publisher for /foo/data
$ kill %2
$ rostopic echo -n 1 /foo/data
# Nothing gets printed - what is going on here?
```

Since the publisher for `/foo/data` was killed, and `rostopic list` does not show `/foo/data` anymore, I'd expect to see `hello` again, instead of nothing.

**Comment by dirk-thomas** [comment]
`rostopic pub` only publishes a single message (on a latched topic) if you don't specify a rate for repeated publishing using `-r`. Hence the behavior you describe is exactly what is supposed to happen.

Try running your `rostopic echo` commands without `-n 1` and you will notice that they never receive more then one message. If you have further questions please consider asking them on answers.ros.org.
