### ISSUE TITLE
rosgraph_msgs/TopicStatistics missing delivered_msgs

### ISSUE THREAD

**Issue by gmwe** [ros/ros_comm#494]
rosgraph_msgs/TopicStatistics should contain **delivered_msgs** as stated in
[rosgraph_msgs](https://github.com/ros/ros_comm_msgs/blob/indigo-devel/rosgraph_msgs/msg/TopicStatistics.msg) and the [api-doc](http://docs.ros.org/api/rosgraph_msgs/html/msg/TopicStatistics.html) 

but running 
`rosmsg show rosgraph_msgs/TopicStatistics`
returns

``` python
string topic
string node_pub
string node_sub
time window_start
time window_stop
int32 dropped_msgs
int32 traffic
duration period_mean
duration period_stddev
duration period_max
duration stamp_age_mean
duration stamp_age_stddev
duration stamp_age_max
```

tested with
- /rosdistro: indigo
- /rosversion: 1.11.8

**Comment by dirk-thomas** [comment]
You are not using the latest version of the package. This feature has just been introduced in 1.10.3 (https://github.com/ros/ros_comm_msgs/blob/indigo-devel/rosgraph_msgs/CHANGELOG.rst).

The new package is not in the public repo yet: http://www.ros.org/debbuild/indigo.html?q=rosgraph_msgs
