### ISSUE TITLE
roslaunch: add support for more complex expressions in launchfile `if` attributes

### ISSUE THREAD

**Issue by jbohren** [ros/ros_comm#503]
Currently `if` attributes in launchfiles can only evaluate arg values. I think this annoys everyone. It's possible to restrict python's `eval()` function to only have access to certain functions and variables [1]. It shouldn't be too hard to add this support for the evaluation of the `if` or `unless` attributes.

The handling of `if` and `unless` is done here: https://github.com/ros/ros_comm/blob/ce75bf8d9c19f8337d2196d3d19f9ba8745e0583/tools/roslaunch/src/roslaunch/depends.py#L97

[1] http://lybniz2.sourceforge.net/safeeval.html

**Comment by po1** [comment]
#382 could potentially bring a lot of improvements to the current `if` and `unless` attributes.
A good (IMO) idea was given [here](https://github.com/ros/ros_comm/pull/341#issuecomment-38480179), but so far I don't think anybody gave it much time...

Relying on python to do it also seems nice and inexpensive, but I somehow feel better knowing that we can explicitly control the allowed operations.

**Comment by tfoote** [comment]
There's some simple eval functionality in #784 #762  and #793 following on #707. Is there anything more we should hold this ticket open for?

**Comment by jbohren** [comment]
@tfoote Nope, that's great that this stuff was added! Thanks @rhaschke!
