### ISSUE TITLE
rosbag: auto-generated docs don't include rosbag/bag.h

### ISSUE THREAD

**Issue by trainman419** [ros/ros_comm#504]
Most of the links here are broken: http://docs.ros.org/indigo/api/rosbag/html/player_8h.html

It sort of looks like the generated python and C++ API docs are generated on top of one another because they have the same class names.

This makes it rather difficult to get started working with the rosbag C++ API.

**Comment by trainman419** [comment]
Apparently these docs have moved to rosbag_storage: http://docs.ros.org/indigo/api/rosbag_storage/html/c++/index.html

And there seems to be some mismatch between the doc generation that is preventing the cross-linking from working properly.

**Comment by trainman419** [comment]
It looks like rosbag is missing the rosdoc.yaml that should be splitting the python and C++ doc generation into separate paths.

**Comment by dirk-thomas** [comment]
The rosdoc.yaml and mainpage.dox was moved from the `rosbag` package to `rosbag_storage` during the refactoring.

I have readded a rosdoc.yaml and mainpage.dox file for the `rosbag` package in ebd9e491e71947889eb81089306698775ab5d2a2.

Please recheck the updated docs.
If you think further changes are necessary please comment with specific proposals.

Regarding the links in the dependency graph: I expect them to fix get fixed after multiple doc generation runs. I will keep an eye on it.

**Comment by trainman419** [comment]
That looks much better! Thanks for the quick fix.

It looks like the cross-links to `rosbag/bag.h` here: http://docs.ros.org/indigo/api/rosbag/html/c++/player_8h.html point to http://docs.ros.org/indigo/api/rosbag/rosbag_storage/html/classrosbag_1_1Bag.html instead of http://docs.ros.org/indigo/api/rosbag_storage/html/c++/bag_8h.html . There are lots more examples of this throughout the API docs, but this is an easy example to describe and reproduce.

That said, the broken cross-linking is less of an issue now that the top-level docs indicate that most of the rosbag classes have now been moved to a new package ( #299 ).

**Comment by dirk-thomas** [comment]
I ran the doc job multiple times but the cross-referencing is still there. But this is not limited to rosbag. It seems to be a generic problem. I created a rosdoc_lite ticket for it: ros-infrastructure/rosdoc_lite#51

Are you ok with closing this ticket with the current state of the docs?

**Comment by trainman419** [comment]
Yeah, I think the remaining issue here is a bug in rosdoc_lite.
