### ISSUE TITLE
rosbag: bag info as a python object

### ISSUE THREAD

**Issue by csherstan** [ros/ros_comm#508]
The rosbag (bag.py) currently has 2 ways of dumping its info: as a string via **str**, or as a string in yaml format via _get_yaml_info.

It would be nice to just get the info as a python object without having to convert from the yaml returned by  _get_yaml_info.

**Comment by dirk-thomas** [comment]
Please consider providing a pull request to add this feature if it is valuable for you.

**Comment by csherstan** [comment]
I'd be happy to do so. Please assign me to the issue.

**Comment by dirk-thomas** [comment]
GitHub does not allow to assign tickets to users not members of the repo. But consider yourself "assigned" :wink:

**Comment by csherstan** [comment]
Pull request: https://github.com/ros/ros_comm/pull/510

Let me know if there are things that need to be corrected, etc. I'm fairly new to Python.

**Comment by dirk-thomas** [comment]
Implemented in #510.
