### ISSUE TITLE
[roslaunch] cache result of catkin_pkg.packages.find_packages to speed up roslaunch

### ISSUE THREAD

**Issue by garaemon** [ros/ros_comm#541]
![roslaunch_caller](https://cloud.githubusercontent.com/assets/40454/5586761/ff9a311a-911b-11e4-9a4e-05be2ee22011.png)

originally discussed in [here](https://github.com/ros-infrastructure/catkin_pkg/pull/111)
## Problem
- roslaunch is slow if catkin workspace has a lot of files
- `catkin_pkg.packages.find_packages` always scan workspace and it's not fast enough
- When rosbuild was used, roslaunch was not so slow, as far as I remember
## Approach
- During running roslaunch, catkin workspace must not be changed, so we can cache `catkin_pkg.packages.find_packages` like old rospack
- In order to keep backward compatibility, add keyword arguments to functions
## Benchmark
- Use [test.rosinstall](https://gist.github.com/garaemon/7a39457795e7c61d7d8c) to build workspace
  
  ```
  $ find src | wc -l
  17239
  $ find src -name package.xml | wc -l
  286
  $ find src -name manifest.xml | wc -l
  146
  ```
- Measure time of `roslaunch openni2_launch openni2.launch`
- Result
  - without caching -- 17 sec
  - with caching -- 5 sec
  - Movie
    - [without caching](http://youtu.be/_Utax0R3u0g)
    - [with caching](http://youtu.be/bAFNlsNcihU)

**Comment by garaemon** [comment]
These three patches are required:
- https://github.com/ros/ros_comm/pull/542
- https://github.com/ros/ros/pull/74
- https://github.com/ros/catkin/pull/704

**Comment by garaemon** [comment]
I updated PR according to https://github.com/ros/catkin/pull/704
1. Use source_path_to_packages keyword argument of `catkin.find_in_workspaces.find_in_workspaces` to cache package paths in catkin workspace
2. Add global variable to roslaunch python module to store cache paths (`_catkin_packages_cache`). 
   If we pass cache variable from `roslaunch.main` to all the function which use `catkin.find_in_workspaces.find_in_workspaces`, The call tree is complicated and deep.

**Comment by guihomework** [comment]
I think we face the same problem of caching, but due to several rospack find commands in our nested launch files, used in some urdf.xacro loading. This is even worse because we use a nfs file system for our system. 
It would help us a lot if this issue could be solved. @garaemon is there something we can help on ?

**Comment by wkentaro** [comment]
I sent another PR at:
- https://github.com/ros/ros_comm/pull/676
- https://github.com/ros/ros/pull/91
- https://github.com/ros/catkin/pull/757

**Comment by wkentaro** [comment]
cc: @guihomework

**Comment by guihomework** [comment]
thanks for adding me in cc, I am interested in testing that at some point but am really busy now. I will try to find some time in the coming days.
