### ISSUE TITLE
roscpp: Empty connection header topic

### ISSUE THREAD

**Issue by tonybaltovski** [ros/ros_comm#543]
I am trying to use a driver that reads the name of the incoming topic from the connection header.  When I publish data from a C++ node, it is always empty but when I use `rostopic pub` or python it works just fine.  Is there a way to ensure the connection header is populated?  

OS: Ubuntu 14.04

ROS:indigo 1.11.9

roscpp: 1.11.9-0trusty-20141029-0127-+0000

roscpp_core: 0.5.4-0trusty-20140724-0053-+0000

The subscriber is in C++ and is [here](https://github.com/smd-ros-devel/lynxmotion_ssc32/blob/master/src/ssc32_driver.cpp#L391)

Here is the code in [python](https://gist.github.com/tonybaltovski/e1470fc1175b423ca5f4) and the [C++ node](https://gist.github.com/tonybaltovski/ac75f7e3273e7086a433)

**Comment by wjwwood** [comment]
I can confirm what @tonybaltovski is describing, I used this package: https://github.com/wjwwood/conn_header_test

When listening (from C++) to a talker in Python I get something like this:

```
[INFO] [WallTime: 1420488403.278505] Publishing 'hello world 9' on topic '/chatter'
Header:
  callerid has value /talker_71570_1420488402228
  latching has value 0
  md5sum has value 992ce8a1687cec8c8bd883ec73ca41d1
  message_definition has value string data


  topic has value /chatter
  type has value std_msgs/String
[ INFO] [1420488403.292841000]: I heard: [hello world 9]
```

When the talker is C++, the topic filed is missing from the connection header:

```
[ INFO] [1420487965.160992000]: Publishing 'hello world 9' on topic '/chatter'
Header:
  callerid has value /talker
  latching has value 0
  md5sum has value 992ce8a1687cec8c8bd883ec73ca41d1
  message_definition has value string data

  type has value std_msgs/String
[ INFO] [1420487965.162136000]: I heard: [hello world 9]
```

I don't see anything in the documentation which indicates that this should be the case.

**Comment by gerkey** [comment]
Also, thanks much to @wjwwood for the easy-to-use test case.

**Comment by wjwwood** [comment]
> Also, thanks much to @wjwwood for the easy-to-use test case.

Sure, no problem. Like my mom always said: "Do unto others".

**Comment by tonybaltovski** [comment]
Thanks guys!
