### ISSUE TITLE
gmock support much like gtest

### ISSUE THREAD

**Issue by kunaltyagi** [ros/ros_comm#567]
Using a good mocking framework is a headache, and especially since ROS already supports gtest, can't the functionality be extended to google-mock framework on similar lines?

**Comment by dirk-thomas** [comment]
Duplicate of ros/catkin#699.

**Comment by kunaltyagi** [comment]
Sorry, is there a bounty?

**Comment by tfoote** [comment]
There's not a bounty. We tried turning on bounty source, but haven't actively been using it and have not turned it off.
