### ISSUE TITLE
Confusing documentation NodeHandle::subscribe(...) and ::publisher(...)

### ISSUE THREAD

**Issue by Bardo91** [ros/ros_comm#582]
In [node_handle.h](https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/node_handle.h), publisher's and subscriber's creation documentation sais that:

```
  On failure, an empty Publisher/Subscriber which can be checked with:
  if (handle)
  {
  ...
  }
```

`handle` seems to be a NodeHandle, however is the subscriber's or publisher's handle. That is a bit confusing. I Suggest change `handle`to `subscriber`, `subscriber_handle` or similar.

**Comment by dirk-thomas** [comment]
That sounds like a good clarification. The doc could also just include the definition of the variable. Then it would be even more obvious what it stands for.

Please consider providing a PR with the doc change.
