### ISSUE TITLE
rosservice: Using now and auto command line keys with rosservice in simulation

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#59]
When using now and auto keys on the command line and running Clock server (e.g. gazebo simulation) I get zero time filled instead of current simulation time (rosservice node is not running long enough to get a message from /clock topic).

I've made a simple patch (calling rospy.sleep(0) before asking for current time) for rosservice. I suppose something similar could be done for rostopic pub.

Patch was made against current version in fuerte (installed from packages).

patch against fuerte 8 weeks ago is available on trac: 
  https://code.ros.org/trac/ros/ticket/4065

**Comment by ablasdel** [comment]
patch added in 4065 trac ticket

```
--- /tmp/__init__.py    2012-11-15 16:53:01.000000000 +0100
+++ __init__.py 2012-11-15 16:56:18.000000000 +0100
@@ -406,6 +406,8 @@
     # search for the now/auto keywords first
     import std_msgs.msg
     rospy.init_node('rosservice', anonymous=True)
+    # This will wait for a message on /clock topic (if using simulated time)
+    rospy.sleep(0)

     if service_class is None:
         service_class = get_service_class_by_name(service_name)
```

**Comment by ablasdel** [comment]
After discussion with dirk the provided patch would not solve the problem as suggested, at best it would work in some cases and not others.

We need someone to submit a procedure for reproducing this issue before we can look into solving this problem correctly.

**Comment by dirk-thomas** [comment]
Without further information it is impossible to look into this issue. I will close the ticket until someone comments with further information.
