### ISSUE TITLE
message_filters: refactorization required (02/22/2011)

### ISSUE THREAD

**Issue by mirzashah** [ros/ros_comm#61]
Issue migrated from code.ros.org, posted by "rusu", ticket #3362

Message filters is due for refactorization, as many have already noted. Just creating a ticket so we can keep track of things.

Our tests showed a 150MB+ and 10+ seconds compile time increase for every object / GCC compilation unit.

This makes it really hard to use in large projects where several instantiations of message_filters subscribers or approximate time synchronizers are used.

Change History

Changed 23 months ago by straszheim 

status changed from new to assigned
Changed 23 months ago by straszheim 

I'm fairly confident that compile time could be improved and am working on it... a difficult job. It would be disappointing to find out later that there are fundamental problems with the design (other than compile time), so that this restructuring work needs to be thrown out.

Changed 23 months ago by rusu 

I agree. Troy, let's keep this one on hold and rediscuss this next week with Patrick. It might be that  https://code.ros.org/trac/ros/ticket/3363 invalidates this one.

**Comment by dirk-thomas** [comment]
Due to the age of the report it will be closed. If it is still an issue please provide more information.
