### ISSUE TITLE
message_filters: dynamic time synchronizers (02/22/2011)

### ISSUE THREAD

**Issue by mirzashah** [ros/ros_comm#62]
Issue migrated from code.ros.org, posted by "rusu", ticket #2562

We need a way to create more flexible time synchronizers that can potentially synchronizer a large number of topics. Since topics are the way to go in terms of "semantics" in ROS, there might be producers which can output several tens of topics that need to be synchronized.

If needed, the user can specify the maximum number of topics that need to be synchronized via a ROS parameter (e.g., 64 topics or 100 topics, etc).

**Comment by dirk-thomas** [comment]
I will close the ticket due to the age and mark it as "wontfix"
