### ISSUE TITLE
rostest ran with improper ROS_MASTER_URI

### ISSUE THREAD

**Issue by 130s** [ros/ros_comm#63]
Migrated from https://code.ros.org/trac/ros/ticket/3270
Attachment available in code.ros.org?: No
Priority:   major 
Last modified ago: Jan 2011
Owned by:   kwc 
Reported by:    tfoote

---

```
Standard Error

[test_nodelet.rostest__test_test_console] stderr--------------------------------
?[31mWARNING: ROS_MASTER_URI port [11311] does not match this roscore [22422]?[0m
?[31m[console_test-2] escalating to SIGTERM?[0m
```

 http://build.willowgarage.com/job/devel_unstable_common_maverick_i386/17/testReport/test_nodelet.TEST-rostest__test_test_console.rostest.runner/RosTest/test_nodelet_rostest__test_test_console_testconsole_test/

This happens semi repeatably on this build

**Comment by dirk-thomas** [comment]
This is not reproducible anymore. Please comment/reopen when still an issue and provide current example.
