### ISSUE TITLE
message_filters: Subscriber needs a copy constructor (03/02/2011)

### ISSUE THREAD

**Issue by mirzashah** [ros/ros_comm#64]
Issue migrated from code.ros.org, posted by "sglaser", ticket #3384. I can confirm I do not see a copy constructor defined in Subscriber.h

Details:
In order to create a std::vector<message_filters::Subscriber>, the message_filters::Subscriber class needs a copy constructor.

**Comment by dirk-thomas** [comment]
Since each `Subscriber` is actually maintaining its subscription either a plain pointer or a shared_ptr should be stored in containers.

Therefore closing this ticket.
