### ISSUE TITLE
rosbag record: specifying the same topic multiple times causes duplicate messages 

### ISSUE THREAD

**Issue by dlaz** [ros/ros_comm#647]
For example

```
rosbag record /foo /foo
rostopic pub -1 /foo std_msgs/Empty
```

results in

```
types:       std_msgs/Empty [d41d8cd98f00b204e9800998ecf8427e]
topics:      /foo   2 msgs    : std_msgs/Empty
```

While this can probably be considered user error, I can't think of a situation when this is actually the desired behavior that rosbag should support. If this is indeed not the desired behavior, I'll submit a PR fixing it (eventually).

**Comment by dirk-thomas** [comment]
This was addressed by #648.
