### ISSUE TITLE
Releasing new version 

### ISSUE THREAD

**Issue by k-okada** [ros/ros_comm#680]
#676 will provide a great improvement on the performance, so could your lease new version so we ca use them as deb package ?

**Comment by dirk-thomas** [comment]
Since a `ros_comm` release implies rebuilding and also redistributing almost every ROS package it is a very costly step. The roslaunch improvement alone does not justify that effort yet. But there will likely be a new release soon - when other PR have been merged.

**Comment by k-okada** [comment]
new version has been released
