### ISSUE TITLE
rosconsole:  ROS_DEBUG_THROTTLE_COND

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#69]
A common use case for throttled rosconsole messages is to warn about some sanity-check condition being false, but not fill the screen with warnings. It would make sense to be able to say

ROS_DEBUG_THROTTLE_COND(5.0, !validityCheck(), "State is invalid!")

with the intended meaning that every 5 seconds, validityCheck is called, and if it's false the message is output. NAMED and STREAM variants would also be nice.

**Comment by dirk-thomas** [comment]
Related to #68

**Comment by dirk-thomas** [comment]
This issue was moved to ros/rosconsole#2
