### ISSUE TITLE
rosmsg show has no error when message are not found

### ISSUE THREAD

**Issue by trainman419** [ros/ros_comm#691]
Observed behavior:

```
$ rosmsg show Quux
$
```

Expected behavior: some kind of error message indicating that the message was not found.

For example:

```
$ rosmsg show Quux
Error: message 'Quux' not found in any package.
ROS_PACKAGE_PATH=...
```

**Comment by dirk-thomas** [comment]
Please consider providing a PR to improve `rosmsg show` to print an error message as well as return a non-zero return code.

**Comment by trainman419** [comment]
I'm not sure I'll have time to submit a PR for this.

I filed it because it showed up on ROS answers, and having no error output is poor user experience: http://answers.ros.org/question/219648/
