### ISSUE TITLE
[roscpp] NodeHandle constructor with parent parameter does not work with a namespace with a leading slash

### ISSUE THREAD

**Issue by jim-rothrock** [ros/ros_comm#692]
In the examples below, model_nh.getNamespace() returns "/cerberus".

According to the NodeHandle constructor documentation,

```
ros::NodeHandle nh(model_nh, "/gazebo_ros_control/pid_gains/" + "arm_base_joint");
```

should be equivalent to

```
ros::NodeHandle nh(model_nh.getNamespace() + "/" + "/gazebo_ros_control/pid_gains/" + "arm_base_joint");
```

They are not. When using the second statement, nh.getNamespace() returns "/cerberus/gazebo_ros_control/pid_gains/arm_base_joint". When using the first statement, nh.getNamespace() returns "/gazebo_ros_control/pid_gains/arm_base_joint". Is the slash before "gazebo_ros_control" prohibited? The gazebo_ros_control package is using code similar to the first example, and no longer finds the PID parameters for my robot's joints. I think that this code worked as of June, 2015. I'll probably change "/gazebo_ros_control" to "gazebo_ros_control" in the gazebo_ros_control source code to fix the problem, but I wanted to point out this issue in case the NodeHandle constructor's current behavior is considered a bug. If it isn't, then the claim of constructor equivalence in the documentation is wrong.

**Comment by dirk-thomas** [comment]
If the passed `namespace` argument is absolute the namespace of the parent node handle is _not_ prepended. I have created #715 to update the docblock to clarify that.
