### ISSUE TITLE
types and topics in rosbag info should be sorted the same

### ISSUE THREAD

**Issue by NikolasE** [ros/ros_comm#696]
I have a small bag file with just two topics and rosbag looks like:

> path:        2015-11-07-13-07-19.bag
> version:     2.0
> duration:    3.8s
> start:       Nov 07 2015 13:07:23.23 (1446898043.23)
> end:         Nov 07 2015 13:07:27.01 (1446898047.01)
> size:        333.0 KB
> messages:    4
> compression: none [1/1 chunks]
> types:       tf/tfMessage                   [94810edda583a504dfda3829e70d7eec]
>              visualization_msgs/MarkerArray [90da67007c26525f655c1c269094e39f]
> topics:      /office_visualization   1 msg     : visualization_msgs/MarkerArray
>              /tf_static            3 msgs    : tf/tfMessage

Types and topics are sorted individually but I think it would be better if e.g. the types are sorted like the topics so that you are able to look up the type of the nth topic in the bag by looking at the nth entry of the types-list.

**Comment by dirk-thomas** [comment]
Please consider providing a PR if this feature is valuable to you.

Since it is unlikely that the maintainers will work on this I will mark this ticket with the milestone `untargeted`.
