### ISSUE TITLE
inconsistency of argument name in SubscriberLink

### ISSUE THREAD

**Issue by dominiquehunziker** [ros/ros_comm#701]
The argument names of the [SubscriberLink interface](https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/subscriber_link.h#L72) are not consistent with the interface implementations [here](https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/transport_subscriber_link.h#L53) and [here](https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/intraprocess_subscriber_link.h#L53).
I believe the two argument names `ser` & `nocopy` have to be swapped in the interface.

**Comment by dirk-thomas** [comment]
Thank you for pointing it out.
