### ISSUE TITLE
std_msg serialize uses undefined _x variable

### ISSUE THREAD

**Issue by felixduvallet** [ros/ros_comm#705]
Several of the std_msgs implementations use an undefined `_x` variable in `serialize()`. For example, _Int32.py has:

``` python
def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))
```

Any exception in publishing the message will try to access `str(_x)`, where `_x` is undefined. As a comparison, _String.py defines:

``` python
_x = self.data
```

A minimal failing example is a publisher that attempts to send a message without casting it properly:

``` python
import rospy
import std_msgs

rospy.init_node('talker')
pub = rospy.Publisher('/foo', std_msgs.msg.Int32, queue_size=1)
rospy.sleep(1)
msg = std_msgs.msg.Int32('1')  # NOTE: the type is incorrect
pub.publish(msg)  # This should raise a struct.error
```

The equivalent call for a String message will correctly raise an exception:
`rospy.exceptions.ROSSerializationException: field data must be of type str`

**Comment by dirk-thomas** [comment]
Moved to ros/genpy#42.
