### ISSUE TITLE
Latched Topics in Split Bags

### ISSUE THREAD

**Issue by DLu** [ros/ros_comm#706]
I'm trying to record TF data across split bags. (`rosbag record --split --duration=5s /tf /tf_static`) The /tf_static topic is only recorded in the first bag. 

Is there anyway to force rosbag to record latched topics in each bag?

**Comment by dirk-thomas** [comment]
There is currently no such option.

**Comment by wjwwood** [comment]
I outlined some possible solutions in https://github.com/ros/ros_comm/issues/805#issue-155150413

**Comment by JanezCim** [comment]
Just an FYI for anyone struggling, using the command

`rosbag play 0.bag 1.bag 2.bag`

will keep all the static transforms correctly for the whole duration of all the split bag files combined. The problem becomes when you try to play them back separately. But afaik this is being solved in Noetic.

**Comment by chaoflow** [comment]
This has been implemented with #1850 included in noetic. I think the issue can be closed.

**Comment by DLu** [comment]
Thanks @tappan-at-git !
