### ISSUE TITLE
Data Race in timer_manager.h

### ISSUE THREAD

**Issue by Crusty82** [ros/ros_comm#732]
potential write after read:

void TimerManager<T, D, E>::schedule(const TimerInfoPtr& info):
info->removed read protected by waiting_mutex_

void TimerManager<T, D, E>::remove(int32_t handle):
info->removed write protected by timers_mutex_

Read and write protected by different mutexes, rendering them ineffective.

**Comment by Crusty82** [comment]
edit: Sorry, I just saw this was fixed in Indigo, seems I have an older version where this is still an issue.
I cant close the issue, maybe you want to do that

**Comment by dirk-thomas** [comment]
Since Hydro and older ROS distros are EOL and not being built anymore on the farm they can't be psyched anymore.
