### ISSUE TITLE
Mono16 images displayed as 8 bits in rostopic echo

### ISSUE THREAD

**Issue by ThomasGuerneve** [ros/ros_comm#755]
Mono16 images are getting displayed as mono8 bits images when doing a rostopic echo. (Values don't go over 255 and there are twice as many values as expected). It's really a display bug since I can read them on the receiver node without any problem.

http://answers.ros.org/question/227295/mono16-images-displayed-as-8-bits-in-rostopic-echo/

**Comment by dirk-thomas** [comment]
You question has already been answered on answers.ros.org.

A generic tools like `rostopic echo` cannot make any assumptions about the semantic interpretation of the byte array. The flag to interpret the data as 16bit data values simply has no meaning to the tool. Every byte array is printed the same way.
