### ISSUE TITLE
tools/*/test vs test/test_*/test

### ISSUE THREAD

**Issue by eric-wieser** [ros/ros_comm#778]
What's the difference in purpose between these two sets of folders?

**Comment by dirk-thomas** [comment]
Every test which can be performed within a package is usually implemented in the package itself.

Some tests require additional dependencies and some of them would introduce circular dependencies. Especially in these low level packages. Therefore these tests are moved into separate `test_*` packages to avoid a dependency cycle.

**Comment by eric-wieser** [comment]
Thanks!
