### ISSUE TITLE
Add stop function for rosbag recorder

### ISSUE THREAD

**Issue by GnarZiheng** [ros/ros_comm#779]
The rosbag recorder class by default can only stop bag recording when ros::shutdown is called or Ctrl+C in command line. Using the existing recorder class, It adds some trouble in our research project when we want to easily stop recording topics whenever it is needed. It would be great if some changes on recorder class can be added or providing a stop() method to allow application to start and stop recording.

**Comment by dirk-thomas** [comment]
Duplicate #428
