### ISSUE TITLE
add_rostest ARGS only takes the first argument

### ISSUE THREAD

**Issue by efernandez** [ros/ros_comm#790]
`add_rostest(test/testlaunchfile.test argument1:=vaule1 argument2:=value2)`

when used in https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rostest/cmake/rostest-extras.cmake.em#L55

generates

``` bash
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/efernandez/ws/src/package_name --package=package_name --results-filename test_package_name__argument1_value1.xml --results-base-dir /home/efernandez/ws/build/package_name/test_results /home/efernandez/ws/src/package_name/test/testlaunchfile.test argument1:=value1
  argument2:=value2
```

Note that after the first argument, there's a new line. Maybe that's the problem.

**Comment by efernandez** [comment]
It seems that `cmake_parse_arguments` is used properly, to take multiple arguments. So maybe the problem is when they're used to run the rostest command.

https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rostest/cmake/rostest-extras.cmake.em#L18

https://cmake.org/cmake/help/v3.0/module/CMakeParseArguments.html

According to that link, _rostest_ARGS should have "argument1:=vaule1;argument2:=value2" for my example. Probably there's an issue with the `;`, which should be replaced with ` ` ?!

@dirk-thomas Any idea?

FYI @mikepurvis

**Comment by dirk-thomas** [comment]
Please see #791 for the fix.
