### ISSUE TITLE
rosbag::Player class comment promises public release

### ISSUE THREAD

**Issue by DianaLaa** [ros/ros_comm#815]
As indicated here: http://answers.ros.org/question/235952/when-will-rosbagplayer-be-released/

rosbag::Player class shows comment

```
PRIVATE. Player class to abstract the interface to the player.
This API is currently considered private, but will be released in the future after view.
```

Will this ever be released? I would very much like to know. Thank you kindly in advance.

**Comment by dirk-thomas** [comment]
The line in question hasn't been touched for six years (https://github.com/ros/ros_comm/commit/7e945ae70bf1fdd3cd77b6b9b9be9a40678d39ad#diff-40a9eca5fa5cae3caaf8813ce7938968R136) (and even then only for moving code). It is not planned to change anything atm.
