### ISSUE TITLE
release current indigo-devel state

### ISSUE THREAD

**Issue by floweisshardt** [ros/ros_comm#824]
@dirk-thomas: is there a plan to release the current  indigo-devel state? We require the patch in https://github.com/ros/ros_comm/pull/814 (which is already merged).

**Comment by dirk-thomas** [comment]
There was no plan for it but I did a set of Indigo releases based on your request. `ros_comm` 1.11.20 has been tagged and will make it through the build farm in the next days (and some time later be synced to the main repo).

**Comment by floweisshardt** [comment]
perfect, thanks!
