### ISSUE TITLE
`rosbag filter` should show progress based on uncompressed size of bag (or preserve compression)

### ISSUE THREAD

**Issue by benwr** [ros/ros_comm#827]
`rosbag filter` writes to an uncompressed bag, but shows progress based on the raw input bag's filesize. This can be pretty confusing if you're reading from a large, compressed bag - you'll hit 100% progress, but then the output file will keep growing for a long time.

**Comment by dirk-thomas** [comment]
Please consider to contribute a pull request for this enhancement.
