### ISSUE TITLE
Warnings (unused-parameter, strict-aliasing) warnings from roscpp.

### ISSUE THREAD

**Issue by mikepurvis** [ros/ros_comm#841]
See: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__roscpp__ubuntu_xenial_amd64__binary/11/consoleFull

15 instances of `unused parameter`, 10 instances of `strict aliasing`

These make a mess in our bundle builds, as catkin_tools dumps all stderr output to the main build log.

@dirk-thomas I can fix the causes or suppress the warnings; which would you prefer?

**Comment by dirk-thomas** [comment]
Good point. It's always good to build without warnings. Since it was a trivial patch I created #842 for it. Please take a look and check if it makes it warning free for you too.
