### ISSUE TITLE
rosgraph - roscore crash on OSX, depending on network setup

### ISSUE THREAD

**Issue by luke-gumbley** [ros/ros_comm#845]
Crashes for me with a fresh Yosemite install. For a similar report, see http://answers.ros.org/question/220631/roscore-bug-errno8/

The issue is caused by OSX being categorised as non-unix-like in network.py, meaning the less sophisticated local address lookup is used. PR inbound.

**Comment by dirk-thomas** [comment]
The references questions seems to have been resolved by resetting the environment variables and setting the hostname. Can you please describe what your exact problem is?

**Comment by luke-gumbley** [comment]
On OSX, the machine name is not automatically resolvable to the local machine. You must either append ".local" or add the machine name to the hosts file as 127.0.0.1.

In the referenced example, the initial report did have problems with environment variables but the follow-up comment beneath refers to the actual issue ("my computer couldn't ping itself under its own name").

Resolution is straightforward - rosgraph already includes a more sophisticated method of obtaining local addresses, but it's not used as the OS check for it excludes OSX. My PR just adds OSX back in.

**Comment by dirk-thomas** [comment]
Addressed by #846.
