### ISSUE TITLE
import rospy fails

### ISSUE THREAD

**Issue by eendebakpt** [ros/ros_comm#848]
I installed rospy using the `setup.py` (and also `cmake`) without any errors (python3). However, when I try `import rospy` I get the following error message:

``` python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/eendebakpt/.local/lib/python3.5/site-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
ImportError: No module named 'std_msgs'
```

Where can I find and install `std_msgs`? Should the `std_msgs` package be added to the requirements of `setup.py`?

**Comment by dirk-thomas** [comment]
You should not use the `setup.py` file to install ROS packages but only use `cmake`. The dependencies of a package are defined in the `package.xml` file. You need to build / install all dependencies before you can build a package (see [from-source installation instructions](http://wiki.ros.org/kinetic/Installation/Source)).

Please also see the [support guideline](http://wiki.ros.org/Support) and ask further questions at http://answers.ros.org
