### ISSUE TITLE
Problem with many simultaneous connects to rosmaster on OSX 10.11 

### ISSUE THREAD

**Issue by jonfink** [ros/ros_comm#849]
As in [http://answers.ros.org/question/240430/problems-launching-many-nodes-on-osx](http://answers.ros.org/question/240430/problems-launching-many-nodes-on-osx)

I started experiencing intermittent problems with ROS (jade) on OSX 10.11 when running many nodes all trying to start up at once and access the rosmaster for subscriptions, publishes, and param server access.

Wrote a very simple test node:

``` c++
#include <ros/ros.h>

int main(int argc, char *argv[])
{
  ros::init(argc, argv, "test_node");
  ros::NodeHandle pnh("~");

  ros::Rate r(100.0);

  while(ros::ok()) {

    if(!ros::master::check()) {
      ROS_ERROR("[%s] Unable to see master", ros::this_node::getName().c_str());
    }

    ros::spinOnce();

    r.sleep();
  }

  return 0;
}
```

And ran many (up to 100, but ran into problems by 30 or 40) instances of it.

**Nodes periodically report that they are unable to contact the master.** This is in keeping with what I noticed in my "real-world" setting, nodes would intermittently fail to contact master and be unable to retrieve parameter settings.

**Comment by dirk-thomas** [comment]
Fixed by 1e546976053ea948dfb22cba46e11ce2af53e541.
