### ISSUE TITLE
rosbag: backtrace in rosbag migration w/o failure

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#85]
make test in test_common_msgs trunk But the tests pass.

Traceback (most recent call last):
  File "/home/tfoote/cmt/common_msgs/test_common_msgs/test/test_common_msgs_migration.py", line 78, in <module>
    migrator = rosbag.migration.MessageMigrator()
  File "/opt/ros/unstable/stacks/ros_comm/tools/rosbag/src/rosbag/migration.py", line 635, in **init**
    renamed = (sn.old_class._type != sn.new_class._type)
AttributeError: 'NoneType' object has no attribute '_type'

**Comment by FranklynJey** [comment]
Hey :D I just ran into the same Traceback. Did you find a solution back then? Cheers, Franklyn

**Comment by dirk-thomas** [comment]
@FranklynJey If you could provide a reproducible example that might help to find the problem and fix it.

**Comment by dirk-thomas** [comment]
I will close this due to no response. Please feel free to comment with the requested information and this ticket can be reopened.
