### ISSUE TITLE
Rosbag record dropping and corrupting data

### ISSUE THREAD

**Issue by gnarang1024** [ros/ros_comm#852]
Hello,

I'm trying to store selected topics being published from various sensors sources (velodyne, monocular camera, IMUs) in a large bag file. I'm able to record the bagfile without seeing any errors. However, when I play back the file, I'm seeing the following errors:
1. Some of the frames of the Velodyne data are being dropped. I've tried recording multiple bagfiles but I see this behavior in all of them
2. From the monocular camera, I'm just recording the camera/image_raw topic . However, after about a minute into the bagfile, the camera input image splits into 2 unequal part and one of the parts get displaced (as seen in the pictures below). I'm seeing this behavior in most of the bagfiles and the time of split is random. 

_**Original Image:**_

![normal_image](https://cloud.githubusercontent.com/assets/17033017/17342704/60ed38de-58c8-11e6-9ae3-6b2e79e1cd00.png)

**_Corrupted Image:_**

![split_image](https://cloud.githubusercontent.com/assets/17033017/17342727/80390c7c-58c8-11e6-94b4-225d8a5f5524.png)

A few details about my setup:
1. I have tried recording files at 2 buffer sizes 1024 and 0 (infinity) and I see these problems in both cases
2. I have tried recording bagfiles on and Odroid XU4 and a high-performance laptop but that did not help
3. I'm running ROS indigo on Ubuntu 14.04

**_Rosbag Info:_**

![rosbag_info](https://cloud.githubusercontent.com/assets/17033017/17343037/d44d6ba4-58c9-11e6-81d4-a833c5b0d8d7.png)

I will be happy to provide any relevant info that may be required. Thanks in advance!

**Comment by dirk-thomas** [comment]
Please do not cross post your question. Since you already asked the same question on [answers.ros.org](http://answers.ros.org/question/240948/rosbag-record-dropping-and-corrupting-data/) I will close this for now.

If it turns out it is a bug in `rosbag` this ticket can of course be reopened.
