### ISSUE TITLE
rosrun and tab will appear invalid node

### ISSUE THREAD

**Issue by ghost** [ros/ros_comm#853]
rosrun  package + tab, will appear rosnodes which are deleted. Cmakefiles  and node files are all delete.and also remake again.

**Comment by dirk-thomas** [comment]
Without more information I can't look into this. "all delete" is just too fuzzy to know what you did. Please post e.g. a sequence of commands to reproduce the issue.

**Comment by spaghetti-** [comment]
Does this happen if you open a new shell? Does not for me.

**Comment by dirk-thomas** [comment]
I will close this ticket for now due to no response. Please feel free to comment with the requested additional information and the ticket can be reopened.
