### ISSUE TITLE
rosout log rotation is odd

### ISSUE THREAD

**Issue by mgrrx** [ros/ros_comm#854]
Normally you'd expect that the rosout log file is rotated as usual (https://en.wikipedia.org/wiki/Log_rotation) by increasing the number in the suffix for old log file such that it is always guaranteed that rosout.log.2 is older than rosout.log.1. The current implementation moves rosout.log to rosout.log.(current_back_index % 10) during "rotation", thus the ordering is not preserved as you would expect it.

**Comment by dirk-thomas** [comment]
Addressed by #991 in ROS Lunar.
