### ISSUE TITLE
'rostopic echo' returning incomplete message data for some topics

### ISSUE THREAD

**Issue by davidepalozzi** [ros/ros_comm#868]
it appears that the kinetic-devel branch has a regression, introduced at commit https://github.com/ros/ros_comm/commit/e0f63978fe0dd239ba8002a7e79756cdf1a335d0

`rostopic echo` may not properly return the message data for some topics

this can be reproduced as follows:
- put the latest ros_comm (kinetic-devel branch) in a source overlay workspace (i overlaid this on-top of indigo)
- start roscore in one terminal
- start the sample TF broadcaster node (code below) in another terminal
- run `rostopic echo /tf`. this will return `transforms: None`
- spinning up a rosnode (tested via rospy) and subscribing to the topic does indeed result in the expected message data. this is only a problem using `rostopic echo` on the commandline it seems

repeating the above on a previous commit (i.e. 9ff6955679afc791240aba637dacde6eeb5ae8eb) of ros_comm has no issue and `rostopic echo /tf` returns the expect result

sample TF broadcaster node:

```
#!/usr/bin/env python  
import rospy
import tf
import time

if __name__ == '__main__':
    rospy.init_node('test')

    while not rospy.is_shutdown():
        br = tf.TransformBroadcaster()
        br.sendTransform((0, 0, 0),
                         tf.transformations.quaternion_from_euler(0, 0, 0),
                         rospy.Time.now(),
                         'test',
                         "world")
        time.sleep(1)
```

**Comment by dirk-thomas** [comment]
Thank you for reporting this. The change was part of #724.

@wkentaro Can you please try to reproduce the reported problem and if necessary provide a patch.

**Comment by wkentaro** [comment]
Ok I will.

**Comment by wkentaro** [comment]
I think https://github.com/ros/ros_comm/pull/872 fixes this problem.

**Comment by dirk-thomas** [comment]
@wkentaro Thank you for the fix.

@davidepalozzi Can you please try the proposed fix from the PR and comment here if it resolves the your problem.

**Comment by davidepalozzi** [comment]
yep, looks good! Thanks guys.

**Comment by dirk-thomas** [comment]
@davidepalozzi Thanks for reporting and checking the patch.

@wkentaro Thanks for the fast fix.
