### ISSUE TITLE
rosbag::Recorder: Less than  of space free on disk with FILENAME.  Disabling recording.

### ISSUE THREAD

**Issue by dborrman** [ros/ros_comm#883]
min_space and min_space_str should be added to the default constructor of rosbag::Recorder, using the old hard-coded values  for 1GB, to stop old applications from terminating on newer ROS version.

When not setting those values explicitly the check for free space fails, the recorder terminates and the following error message with an empty string is not helpful:

ROS_ERROR("Less than %s of space free on disk with %s.  Disabling recording.", options_.min_space_str.c_str(), bag_.getFileName().c_str());

**Comment by dirk-thomas** [comment]
#884 should address the problem you described. It would be great if you could try the fix and confirm that it works for you.

**Comment by dborrman** [comment]
Yes, this works for me. Thanks!
