### ISSUE TITLE
rosbag: rosrecord feature request: synchronize recording of multiple topics

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#90]
It would be nice if rosrecord could take a set of topics to synchronize and record together (eg for stereo cams).

migration of trac ticket 1854:
 https://code.ros.org/trac/ros/ticket/1854

Change History:
Changed 3 years ago by gerkey 

milestone changed from ROS M3 to ROS 1.1
Bumping to 1.1; bring it back to 1.0 if you intend to do it very soon.

Changed 3 years ago by gerkey 

milestone changed from ROS 1.1 to ROS 1.3
This should probably be done with a rosbag nodelet that would allow in-process synchronization without reserialization.

Changed 3 years ago by leibs 

status changed from new to assigned
I want to make sure this gets addressed for D-turtle.

Changed 3 years ago by leibs 

component changed from rosplay/rosrecord/rosbagmigration to rosbag
Changed 2 years ago by leibs 

milestone ROS 1.3 deleted
I'm bumping this off 1.3 Milestone. I want this to be part of a new experimental tool I plan to write.

Changed 2 years ago by leibs 

milestone set to ROS 1.5
Changed 2 years ago by leibs 

status changed from assigned to new
Will reaccept when I know I will be working on it.

**Comment by dirk-thomas** [comment]
rosrecord should not be affected by this. It can record arbitrary data as they come in - any synchronization should be done before recording or after playing back.
