### ISSUE TITLE
rostopic echo -p no longer works

### ISSUE THREAD

**Issue by geoffviola** [ros/ros_comm#915]
There seems to be a new bug with rostopic echo, when printing in the csv format.

It looks like the call at https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rostopic/src/rostopic/__init__.py#L936 expects value_transform as the parameter name. Meanwhile, the function defined at https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rostopic/src/rostopic/__init__.py#L725 takes value_transform_fn as a parameter. Changing either seems to work as long as they're consistent, but I'm not sure which is better to change.

**Comment by wjwwood** [comment]
Is this related to https://github.com/ros/ros_comm/pull/909?

**Comment by geoffviola** [comment]
I don't think so. This error is specific to printing in the CSV format. Printing normally works fine.

**Comment by geoffviola** [comment]
It looks related to this commit: https://github.com/ros/ros_comm/commit/e0f63978fe0dd239ba8002a7e79756cdf1a335d0

**Comment by dirk-thomas** [comment]
@wkentaro can you please check if this is a regression and if yes work on a fix?

**Comment by wkentaro** [comment]
@geoffviola Could you give me commands how to reproduce the error?

**Comment by geoffviola** [comment]
### Window 1
1. source /opt/ros/kinetic/setup.bash
2. roscore

---

### Window 2
1. source /opt/ros/kinetic/setup.bash
2. rosrun roscpp_tutorials talker

---

### Window 3
1. source /opt/ros/kinetic/setup.bash
2. rostopic echo /chatter -p
