### ISSUE TITLE
rosbag play: loading progress bar

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#92]
When opening a large bag rosbag play can get "stuck" for a while at "Opening <bag name>". It would be nice to have a progress bar/status update to show what it's doing.

This would likely involve an API addition as well, to provide this functionality for anyone.

migration of trac ticket 2719:
 https://code.ros.org/trac/ros/ticket/2719

change history:
Changed 3 years ago by jfaust 

owner changed from tfield to leibs
Changed 3 years ago by tfield 

While a progress bar would be a good interim solution, the goal should really be to remove any delay on opening a bag.

At the moment, the entire index is loaded. Ideally we'd only populate the chunk indexes on demand. Jeremy would have a better idea, but this could prove tricky considering how View is currently implemented.

Changed 3 years ago by leibs 

We're definitely planning on a future performance optimization to lazily load the chunk indexes, but I think that's still a ways off. Most likely post-C-turtle. Adding a progress callback to the open call seems like it should be fairly easy though.

Changed 3 years ago by tfield 

summary changed from robag play: loading progress bar to rosbag play: loading progress bar
Changed 3 years ago by jfaust 

no no, this was for robag

Changed 3 years ago by tfield 

Are you going to have a go at this for C-turtle, Jeremy?

Changed 2 years ago by straszheim 

'record' could use a spinner as well, preferably only visible when a -v or somesuch is specified

**Comment by dirk-thomas** [comment]
This should not be an issue anymore. Loading a bagfile with more than one GB of data took only a fraction of a second under Groovy.
