### ISSUE TITLE
Inconsistent value of header seq: first message in rospy has seq=1 and first message in roscpp has seq=0

### ISSUE THREAD

**Issue by sd1074** [ros/ros_comm#921]
I was planning to use Header seq value to verify that communication in my system of ROS-nodes (using ROS Indigo) is synchronized, however, I discovered a couple issues with that value.
1. The value of seq in the first message published with a rospy node is 1, whereas the value of seq in the same case with roscpp node is 0 (see examples below). That looks somewhat inconsistent. Is that an expected behavior or a bug?
2. In rospy, msg.header.seq is updated every time the message is published. In roscpp, in the published data the value is incremented as well, but the value in the message object itself doesn't seem to be updated (always 0). Seems like there is no way to read value.

Please find the sample code demonstrating the issues here:
http://answers.ros.org/question/246195/issues-with-header-seq-value-first-value-in-rospy-is-0-first-value-in-roscpp-is-1-access-from-roscpp/

**Comment by dirk-thomas** [comment]
Please see other related questions:
- http://answers.ros.org/question/55126/why-does-ros-overwrite-my-sequence-number/
- http://answers.ros.org/question/38856/ros-header-increasing-seq-in-service-calls/

The sequence number in the header is deprecated. The existing behavior is only there for backward compatibility. Therefore the different behavior you experience will not be fixed.
