### ISSUE TITLE
[rosbag] API Documentation is broken

### ISSUE THREAD

**Issue by jackieokay** [ros/ros_comm#922]
There are broken documentation links in the rosbag Doxygen documentation posted on the ROS wiki page.

e.g.
http://docs.ros.org/api/rosbag_storage/html/classrosbag_1_1Bag.html
is broken. This page leads to it: http://docs.ros.org/api/rosbag/html/c++/namespacerosbag.html

**Comment by dirk-thomas** [comment]
Thanks for the report. The problem has been addressed by ros-infrastructure/ros_buildfarm#352.
