### ISSUE TITLE
rosbag: Allow adding a description to a bag file

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#93]
I tend to lose track of which bag file is which. It would be nice to be able to add a text description to the metadata of a bag file.

Relevant thread from ros-users:

 http://ros-users.122217.n3.nabble.com/Meta-data-for-bag-files-td913046.html

migration of trac ticket 2864:
 https://code.ros.org/trac/ros/ticket/2864

**Comment by dirk-thomas** [comment]
This wont be implemented as it is also possible to use existing ways to structure large number of bag files (i.e. file system folder hierarchy and reasonable filenames).
