### ISSUE TITLE
rosparam/roslaunch: list params put on param server and their values

### ISSUE THREAD

**Issue by 130s** [ros/ros_comm#96]
Migrated from https://code.ros.org/trac/ros/ticket/3924
Reported by:    bcohen  Owned by:   kwc
Priority:   minor 
Attachment available: No
Last modified ago: May 2012

---

**use case**

I have a master launch file that includes many launch files and each of them may include many yaml files with many rosparams. A few of the launch files put pr2_planning_description.yaml on the param server because it is a very very popular file. As it turns out, they all don't reference the same version of the file and one of them places a broken copy of that file on the param server.

It's difficult to debug this problem because the files could be put on the param server in different orders every time I relaunch my master launch file. So, sometimes it works and sometimes it doesn't. Also, remember that I have no idea that it's a param problem in the first place until I start digging. Once it pops into my head that it may be a param problem, I need to search through all of the included launch files and very carefully look through them for the broken yaml file. So, even after I realize my stupid mistake - it still may take time to hunt down that file.

**proposed functionality**

Params can be the source of many problems. Especially on a large project like the sushi challenge. I don't know if this is the smartest solution but it is a clear one.

I propose that either roslaunch (or rosparam?) has some additional functionality that can be specified with some flag.

roslaunch --list-params master.launch

The 'list-params' would list all of the fully defined params that are put on the param server in the yaml-format (fully defined - I mean with their namespaces). Most importantly, it will list all of the duplicates as well. So, if I want to pipe it to a yaml file, then I can rosparam load the resulting file. Then I can grep through that file and find the offending params.

simpler solution:

Alternatively, roslaunch can just give me a warning if I am loading up the same exact param more than once. In that case, it would give me the warning with the param name, locations in the launch files where it occurs.

This might already exist and if so, sorry for making you read my nonsense.

Thanks for considering this.

P.S. roslaunch currently lists the params that are put on the param server at the top of its output. It would be a nice convenience if it can output the values as well...this isn't my major concern but it's just a thought.

**Comment by dirk-thomas** [comment]
The printing of the parameter values in roslaunch is addressed in #397.

Furthermore there is the `--dump-params` option which will output all parameters in yaml format.

Since setting the same parameter multiple times (especially when using nested launch files) is not necessary an error but intended there shouldn't be a warning for these cases.
