### ISSUE TITLE
rosbag: info fails with "unknown bag version" on bags with future minor version

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#97]
Writing a bag with a minor version number from the future (e.g. 201 for D Turtle) makes rosbag info fail with:

```
ERROR reading test_future_version_works.bag: unknown bag version 201
```

We've committed to minor versions being backwards compatible, so this is a defect.

migration of trac ticket 3227:

change history:
https://code.ros.org/trac/ros/ticket/3227

Changed 2 years ago by tfield 

Need to add dependency for C++ future version unit test on Python unit test for creating bag, e.g.

ADD_DEPENDENCIES(test_bag test/test_bag.py)

**Comment by dirk-thomas** [comment]
This has already been addressed and is even covered by a unit test: https://github.com/ros/ros_comm/blob/416fc588e3b83beb4bb2526c81720e577cdc0a46/test/test_rosbag/test/test_bag.py#L234
