### ISSUE TITLE
rosbag: Use ros nodes to do offline processing with rosbag  

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#98]
I'm happy to implement this functionality, I just want some input about the preferred approach before I start writing code and submitting a patch.

So here's the issue. I've run into a bunch of situations where I want to do some offline processing of some data that I've previously recorded. This could be because it's a new process that wasn't around when I recorded it, or the process could just be too slow to run in realtime. I could do this using the rosbag API, but that's annoying because now the code won't be usable in a running system. To be able to run in the system, I'd normally create a new rosnode that listens to some topic and outputs messages on a new topic. Sure, I could refactor the common code between these two modes, but having to do that all the time is annoying. It would be better if I could just write the code for the node and then have rosbag play (and record) at the same speed that my node is processing the data. This would all be controlled with a launch file.

I'm thinking that one way to implement this functionality would be to use a similar mechanism to what rosbag uses to speed or slow down a feed by a constant rate. However, instead of triggering new messages from a timer, the user would specify two topics (and message types?). The first would be the topic in the existing bag to synchronize and the second would be the topic to listen to output messages from which we'll use as a trigger. rosbag would play messages from the bag until the next message in the synchronize topic. It would then block until it hears a new message on the trigger topic (or a timeout).

Would this be reasonable to implement? Do you have similar functionality in the pipeline already that I could just help with instead? Is there a different approach that you'd prefer?

migration of trac ticket 3298:
https://code.ros.org/trac/ros/ticket/3298

Change History:

Changed 2 years ago by leibs 

The need for this kind of pipeline has come up numerous times. Unfortunately, in all but the simplest cases, the mechanism for triggering/syncing is not entirely obvious.

The worst complication typically involves the processing node needing information from multiple topics, and the temporal ordering of those topics not being consistent.

But, if you're willing to take a crack at creating the patch to do what you want, it sounds like a pretty reasonable starting point. My recommendation for an API that feels like it fits nicely into rosbag play and gives you the functionality you want:

First, add an option to parameterize the step synchronization topic. This option would impact how stepping through a bag operates when a bag is paused. Rather than playing the next topic, it would play all topics until the next instance of the step topic.
Next, add a step trigger topic. The callback for this topic would essentially do the same thing as hitting "s" when the bag is paused. This topic would be subscribed to using \* type so that you could use an arbitrary topic for it. This will be a little trickier to implement since the code path that checks for hitting s isn't super clean. My guess though is a (mutex-locked) counter that gets incremented on the callback, and checked in the same place that the 's' processing happens would do the tricky though.

**Comment by dirk-thomas** [comment]
The decision when to pause/resume the playback of a rosbag is highly application specific. It is not likely that this functionality can be provided in a generic-enough way. It might be best to use the rosbag API and perform the stepping through the log file based on the application specific needs and knowledge about the processed messages.

Therefore closing this ticket.

**Comment by protobits** [comment]
Hi, I've developed something along this lines. It is something like a rosbag play tool clone, which publishes and then waits for acknowledgment for the receiver via a Trigger service call. It works very well and also managed to handle the case of a subscriber expecting a sinchronized tuple of messages with matching timestamps.

You can find it here: https://github.com/lrse/batch_ros
