### ISSUE TITLE
rosbag::Bag copy/move crash

### ISSUE THREAD

**Issue by racko** [ros/ros_comm#999]
Copying (or moving in C++11 and later) rosbag::Bag causes crashes. I guess that Bags are not meant to be copied / moved. Using C++11 semantics, copying does not make sense, just as std::fstream is not copyable. Making them movable would be a benefit in C++11 but since rosbag_storage uses C++98, we cannot implement move assignment / move constructors explicitly and would have to use copy assignment / copy constructors instead, which is considered a bad design. A swap() member function should be implemented to do that. Copy assignment and copy constructor should be disabled by making them private without giving an implementation.

```
#include <rosbag/bag.h>
#include <std_msgs/String.h>

int main() {
    rosbag::Bag bag1("/tmp/out.bag", rosbag::bagmode::Write);
    //auto bag2 = std::move(bag1);
    auto bag2 = bag1;
    bag2.write("/data", ros::Time(0, 1), std_msgs::String());
    return 0;
}
```

**Comment by dirk-thomas** [comment]
Addressed by #1000.
